In [ ]:
{
 "metadata": {
  "name": "",
  "signature": "sha256:341bd633a049b52ca86829ec3fe495dd8d46f9c777d406dc983cba82af66ada6"
 },
 "nbformat": 3,
 "nbformat_minor": 0,
 "worksheets": [
  {
   "cells": [
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "import numpy as np, requests, zipfile, StringIO, pandas as pd, json, copy"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [],
     "prompt_number": 421
    },
    {
     "cell_type": "markdown",
     "metadata": {},
     "source": [
      "Connect to the FAO database and define indicator paths. Alternatively, the FAO databse is mirrored at the project website."
     ]
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "masterpath = 'http://faostat.fao.org/Portals/_Faostat/Downloads/zip_files/'\n",
      "#masterpath = 'http://food.csaladen.es/db/' #alternative mirror for entire FAO database\n",
      "localpath=True\n",
      "if localpath:\n",
      "    masterpath = 'E:/Skydrive/Documents/GitHub/Food-Energy/db/' #local path for downloaded FAO database, only for developer purposes\n",
      "indicators=[]\n",
      "indicators.append('CommodityBalances_Crops_E_All_Data') #0\n",
      "indicators.append('CommodityBalances_LivestockFish_E_All_Data') #1\n",
      "indicators.append('Emissions_Agriculture_Burning_crop_residues_E_All_Data') #2\n",
      "indicators.append('Emissions_Agriculture_Energy_E_All_Data') #3\n",
      "indicators.append('Emissions_Agriculture_Synthetic_Fertilizers_E_All_Data') #4\n",
      "indicators.append('Environment_Energy_E_All_Data') #5\n",
      "indicators.append('FoodBalanceSheets_E_All_Data') #6\n",
      "indicators.append('FoodSupply_Crops_E_All_Data') #7\n",
      "indicators.append('FoodSupply_LivestockFish_E_All_Data') #8\n",
      "indicators.append('Population_E_All_Data') #9\n",
      "indicators.append('Production_Crops_E_All_Data') #10\n",
      "indicators.append('Production_CropsProcessed_E_All_Data') #11\n",
      "indicators.append('Production_Livestock_E_All_Data') #12\n",
      "indicators.append('Production_LivestockPrimary_E_All_Data') #13\n",
      "indicators.append('Production_LivestockProcessed_E_All_Data') #14\n",
      "indicators.append('Resources_Fertilizers_E_All_Data') #15\n",
      "indicators.append('Resources_FertilizersArchive_E_All_Data') #16"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [],
     "prompt_number": 2
    },
    {
     "cell_type": "markdown",
     "metadata": {},
     "source": [
      "Select indicator and import data from the CSV from within the zip file. This can take anywhere from a few minutes to several hours, depending on your computer's performance. If you have access to paralell computing capabilites please turn them on at the *Clusters* tab of the main Ipython window. "
     ]
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "def get_data(ind):\n",
      "    if localpath:\n",
      "        r = masterpath+indicators[ind]+'.zip'\n",
      "        z = zipfile.ZipFile(r)\n",
      "    else:\n",
      "        r = requests.get(masterpath+indicators[ind]+'.zip')\n",
      "        z = zipfile.ZipFile(StringIO.StringIO(r.content))\n",
      "    return pd.read_csv(z.open(indicators[ind]+'.csv'))\n",
      "\n",
      "balance = get_data(6)\n",
      "energy = get_data(3)\n",
      "fertilizers1 = get_data(15)\n",
      "fertilizers2 = get_data(16)\n",
      "population = get_data(9)\n",
      "print set(balance.Element)\n",
      "print set(energy.Element)\n",
      "print set(fertilizers1.Element)\n",
      "print set(fertilizers2.Element)\n",
      "print set(population.Element)"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "output_type": "stream",
       "stream": "stdout",
       "text": [
        "set(['Feed', 'Stock Variation', 'Protein supply quantity', 'Food', 'Processing', 'Other Util', 'Food supply', 'Domestic supply quantity', 'Fat supply quantity', 'Seed', 'Food supply quantity (kg/capita', 'Total Population - Both sexes', 'Waste', 'Production', 'Import Quantity', 'Export Quantity'])\n",
        "set(['Emissions (CO2eq) (Energy)', 'Consumption in Agriculture', 'Emissions (N2O) (Energy)', 'Implied emission factor for CO2', 'Emissions (CH4) (Energy)', 'Implied emission factor for CH4', 'Emissions (CO2eq) from CH4 (Energy)', 'Emissions (CO2eq) from N2O (Energy)', 'Emissions (CO2) (Energy)', 'Implied emission factor for N2O'])\n",
        "set(['Export Quantity in nutrients', 'Consumption', 'Export Quantity', 'Consumption in nutrients', 'Non-fertilizer use', 'Production Quantity in nutrients', 'Non-fertilizer use in nutrients', 'Production', 'Import Quantity', 'Import Quantity in nutrients'])\n",
        "set(['Export Quantity', 'Prices Paid by Farmers', 'Production', 'Import Quantity', 'Consumption'])"
       ]
      },
      {
       "output_type": "stream",
       "stream": "stdout",
       "text": [
        "\n",
        "set(['Total economically active population in Agr', 'Total Population - Male', 'Total Population - Female', 'Total economically active population', 'Rural population', 'Female economically active population', 'Urban population', 'Male economically active population in Agr', 'Male economically active population', 'Female economically active population in Agr', 'Total Population - Both sexes'])\n"
       ]
      }
     ],
     "prompt_number": 489
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "data = population\n",
      "print set(data[((data.Element=='Total economically active population in Agr')&(data.Year==2003)&(data.Country=='Brazil'))].Item)\n",
      "data[((data.Element=='Total economically active population in Agr')&(data.Year==2003)&(data.Country=='Brazil'))]"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "output_type": "stream",
       "stream": "stdout",
       "text": [
        "set(['Population - Est. & Proj.'])\n"
       ]
      },
      {
       "html": [
        "<div style=\"max-height:1000px;max-width:1500px;overflow:auto;\">\n",
        "<table border=\"1\" class=\"dataframe\">\n",
        "  <thead>\n",
        "    <tr style=\"text-align: right;\">\n",
        "      <th></th>\n",
        "      <th>CountryCode</th>\n",
        "      <th>Country</th>\n",
        "      <th>ItemCode</th>\n",
        "      <th>Item</th>\n",
        "      <th>ElementGroup</th>\n",
        "      <th>ElementCode</th>\n",
        "      <th>Element</th>\n",
        "      <th>Year</th>\n",
        "      <th>Unit</th>\n",
        "      <th>Value</th>\n",
        "      <th>Flag</th>\n",
        "    </tr>\n",
        "  </thead>\n",
        "  <tbody>\n",
        "    <tr>\n",
        "      <th>42040</th>\n",
        "      <td> 21</td>\n",
        "      <td> Brazil</td>\n",
        "      <td> 3010</td>\n",
        "      <td> Population - Est. &amp; Proj.</td>\n",
        "      <td> 601</td>\n",
        "      <td> 601</td>\n",
        "      <td> Total economically active population in Agr</td>\n",
        "      <td> 2003</td>\n",
        "      <td> 1000</td>\n",
        "      <td> 12805</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "  </tbody>\n",
        "</table>\n",
        "<p>1 rows \u00d7 11 columns</p>\n",
        "</div>"
       ],
       "metadata": {},
       "output_type": "pyout",
       "prompt_number": 488,
       "text": [
        "       CountryCode Country  ItemCode                       Item  ElementGroup  \\\n",
        "42040           21  Brazil      3010  Population - Est. & Proj.           601   \n",
        "\n",
        "       ElementCode                                      Element  Year  Unit  \\\n",
        "42040          601  Total economically active population in Agr  2003  1000   \n",
        "\n",
        "       Value Flag  \n",
        "42040  12805  NaN  \n",
        "\n",
        "[1 rows x 11 columns]"
       ]
      }
     ],
     "prompt_number": 488
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "def add_to_json(data,i,source,target,value,prod,supply):\n",
      "    global groupdict\n",
      "    global count\n",
      "    if (~np.isnan(value)&(value!=0)):\n",
      "        if source not in groupdict[i]: \n",
      "            groupdict[i][source]=count[i]\n",
      "            data[i][\"nodes\"].append({\"name\":source})\n",
      "            count[i] += 1 \n",
      "        if target not in groupdict[i]: \n",
      "            groupdict[i][target]=count[i]\n",
      "            data[i][\"nodes\"].append({\"name\":target})\n",
      "            count[i] += 1 \n",
      "        links_innerdict={} \n",
      "        links_innerdict[\"source\"]=groupdict[i][source]\n",
      "        links_innerdict[\"target\"]=groupdict[i][target]\n",
      "        links_innerdict[\"value\"]=value\n",
      "        links_innerdict[\"prod\"]=prod\n",
      "        links_innerdict[\"supply\"]=supply\n",
      "        data[i][\"links\"].append(links_innerdict)\n",
      "\n",
      "#elements1=['Feed','Food','Processing','Other Util','Seed','Waste','Stock Variation','Import Quantity','Export Quantity']\n",
      "elements1=['Feed','Food','Processing','Other Util','Seed','Waste']\n",
      "elements2=['Food supply','Food supply quantity (kg/capita']\n",
      "fuels=['Gas-diesel oils', 'Natural gas (including LNG)', 'Residual fuel oil', 'Liquefied petroleum gas (LPG)']\n",
      "fert1=['Phosphate fertilizers', 'Potash fertilizers', 'Nitrogenous fertilizers']\n",
      "fert2=['Potash Fertilizers (K20 total nutrients)', 'Phosphate Fertilizers (P205 total nutrients)', 'Nitrogen Fertilizers (N total nutrients)']\n",
      "#for country in set(data.Country.values):\n",
      "for country in ['United States of America', 'Canada', 'China', 'India']:    #['World + (Total)']\n",
      "   #for year in set(balance[balance.Country==country].Year.values):\n",
      "   for year in range(1981,2009):\n",
      "     #try:\n",
      "            \n",
      "        ###############################################################################################\n",
      "        ######                                   FOOD PART                                       ######\n",
      "        ###############################################################################################\n",
      "        \n",
      "        #initialize food output variable for sum collection and processing for EROEI\n",
      "        foodoutput=0\n",
      "        \n",
      "        # associate food items to their respective groups\n",
      "        n = 4          #number of grouping variations\n",
      "        supergroup=[]  #group to which food item entry belongs to. defined below, custom groups possible, along the FAO official ones \n",
      "        parent={}      #food item parent(source) node, where applicable (secondary food items), i.e. Feed for Animal Products or Milk for Cheese\n",
      "        for i in range (n):\n",
      "            supergroup.append({})\n",
      "        \n",
      "        for i in balance[(balance.Element==\"Food\")&(balance.Year==year)&(balance.Country==country)\\\n",
      "                          &(((2511<=balance.ItemCode)&(balance.ItemCode<=2782))\\\n",
      "                          |(balance.ItemCode==2805)\\\n",
      "                          |(balance.ItemCode==2899)\\\n",
      "                          |(balance.ItemCode==2912)\\\n",
      "                          |(balance.ItemCode==2945)\\\n",
      "                          |(balance.ItemCode==2948)\\\n",
      "                          |(balance.ItemCode==2949)\\\n",
      "                          |(balance.ItemCode==2961))].values:\n",
      "            fooditem=i[3]         #choose column in which food item names are stored, might need to change it\n",
      "            if \"+\" in fooditem:   #simplify food names for the sake of visualization\n",
      "                fooditem=fooditem[0:fooditem.find(\"+\")-1]\n",
      "            if \"(\" in fooditem:\n",
      "                fooditem=fooditem[0:fooditem.find(\"(\")-1]\n",
      "            if \"and products\" in fooditem:\n",
      "                fooditem=fooditem[0:fooditem.find(\"and products\")-1]\n",
      "            index = i[2]         #choose column in which food group codes are stored, might need to change it\n",
      "            parent[fooditem]='None'\n",
      "            for i in range (n):  #assign default supergroup 'Others' and no parent to all food items\n",
      "                supergroup[i][fooditem]='Others'\n",
      "            if ((2511<=index<=2659) | (index==2745) | (index==2805) | (index==2899) | (index==2912)):\n",
      "                if ((2511<=index<=2520) | (index==2805)):\n",
      "                    supergroup[1][fooditem] = 'Cereals - Excluding Beer'\n",
      "                    supergroup[0][fooditem] = 'Cereals'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'None'\n",
      "                elif (2531<=index<=2535):\n",
      "                    supergroup[1][fooditem] = 'Starchy Roots'\n",
      "                    supergroup[0][fooditem] = 'Starchy Roots'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'None'\n",
      "                elif (2536<=index<=2537):\n",
      "                    supergroup[1][fooditem] = 'Sugar Crops'\n",
      "                    supergroup[0][fooditem] = 'Sugar Crops'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'None'\n",
      "                elif ((2541<=index<=2543)|(index==2745)):\n",
      "                    supergroup[1][fooditem] = 'Sugar & Sweeteners'\n",
      "                    supergroup[0][fooditem] = 'Sugar'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'Processing'\n",
      "                elif (2546<=index<=2549):\n",
      "                    supergroup[1][fooditem] = 'Pulses'\n",
      "                    supergroup[0][fooditem] = 'Fruits & Vegetables'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'None'\n",
      "                elif (2555<=index<=2570):\n",
      "                    supergroup[1][fooditem] = 'Oilcrops'\n",
      "                    supergroup[0][fooditem] = 'Oilcrops'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'None'\n",
      "                elif (2571<=index<=2586):\n",
      "                    supergroup[1][fooditem] = 'Vegetable Oils'\n",
      "                    supergroup[0][fooditem] = 'Vegetable Oils'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'Processing'\n",
      "                elif (2601<=index<=2605):\n",
      "                    supergroup[1][fooditem] = 'Vegetables'\n",
      "                    supergroup[0][fooditem] = 'Fruits & Vegetables'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'None'\n",
      "                elif (2611<=index<=2625):\n",
      "                    supergroup[1][fooditem] = 'Fruits - Excluding Wine'\n",
      "                    supergroup[0][fooditem] = 'Fruits & Vegetables'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'None'\n",
      "                elif (2630<=index<=2635):\n",
      "                    supergroup[1][fooditem] = 'Stimulants'\n",
      "                    supergroup[0][fooditem] = 'Others'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'None'\n",
      "                elif (2640<=index<=2645):\n",
      "                    supergroup[1][fooditem] = 'Spices'\n",
      "                    supergroup[0][fooditem] = 'Others'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'None'\n",
      "                elif (2655<=index<=2659):\n",
      "                    supergroup[1][fooditem] = 'Alcoholic Beverages'\n",
      "                    supergroup[0][fooditem] = 'Other Processed'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'Processing'\n",
      "                elif (index==2899):\n",
      "                    supergroup[1][fooditem] = 'Miscellaneous'\n",
      "                    supergroup[0][fooditem] = 'Others'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'None'\n",
      "                elif (index==2912):\n",
      "                    supergroup[1][fooditem] = 'Treenuts'\n",
      "                    supergroup[0][fooditem] = 'Fruits & Vegetables'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'None'\n",
      "                       \n",
      "            elif ((2731<=index<=2782) | (index==2945)| (index==2948) | (index==2949) | (index==2961)):\n",
      "                if (2731<=index<=2736):\n",
      "                    supergroup[1][fooditem] = 'Meat'\n",
      "                    supergroup[0][fooditem] = 'Animal Products'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'Feed'\n",
      "                elif (2737<=index<=2743):\n",
      "                    supergroup[1][fooditem] = 'Animal Fats'  \n",
      "                    supergroup[0][fooditem] = 'Other Processed' \n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'Processing'\n",
      "                elif (2761<=index<=2768):\n",
      "                    supergroup[1][fooditem] = 'Fish, Seafood'\n",
      "                    supergroup[0][fooditem] = 'Aquatic Products'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'Feed'\n",
      "                elif ((2769<=index<=2775)|(index==2961)):\n",
      "                    supergroup[1][fooditem] = 'Aquatic Products, Other'\n",
      "                    supergroup[0][fooditem] = 'Aquatic Products'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'Feed'\n",
      "                elif (2781<=index<=2782):\n",
      "                    supergroup[1][fooditem] = 'Animal Fats'\n",
      "                    supergroup[0][fooditem] = 'Other Processed'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'Processing'\n",
      "                elif (index==2945):\n",
      "                    supergroup[1][fooditem] = 'Offals'\n",
      "                    supergroup[0][fooditem] = 'Animal Products'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'Feed'\n",
      "                elif (index==2948):\n",
      "                    supergroup[1][fooditem] = 'Milk - Excluding Butter'\n",
      "                    supergroup[0][fooditem] = 'Animal Products'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'Feed'\n",
      "                elif (index==2949):\n",
      "                    supergroup[1][fooditem] = 'Eggs'    \n",
      "                    supergroup[0][fooditem] = 'Animal Products'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'Feed'\n",
      "        \n",
      "        #extract food item caloric values\n",
      "        percapitasupply={}\n",
      "        percapitaenergy={}\n",
      "        for i in balance[(balance.Element=='Food supply')&(balance.Year==year)&(balance.Country==country)].values:\n",
      "            foodvalue=i[9]        #choose column in which food item values are stored, might need to change it\n",
      "            fooditem=i[3]         #choose column in which food item names are stored, might need to change it\n",
      "            if \"+\" in fooditem:   #simplify food names for the sake of visualization\n",
      "                fooditem=fooditem[0:fooditem.find(\"+\")-1]\n",
      "            if \"(\" in fooditem:\n",
      "                fooditem=fooditem[0:fooditem.find(\"(\")-1]\n",
      "            if \"and products\" in fooditem:\n",
      "                fooditem=fooditem[0:fooditem.find(\"and products\")-1]\n",
      "            percapitaenergy[fooditem]=foodvalue\n",
      "        \n",
      "        for i in balance[(balance.Element=='Food supply quantity (kg/capita')&(balance.Year==year)&(balance.Country==country)].values:\n",
      "            foodvalue=i[9]        #choose column in which food item values are stored, might need to change it\n",
      "            fooditem=i[3]         #choose column in which food item names are stored, might need to change it\n",
      "            if \"+\" in fooditem:   #simplify food names for the sake of visualization\n",
      "                fooditem=fooditem[0:fooditem.find(\"+\")-1]\n",
      "            if \"(\" in fooditem:\n",
      "                fooditem=fooditem[0:fooditem.find(\"(\")-1]\n",
      "            if \"and products\" in fooditem:\n",
      "                fooditem=fooditem[0:fooditem.find(\"and products\")-1]\n",
      "            percapitasupply[fooditem]=foodvalue*1000/365.25 #kg/year/capita->g/day/capita\n",
      "        \n",
      "        foodcalorie={}\n",
      "        for i in percapitasupply:\n",
      "            foodcalorie[i]=100  #set default caloric value for all food items, necessary to handle exceptions\n",
      "            if i in percapitaenergy:\n",
      "                if ((percapitasupply[i]==0)|(percapitaenergy[i]==0)): #if either term is null, try to assing the supergroup values, if they exist\n",
      "                    if ((i in supergroup[1])&(supergroup[1][i] in percapitasupply)&(supergroup[1][i] in percapitaenergy)):\n",
      "                        if ((percapitasupply[supergroup[1][i]]!=0)&(percapitaenergy[supergroup[1][i]]!=0)):\n",
      "                            foodcalorie[i]=100*percapitaenergy[supergroup[1][i]]/percapitasupply[supergroup[1][i]]\n",
      "                else:\n",
      "                    foodcalorie[i]=100*percapitaenergy[i]/percapitasupply[i]\n",
      "        \n",
      "        #extract supply data and calculate energy data\n",
      "        energydata=[]  #initialize dictionary array for later JSON export for D3 & sankey.js visualization\n",
      "        supplydata=[]  #initialize dictionary array for later JSON export for D3 & sankey.js visualization\n",
      "        count = []     #counter for the groupdict below\n",
      "        groupdict=[{}] #initialize dictionary for mapping food category names to JSON, in the order of addition - necessary format for sankey.js\n",
      "        parentsupplysum=[]   #dictionary to keep track of item sums in case of aggregations, based on the supergroup variable defined above\n",
      "        parentenergysum=[]   #dictionary to keep track of item sums in case of aggregations, based on the supergroup variable defined above    \n",
      "        for i in range (n):\n",
      "            energydata.append({\"nodes\":[],\"links\":[]})\n",
      "            supplydata.append({\"nodes\":[],\"links\":[]})\n",
      "            count.append(0)\n",
      "            groupdict.append({})\n",
      "            supergroup.append({})\n",
      "            parentsupplysum.append({})\n",
      "            parentenergysum.append({})\n",
      "        \n",
      "        for element in elements1:\n",
      "            supplysum=[]   #dictionary to keep track of item sums in case of aggregations, based on the supergroup variable defined above\n",
      "            energysum=[]   #dictionary to keep track of item sums in case of aggregations, based on the supergroup variable defined above\n",
      "            for i in range (n):\n",
      "                supplysum.append({})\n",
      "                energysum.append({})\n",
      "            \n",
      "            for i in balance[(balance.Element==element)&(balance.Year==year)&(balance.Country==country)\\\n",
      "                          &(((2511<=balance.ItemCode)&(balance.ItemCode<=2782))\\\n",
      "                          |(balance.ItemCode==2805)\\\n",
      "                          |(balance.ItemCode==2899)\\\n",
      "                          |(balance.ItemCode==2912)\\\n",
      "                          |(balance.ItemCode==2945)\\\n",
      "                          |(balance.ItemCode==2948)\\\n",
      "                          |(balance.ItemCode==2949)\\\n",
      "                          |(balance.ItemCode==2961))].values:\n",
      "                foodvalue=i[9]            #choose column in which food item values are stored, might need to change it\n",
      "                if (~np.isnan(foodvalue)&(foodvalue!=0)):\n",
      "                    fooditem=i[3]         #choose column in which food item names are stored, might need to change it\n",
      "                    if \"+\" in fooditem:   #simplify food names for the sake of visualization\n",
      "                        fooditem=fooditem[0:fooditem.find(\"+\")-1]\n",
      "                    if \"(\" in fooditem:\n",
      "                        fooditem=fooditem[0:fooditem.find(\"(\")-1]\n",
      "                    if \"and products\" in fooditem:\n",
      "                        fooditem=fooditem[0:fooditem.find(\"and products\")-1]\n",
      "                    \n",
      "                    energyvalue=foodvalue*foodcalorie[fooditem]*0.00116222222/100\n",
      "                          #TWh = 1000tons * kcal/100g # 10^9) /100g * 0.00116222222 kwh/kcal *10^-9 TWh/kWh\n",
      " \n",
      "                   #create links for detail level 3    \n",
      "                    if (element==\"Seed\"):  #replace seed group with self-loops \n",
      "                        add_to_json(supplydata,2,fooditem,fooditem,foodvalue,energyvalue,'[{\"l\":'+repr(fooditem)+',\"v\":'+repr(foodvalue)+'}]')   \n",
      "                        add_to_json(energydata,2,fooditem,fooditem,energyvalue,foodvalue,'[{\"l\":'+repr(fooditem)+',\"v\":'+repr(energyvalue)+'}]')   \n",
      "                    else:\n",
      "                        add_to_json(supplydata,2,fooditem,element,foodvalue,energyvalue,'[{\"l\":'+repr(fooditem)+',\"v\":'+repr(foodvalue)+'}]')\n",
      "                        add_to_json(energydata,2,fooditem,element,energyvalue,foodvalue,'[{\"l\":'+repr(fooditem)+',\"v\":'+repr(energyvalue)+'}]')\n",
      "                    \n",
      "                        #sum all links going into food for sepparate representation\n",
      "                        if (element==\"Food\"):\n",
      "                            foodoutput+=energyvalue\n",
      "                        \n",
      "                    #create aggregate values for parent links detail level 3\n",
      "                    if fooditem in parentsupplysum[2]:\n",
      "                        parentsupplysum[2][fooditem]+=foodvalue\n",
      "                        parentenergysum[2][fooditem]+=energyvalue\n",
      "                    else:\n",
      "                        parentsupplysum[2][fooditem]=foodvalue\n",
      "                        parentenergysum[2][fooditem]=energyvalue\n",
      "                    \n",
      "                    #create aggregate values for detail levels 1-2\n",
      "                    for i in range(2): #sum food item values over different groups, defined above, currently 1-2\n",
      "                        #save sum, but also components for the piechart breakdown\n",
      "                        if supergroup[i][fooditem] in supplysum[i]:\n",
      "                            supplysum[i][supergroup[i][fooditem]][\"data\"].append({\"l\":fooditem, \"v\":foodvalue})\n",
      "                            supplysum[i][supergroup[i][fooditem]][\"sum\"]+=foodvalue\n",
      "                            energysum[i][supergroup[i][fooditem]][\"data\"].append({\"l\":fooditem, \"v\":energyvalue})\n",
      "                            energysum[i][supergroup[i][fooditem]][\"sum\"]+=energyvalue\n",
      "                        else:\n",
      "                            supplysum[i][supergroup[i][fooditem]]={\"data\":[{\"l\":fooditem, \"v\":foodvalue}],\"sum\":foodvalue}\n",
      "                            energysum[i][supergroup[i][fooditem]]={\"data\":[{\"l\":fooditem, \"v\":energyvalue}],\"sum\":energyvalue}\n",
      "            \n",
      "            #create links for detail levels 1-2    \n",
      "            for i in range(2):\n",
      "                for j in supplysum[i]:\n",
      "                    if (element==\"Seed\"):\n",
      "                        add_to_json(supplydata,i,j,j,supplysum[i][j][\"sum\"],energysum[i][j][\"sum\"],supplysum[i][j][\"data\"])\n",
      "                        add_to_json(energydata,i,j,j,energysum[i][j][\"sum\"],supplysum[i][j][\"sum\"],energysum[i][j][\"data\"])\n",
      "                    else:\n",
      "                        add_to_json(supplydata,i,j,element,supplysum[i][j][\"sum\"],energysum[i][j][\"sum\"],supplysum[i][j][\"data\"])\n",
      "                        add_to_json(energydata,i,j,element,energysum[i][j][\"sum\"],supplysum[i][j][\"sum\"],energysum[i][j][\"data\"])\n",
      "            \n",
      "            #create aggregate values for parent links detail levels 1-2\n",
      "            for i in range(2):\n",
      "                for j in set(supplysum[i]):\n",
      "                    if j in parentsupplysum[i]:\n",
      "                        parentsupplysum[i][j]+=supplysum[i][j][\"sum\"]\n",
      "                        parentenergysum[i][j]+=energysum[i][j][\"sum\"]\n",
      "                    else:\n",
      "                        parentsupplysum[i][j]=supplysum[i][j][\"sum\"]\n",
      "                        parentenergysum[i][j]=energysum[i][j][\"sum\"]\n",
      "                   \n",
      "        #create parent links for detail levels 1-3\n",
      "        for i in range(3):    \n",
      "            for j in parentsupplysum[i]:\n",
      "                if (parent[j]!=\"None\"):\n",
      "                    add_to_json(supplydata,i, parent[j],j,parentsupplysum[i][j],parentenergysum[i][j],'[{\"l\":'+repr( parent[j])+',\"v\":'+repr(parentsupplysum[i][j])+'}]')\n",
      "                    add_to_json(energydata,i, parent[j],j,parentenergysum[i][j],parentsupplysum[i][j],'[{\"l\":'+repr( parent[j])+',\"v\":'+repr(parentenergysum[i][j])+'}]')\n",
      "        \n",
      "        #update nodes name map\n",
      "        for i in range(n):\n",
      "            energydata[i]['nodes']=supplydata[i]['nodes']\n",
      "            \n",
      "        ###############################################################################################\n",
      "        ######                                   FUEL PART                                       ######\n",
      "        ###############################################################################################\n",
      "        \n",
      "        #calculate crops share for energy input distribution\n",
      "        supplyshare=[]\n",
      "        energyshare=[]\n",
      "        fuelenergysum=[]\n",
      "        for i in range (n):\n",
      "            supplyshare.append({})\n",
      "            energyshare.append({})\n",
      "            fuelenergysum.append({})\n",
      "        \n",
      "        cropsum=[]\n",
      "        cropenergy=[]\n",
      "        for i in range(n):\n",
      "            cropsum.append(0)\n",
      "            cropenergy.append(0)\n",
      "            for j in parentsupplysum[i]:\n",
      "                if (parent[j]=='None'):\n",
      "                    cropsum[i] += parentsupplysum[i][j]\n",
      "                    cropenergy[i] += parentenergysum[i][j]\n",
      "        \n",
      "        for i in range(n):\n",
      "            for j in parentsupplysum[i]:\n",
      "                if (parent[j]=='None'):\n",
      "                    supplyshare[i][j] = parentsupplysum[i][j]/cropsum[i]\n",
      "                    energyshare[i][j] = parentenergysum[i][j]/cropenergy[i]\n",
      "        \n",
      "        #distribute electricity input\n",
      "        for fuel in ['Electricity']:\n",
      "            for i in energy[(energy.Element=='Consumption in Agriculture')&(energy.Year==year)&(energy.Country==country)\\\n",
      "                            &(energy.Unit=='Terajoule')&(energy.Item==fuel)].values:\n",
      "                fuelvalue=i[9]            #choose column in which fuel item values are stored, might need to change it\n",
      "                if (~np.isnan(fuelvalue)&(fuelvalue!=0)):\n",
      "                    fuelitem=i[3]         #choose column in which fuel item names are stored, might need to change it\n",
      "                    if \"+\" in fuelitem:   #simplify fuel names for the sake of visualization\n",
      "                        fuelitem=fuelitem[0:fuelitem.find(\"+\")-1]\n",
      "                    if \"(\" in fooditem:\n",
      "                        fuelitem=fuelitem[0:fuelitem.find(\"(\")-1]\n",
      "                    if \"and products\" in fuelitem:\n",
      "                        fuelitem=fuelitem[0:fuelitem.find(\"and products\")-1]\n",
      "                    electricityvalue=fuelvalue*0.000277777778 #1 joule = 0.000277777778 Wh\n",
      "                    for i in range(n):\n",
      "                        for j in parentsupplysum[i]:\n",
      "                            if (parent[j]=='None'):\n",
      "                                add_to_json(energydata,i, fuel,j,electricityvalue*energyshare[i][j],0,'[{\"l\":'+repr(fuel)+',\"v\":'+repr(electricityvalue*energyshare[i][j])+'}]')\n",
      "         \n",
      "        #distribute fossil fuel input\n",
      "        for fuel in fuels:\n",
      "            for i in energy[(energy.Element=='Consumption in Agriculture')&(energy.Year==year)&(energy.Country==country)\\\n",
      "                            &(energy.Unit=='Terajoule')&(energy.Item==fuel)].values:\n",
      "                fuelvalue=i[9]            #choose column in which fuel item values are stored, might need to change it\n",
      "                if (~np.isnan(fuelvalue)&(fuelvalue!=0)):\n",
      "                    fuelitem=i[3]         #choose column in which fuel item names are stored, might need to change it\n",
      "                    if \"+\" in fuelitem:   #simplify fuel names for the sake of visualization\n",
      "                        fuelitem=fuelitem[0:fuelitem.find(\"+\")-1]\n",
      "                    if \"(\" in fooditem:\n",
      "                        fuelitem=fuelitem[0:fuelitem.find(\"(\")-1]\n",
      "                    if \"and products\" in fuelitem:\n",
      "                        fuelitem=fuelitem[0:fuelitem.find(\"and products\")-1]\n",
      "                    fuelvalue*=0.000277777778 #1 joule = 0.000277777778 Wh\n",
      "                    for i in range(n): #sum fuel item values over all groups\n",
      "                        supergroup[i][fuelitem]=\"Fossil Fuels\"\n",
      "                        #save sum, but also components for the piechart breakdown\n",
      "                        if supergroup[i][fuelitem] in fuelenergysum[i]:\n",
      "                            fuelenergysum[i][supergroup[i][fuelitem]][\"data\"].append({\"l\":fuelitem, \"v\":fuelvalue})\n",
      "                            fuelenergysum[i][supergroup[i][fuelitem]][\"sum\"]+=fuelvalue\n",
      "                        else:\n",
      "                            fuelenergysum[i][supergroup[i][fuelitem]]={\"data\":[{\"l\":fuelitem, \"v\":fuelvalue}],\"sum\":fuelvalue}\n",
      "        f_save=copy.deepcopy(fuelenergysum)\n",
      "        for i in range(n):\n",
      "            for j in parentsupplysum[i]:\n",
      "                fuelenergysum=copy.deepcopy(f_save)\n",
      "                if (parent[j]=='None'):\n",
      "                    for k in fuelenergysum[i]:\n",
      "                        for f in fuelenergysum[i][k][\"data\"]:\n",
      "                            f[\"v\"]*=energyshare[i][j]\n",
      "                        add_to_json(energydata,i,k,j,fuelenergysum[i][k][\"sum\"]*energyshare[i][j],0,fuelenergysum[i][k][\"data\"])\n",
      "         \n",
      "        \n",
      "        ###############################################################################################\n",
      "        ######                                   FERTILIZERS PART                                ######\n",
      "        ###############################################################################################\n",
      "        \n",
      "        fertenergysum=[]\n",
      "        fertsupplysum=[]\n",
      "        for i in range (n):\n",
      "            fertenergysum.append({})\n",
      "            fertsupplysum.append({})\n",
      "        \n",
      "        if (year<2003):\n",
      "            fertilizers=fertilizers2 #inverted on purpose\n",
      "            fertnames=fert1\n",
      "            fertelement='Consumption'\n",
      "        else:\n",
      "            fertilizers=fertilizers1\n",
      "            fertnames=fert2\n",
      "            fertelement='Consumption in nutrients'\n",
      "        for fert in fertnames:\n",
      "            for i in fertilizers[(fertilizers.Element==fertelement)&(fertilizers.Year==year)&(fertilizers.Country==country)\\\n",
      "                            &(fertilizers.Item==fert)].values:\n",
      "                fertvalue=i[9]            #choose column in which fert item values are stored, might need to change it\n",
      "                if (~np.isnan(fertvalue)&(fertvalue!=0)):\n",
      "                    fertitem=i[3]         #choose column in which fert item names are stored, might need to change it\n",
      "                    #define energy content+packaging and transport (http://www.engr.usask.ca/societies/csae/c9915.pdf page10)\n",
      "                    if fertitem in ['Phosphate fertilizers', 'Phosphate Fertilizers (P205 total nutrients)']:\n",
      "                        fertenergycontent=6.82+8.33 #MJ/kg \n",
      "                        fertitem='Phosphate'\n",
      "                    if fertitem in ['Potash fertilizers', 'Potash Fertilizers (K20 total nutrients)']:\n",
      "                        fertenergycontent=2.88+6.35 #MJ/kg\n",
      "                        fertitem='Potash'\n",
      "                    if fertitem in ['Nitrogenous fertilizers', 'Nitrogen Fertilizers (N total nutrients)']:\n",
      "                        fertenergycontent=59+7.05 #MJ/kg\n",
      "                        fertitem='Nitrogen'\n",
      "                    \n",
      "                    fertvalue=fertvalue/1000 #model units are in 1000 tonnes\n",
      "                    fertenergy=fertvalue*fertenergycontent         *  0.000277777778   #TWh \n",
      "                                          #MJ/kg / TJ/1000tonnes   *  #1 joule = 0.000277777778 Wh\n",
      "                    for i in range(n): #sum fert item values over all groups\n",
      "                        supergroup[i][fertitem]=\"Fertilizers\"\n",
      "                        #save sum, but also components for the piechart breakdown\n",
      "                        if supergroup[i][fertitem] in fertenergysum[i]:\n",
      "                            fertenergysum[i][supergroup[i][fertitem]][\"data\"].append({\"l\":fertitem, \"v\":fertenergy})\n",
      "                            fertenergysum[i][supergroup[i][fertitem]][\"sum\"]+=fertenergy\n",
      "                            fertsupplysum[i][supergroup[i][fertitem]][\"data\"].append({\"l\":fertitem, \"v\":fertvalue})\n",
      "                            fertsupplysum[i][supergroup[i][fertitem]][\"sum\"]+=fertvalue\n",
      "                        else:\n",
      "                            fertenergysum[i][supergroup[i][fertitem]]={\"data\":[{\"l\":fertitem, \"v\":fertenergy}],\"sum\":fertenergy}\n",
      "                            fertsupplysum[i][supergroup[i][fertitem]]={\"data\":[{\"l\":fertitem, \"v\":fertvalue}],\"sum\":fertvalue}\n",
      "        f_save=copy.deepcopy(fertenergysum)\n",
      "        for i in range(n):\n",
      "            for j in parentsupplysum[i]:\n",
      "                fertenergysum=copy.deepcopy(f_save)\n",
      "                if (parent[j]=='None'):\n",
      "                    for k in fertenergysum[i]:\n",
      "                        for f in fertenergysum[i][k][\"data\"]:\n",
      "                            f[\"v\"]*=energyshare[i][j]\n",
      "                        add_to_json(energydata,i,k,j,fertenergysum[i][k][\"sum\"]*energyshare[i][j],fertsupplysum[i][k][\"sum\"]*energyshare[i][j],fertenergysum[i][k][\"data\"])\n",
      "           \n",
      "        ###############################################################################################\n",
      "        ######                                   LABOR PART                                      ######\n",
      "        ###############################################################################################\n",
      "        \n",
      "        calorietotal=balance[(balance.Element=='Food supply')&(balance.Year==year)&(balance.Country==country)\\\n",
      "                             &(balance.Item=='Grand Total + (Total)')].values[0][9] #second index: choose column in which pop item values are stored, might need to change it\n",
      "        popvalue=population[(population.Element=='Total economically active population in Agr')&(population.Year==year)\\\n",
      "                            &(population.Country==country)].values[0][9] #second index: choose column in which pop item values are stored, might need to change it\n",
      "        if (~np.isnan(popvalue)&(popvalue!=0)):\n",
      "            workyear=5.0/7.0*365.25   #working days spent with farming per year\n",
      "            \n",
      "            hourlycalorieburn=204        #calories needed per hour of farming\n",
      "            hoursperday=12               #hours per day spent farming\n",
      "            minimumcalorieburn=hourlycalorieburn*hoursperday\n",
      "            calorieburn=0.9              #percent of calorie intake burned for farming, if below minimum\n",
      "            \n",
      "            laborenergy=min(minimumcalorieburn,calorieburn*calorietotal)*workyear*popvalue*1000*0.00116222222/1000000000\n",
      "                                                                                              # 0.00116222222 kwh/kcal *10^-9 TWh/kWh\n",
      "            for i in range(n):\n",
      "                for j in parentsupplysum[i]:\n",
      "                    if (parent[j]=='None'):\n",
      "                        add_to_json(energydata,i,\"Labor\",j,laborenergy*energyshare[i][j],0,'[{\"l\":'+repr(\"Labor\")+',\"v\":'+repr(laborenergy*energyshare[i][j])+'}]')\n",
      "         \n",
      "        ###############################################################################################\n",
      "        ######                                   SAVE DATA                                       ######\n",
      "        ###############################################################################################\n",
      "        \n",
      "        for i in range(n):\n",
      "            file('../json/'+country+repr(year)+'d'+repr(i+1)+'.json','w').write(json.dumps(supplydata[i]))\n",
      "            file('../json/'+country+repr(year)+'e'+repr(i+1)+'.json','w').write(json.dumps(energydata[i]))\n",
      "        \n",
      "        #create global input-output graph    \n",
      "        fooddata={\"nodes\":[{\"name\": \"Input\"},{\"name\": \"Food\"},{\"name\": \"Output\"}],\"links\":[]}\n",
      "        foodinput=laborenergy+fertenergysum[0][\"Fertilizers\"][\"sum\"]+fuelenergysum[0][\"Fossil Fuels\"][\"sum\"]+electricityvalue\n",
      "        \n",
      "        links_innerdict={} \n",
      "        links_innerdict[\"source\"]=0\n",
      "        links_innerdict[\"target\"]=1\n",
      "        links_innerdict[\"value\"]=foodinput\n",
      "        fooddata[\"links\"].append(links_innerdict)\n",
      "        \n",
      "        links_innerdict={} \n",
      "        links_innerdict[\"source\"]=1\n",
      "        links_innerdict[\"target\"]=2\n",
      "        links_innerdict[\"value\"]=foodoutput\n",
      "        fooddata[\"links\"].append(links_innerdict)\n",
      "        \n",
      "        file('../json/'+country+repr(year)+'.json','w').write(json.dumps(fooddata)) \n",
      "     \n",
      "    #except:\n",
      "    #    KeyError        "
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "ename": "KeyError",
       "evalue": "'Fossil Fuels'",
       "output_type": "pyerr",
       "traceback": [
        "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m\n\u001b[1;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
        "\u001b[1;32m<ipython-input-571-5748d8e4a744>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m()\u001b[0m\n\u001b[0;32m    453\u001b[0m         \u001b[1;31m#create global input-output graph\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    454\u001b[0m         \u001b[0mfooddata\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;33m{\u001b[0m\u001b[1;34m\"nodes\"\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;33m{\u001b[0m\u001b[1;34m\"name\"\u001b[0m\u001b[1;33m:\u001b[0m \u001b[1;34m\"Input\"\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m{\u001b[0m\u001b[1;34m\"name\"\u001b[0m\u001b[1;33m:\u001b[0m \u001b[1;34m\"Food\"\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m{\u001b[0m\u001b[1;34m\"name\"\u001b[0m\u001b[1;33m:\u001b[0m \u001b[1;34m\"Output\"\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;34m\"links\"\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 455\u001b[1;33m         \u001b[0mfoodinput\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mlaborenergy\u001b[0m\u001b[1;33m+\u001b[0m\u001b[0mfertenergysum\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m\"Fertilizers\"\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m\"sum\"\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m+\u001b[0m\u001b[0mfuelenergysum\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m\"Fossil Fuels\"\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m\"sum\"\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m+\u001b[0m\u001b[0melectricityvalue\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    456\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    457\u001b[0m         \u001b[0mlinks_innerdict\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;33m{\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
        "\u001b[1;31mKeyError\u001b[0m: 'Fossil Fuels'"
       ]
      }
     ],
     "prompt_number": 571
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "try: \n",
      "    a=a[p]\n",
      "except:\n",
      "    KeyError"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [],
     "prompt_number": 569
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "popvalue=population[(population.Element=='Total economically active population in Agr')&(population.Year==1981)\\\n",
      "                            &(population.Country==country)].values[0][9]\n",
      "print popvalue"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "output_type": "stream",
       "stream": "stdout",
       "text": [
        "981259.0\n"
       ]
      }
     ],
     "prompt_number": 514
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "#energy[(energy.Element=='Consumption in Agriculture')&(balance.Year==2002)&(balance.Country==country)\\\n",
      "#                            &(energy.Unit=='Terajoule')&(energy.Item=='Electricty')]\n",
      "energy[(energy.Element=='Consumption in Agriculture')&(energy.Year==2002)&(energy.Country=='World + (Total)')]"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "html": [
        "<div style=\"max-height:1000px;max-width:1500px;overflow:auto;\">\n",
        "<table border=\"1\" class=\"dataframe\">\n",
        "  <thead>\n",
        "    <tr style=\"text-align: right;\">\n",
        "      <th></th>\n",
        "      <th>CountryCode</th>\n",
        "      <th>Country</th>\n",
        "      <th>ItemCode</th>\n",
        "      <th>Item</th>\n",
        "      <th>ElementGroup</th>\n",
        "      <th>ElementCode</th>\n",
        "      <th>Element</th>\n",
        "      <th>Year</th>\n",
        "      <th>Unit</th>\n",
        "      <th>Value</th>\n",
        "      <th>Flag</th>\n",
        "    </tr>\n",
        "  </thead>\n",
        "  <tbody>\n",
        "    <tr>\n",
        "      <th>346386</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6807</td>\n",
        "      <td>                                       Electricity</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td> 1312020.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>346387</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6807</td>\n",
        "      <td>                                       Electricity</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72182</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td> million kWh</td>\n",
        "      <td>  364449.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>346682</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6811</td>\n",
        "      <td>              Energy consumed in fishery + (Total)</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td>  383192.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>346986</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6808</td>\n",
        "      <td>                       Energy for power irrigation</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72182</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td> million kWh</td>\n",
        "      <td>  236328.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>346987</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6808</td>\n",
        "      <td>                       Energy for power irrigation</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td>  850780.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>347113</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6801</td>\n",
        "      <td>                                   Gas-diesel oils</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td> 3655110.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>347398</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6803</td>\n",
        "      <td>                      Gas-diesel oils in fisheries</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td>  213660.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>347680</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6800</td>\n",
        "      <td>                                          Gasoline</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td>  216053.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>347967</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6809</td>\n",
        "      <td>                                         Hard coal</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td>  561512.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>348254</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6805</td>\n",
        "      <td>                     Liquefied petroleum gas (LPG)</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td>  134066.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>348541</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6802</td>\n",
        "      <td>                       Natural gas (including LNG)</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td>  282638.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>348828</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6804</td>\n",
        "      <td>                                 Residual fuel oil</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td>  169532.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>349113</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6806</td>\n",
        "      <td>                    Residual fuel oil in fisheries</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td>   39336.7</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>349427</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6813</td>\n",
        "      <td>                            Total Energy + (Total)</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72182</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td> million kWh</td>\n",
        "      <td>  364449.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>349428</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6813</td>\n",
        "      <td>                            Total Energy + (Total)</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td> 6330930.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>349723</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6810</td>\n",
        "      <td> Transport fuel consumed in agriculture (excl. ...</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td> 3690460.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "  </tbody>\n",
        "</table>\n",
        "<p>16 rows \u00d7 11 columns</p>\n",
        "</div>"
       ],
       "metadata": {},
       "output_type": "pyout",
       "prompt_number": 314,
       "text": [
        "        CountryCode          Country  ItemCode  \\\n",
        "346386         5000  World + (Total)      6807   \n",
        "346387         5000  World + (Total)      6807   \n",
        "346682         5000  World + (Total)      6811   \n",
        "346986         5000  World + (Total)      6808   \n",
        "346987         5000  World + (Total)      6808   \n",
        "347113         5000  World + (Total)      6801   \n",
        "347398         5000  World + (Total)      6803   \n",
        "347680         5000  World + (Total)      6800   \n",
        "347967         5000  World + (Total)      6809   \n",
        "348254         5000  World + (Total)      6805   \n",
        "348541         5000  World + (Total)      6802   \n",
        "348828         5000  World + (Total)      6804   \n",
        "349113         5000  World + (Total)      6806   \n",
        "349427         5000  World + (Total)      6813   \n",
        "349428         5000  World + (Total)      6813   \n",
        "349723         5000  World + (Total)      6810   \n",
        "\n",
        "                                                     Item  ElementGroup  \\\n",
        "346386                                        Electricity          7218   \n",
        "346387                                        Electricity          7218   \n",
        "346682               Energy consumed in fishery + (Total)          7218   \n",
        "346986                        Energy for power irrigation          7218   \n",
        "346987                        Energy for power irrigation          7218   \n",
        "347113                                    Gas-diesel oils          7218   \n",
        "347398                       Gas-diesel oils in fisheries          7218   \n",
        "347680                                           Gasoline          7218   \n",
        "347967                                          Hard coal          7218   \n",
        "348254                      Liquefied petroleum gas (LPG)          7218   \n",
        "348541                        Natural gas (including LNG)          7218   \n",
        "348828                                  Residual fuel oil          7218   \n",
        "349113                     Residual fuel oil in fisheries          7218   \n",
        "349427                             Total Energy + (Total)          7218   \n",
        "349428                             Total Energy + (Total)          7218   \n",
        "349723  Transport fuel consumed in agriculture (excl. ...          7218   \n",
        "\n",
        "        ElementCode                     Element  Year         Unit      Value  \\\n",
        "346386        72184  Consumption in Agriculture  2002    Terajoule  1312020.0   \n",
        "346387        72182  Consumption in Agriculture  2002  million kWh   364449.0   \n",
        "346682        72184  Consumption in Agriculture  2002    Terajoule   383192.0   \n",
        "346986        72182  Consumption in Agriculture  2002  million kWh   236328.0   \n",
        "346987        72184  Consumption in Agriculture  2002    Terajoule   850780.0   \n",
        "347113        72184  Consumption in Agriculture  2002    Terajoule  3655110.0   \n",
        "347398        72184  Consumption in Agriculture  2002    Terajoule   213660.0   \n",
        "347680        72184  Consumption in Agriculture  2002    Terajoule   216053.0   \n",
        "347967        72184  Consumption in Agriculture  2002    Terajoule   561512.0   \n",
        "348254        72184  Consumption in Agriculture  2002    Terajoule   134066.0   \n",
        "348541        72184  Consumption in Agriculture  2002    Terajoule   282638.0   \n",
        "348828        72184  Consumption in Agriculture  2002    Terajoule   169532.0   \n",
        "349113        72184  Consumption in Agriculture  2002    Terajoule    39336.7   \n",
        "349427        72182  Consumption in Agriculture  2002  million kWh   364449.0   \n",
        "349428        72184  Consumption in Agriculture  2002    Terajoule  6330930.0   \n",
        "349723        72184  Consumption in Agriculture  2002    Terajoule  3690460.0   \n",
        "\n",
        "       Flag  \n",
        "346386    A  \n",
        "346387    A  \n",
        "346682    A  \n",
        "346986    A  \n",
        "346987    A  \n",
        "347113    A  \n",
        "347398    A  \n",
        "347680    A  \n",
        "347967    A  \n",
        "348254    A  \n",
        "348541    A  \n",
        "348828    A  \n",
        "349113    A  \n",
        "349427    A  \n",
        "349428    A  \n",
        "349723    A  \n",
        "\n",
        "[16 rows x 11 columns]"
       ]
      }
     ],
     "prompt_number": 314
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "'''                \n",
      "                            #add_to_json(energydata,2,fooditem,element,foodvalue,foodvalue,11,'[{\"l\":'+repr(fooditem)+',\"v\":'+repr(foodvalue)+'}]')\n",
      "                        if (element==\"Processing\"):\n",
      "                            processinggroup[2]+=energyvalue #save processing group\n",
      "                            processingprodgroup[2]+=foodvalue #save processing group\n",
      "                    \n",
      "                        for i in range(2): #sum fooitem values over different categories, defined above, currently 1-2\n",
      "                            if supergroup[i][fooditem] in energysum[i]:\n",
      "                                energysum[i][supergroup[i][fooditem]][\"data\"].append({\"l\":fooditem, \"v\":energyvalue})\n",
      "                                energysum[i][supergroup[i][fooditem]][\"sum\"]+=energyvalue\n",
      "                                prodsum[i][supergroup[i][fooditem]][\"data\"].append({\"l\":fooditem, \"v\":foodvalue})\n",
      "                                prodsum[i][supergroup[i][fooditem]][\"sum\"]+=foodvalue\n",
      "                            else:\n",
      "                                energysum[i][supergroup[i][fooditem]]={\"data\":[{\"l\":fooditem, \"v\":energyvalue}],\"sum\":energyvalue}\n",
      "                                prodsum[i][supergroup[i][fooditem]]={\"data\":[{\"l\":fooditem, \"v\":foodvalue}],\"sum\":foodvalue}\n",
      "                  \n",
      "            for i in range(2):\n",
      "                for j in energysum[i]:\n",
      "                    if (element==\"Seed\"):\n",
      "                        add_to_json(i,j,j,energysum[i][j][\"sum\"],prodsum[i][j][\"sum\"],energysum[i][j][\"sum\"]/(prodsum[i][j][\"sum\"]*(0.00116222222/100)),energysum[i][j][\"data\"]) #save categories, same manner for handling seed as above\n",
      "                    else:\n",
      "                        add_to_json(i,j,element,energysum[i][j][\"sum\"],prodsum[i][j][\"sum\"],energysum[i][j][\"sum\"]/(prodsum[i][j][\"sum\"]*(0.00116222222/100)),energysum[i][j][\"data\"])\n",
      "                    if (element==\"Processing\"):\n",
      "                        processinggroup[i]+=energysum[i][j][\"sum\"] #save processing group\n",
      "                        processingprodgroup[i]+=prodsum[i][j][\"sum\"] #save processing group\n",
      "                    if ((j=='Animal Products')\\\n",
      "                        |(j=='Aquatic Products')\\\n",
      "                        |(j=='Meat')\\\n",
      "                        |(j=='Animal Fats')\\\n",
      "                        |(j=='Fish, Seafood')\\\n",
      "                        |(j=='Aquatic Products, Other')\\\n",
      "                        |(j=='Offals')\\\n",
      "                        |(j=='Milk - Excluding Butter')\\\n",
      "                        |(j=='Eggs')):\n",
      "                            if j in feedgroup[i]:\n",
      "                                feedgroup[i][j]+=energysum[i][j][\"sum\"] #save feed group for the secondary food items\n",
      "                                feedprodgroup[i][j]+=prodsum[i][j][\"sum\"] #save feed group for the secondary food items\n",
      "                            else:\n",
      "                                feedgroup[i][j]=energysum[i][j][\"sum\"]\n",
      "                                feedprodgroup[i][j]=prodsum[i][j][\"sum\"]\n",
      "            \n",
      "        for i in range(3): #n\n",
      "            for j in feedgroup[i]:\n",
      "                add_to_json(i,\"Feed\",j,feedgroup[i][j],feedprodgroup[i][j],feedgroup[i][j]/(feedprodgroup[i][j]*(0.00116222222/100)),'[{\"l\":'+repr(\"Feed\")+',\"v\":'+repr(feedgroup[i][j])+'}]')\n",
      "        \n",
      "        for i in range(3): #n\n",
      "            add_to_json(i,\"Processing\",\"Food\",processinggroup[i],processingprodgroup[i],processinggroup[i]/(processingprodgroup[i]*(0.00116222222/100)),'[{\"l\":'+repr(\"Processing\")+',\"v\":'+repr(processinggroup[i])+'}]')\n",
      "'''"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "metadata": {},
       "output_type": "pyout",
       "prompt_number": 114,
       "text": [
        "'                \\n                            #add_to_json(energydata,2,fooditem,element,foodvalue,foodvalue,11,\\'[{\"l\":\\'+repr(fooditem)+\\',\"v\":\\'+repr(foodvalue)+\\'}]\\')\\n                        if (element==\"Processing\"):\\n                            processinggroup[2]+=energyvalue #save processing group\\n                            processingprodgroup[2]+=foodvalue #save processing group\\n                    \\n                        for i in range(2): #sum fooitem values over different categories, defined above, currently 1-2\\n                            if supergroup[i][fooditem] in energysum[i]:\\n                                energysum[i][supergroup[i][fooditem]][\"data\"].append({\"l\":fooditem, \"v\":energyvalue})\\n                                energysum[i][supergroup[i][fooditem]][\"sum\"]+=energyvalue\\n                                prodsum[i][supergroup[i][fooditem]][\"data\"].append({\"l\":fooditem, \"v\":foodvalue})\\n                                prodsum[i][supergroup[i][fooditem]][\"sum\"]+=foodvalue\\n                            else:\\n                                energysum[i][supergroup[i][fooditem]]={\"data\":[{\"l\":fooditem, \"v\":energyvalue}],\"sum\":energyvalue}\\n                                prodsum[i][supergroup[i][fooditem]]={\"data\":[{\"l\":fooditem, \"v\":foodvalue}],\"sum\":foodvalue}\\n                  \\n            for i in range(2):\\n                for j in energysum[i]:\\n                    if (element==\"Seed\"):\\n                        add_to_json(i,j,j,energysum[i][j][\"sum\"],prodsum[i][j][\"sum\"],energysum[i][j][\"sum\"]/(prodsum[i][j][\"sum\"]*(0.00116222222/100)),energysum[i][j][\"data\"]) #save categories, same manner for handling seed as above\\n                    else:\\n                        add_to_json(i,j,element,energysum[i][j][\"sum\"],prodsum[i][j][\"sum\"],energysum[i][j][\"sum\"]/(prodsum[i][j][\"sum\"]*(0.00116222222/100)),energysum[i][j][\"data\"])\\n                    if (element==\"Processing\"):\\n                        processinggroup[i]+=energysum[i][j][\"sum\"] #save processing group\\n                        processingprodgroup[i]+=prodsum[i][j][\"sum\"] #save processing group\\n                    if ((j==\\'Animal Products\\')                        |(j==\\'Aquatic Products\\')                        |(j==\\'Meat\\')                        |(j==\\'Animal Fats\\')                        |(j==\\'Fish, Seafood\\')                        |(j==\\'Aquatic Products, Other\\')                        |(j==\\'Offals\\')                        |(j==\\'Milk - Excluding Butter\\')                        |(j==\\'Eggs\\')):\\n                            if j in feedgroup[i]:\\n                                feedgroup[i][j]+=energysum[i][j][\"sum\"] #save feed group for the secondary food items\\n                                feedprodgroup[i][j]+=prodsum[i][j][\"sum\"] #save feed group for the secondary food items\\n                            else:\\n                                feedgroup[i][j]=energysum[i][j][\"sum\"]\\n                                feedprodgroup[i][j]=prodsum[i][j][\"sum\"]\\n            \\n        for i in range(3): #n\\n            for j in feedgroup[i]:\\n                add_to_json(i,\"Feed\",j,feedgroup[i][j],feedprodgroup[i][j],feedgroup[i][j]/(feedprodgroup[i][j]*(0.00116222222/100)),\\'[{\"l\":\\'+repr(\"Feed\")+\\',\"v\":\\'+repr(feedgroup[i][j])+\\'}]\\')\\n        \\n        for i in range(3): #n\\n            add_to_json(i,\"Processing\",\"Food\",processinggroup[i],processingprodgroup[i],processinggroup[i]/(processingprodgroup[i]*(0.00116222222/100)),\\'[{\"l\":\\'+repr(\"Processing\")+\\',\"v\":\\'+repr(processinggroup[i])+\\'}]\\')\\n'"
       ]
      }
     ],
     "prompt_number": 114
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "balance[(balance.Element==\"Food supply\")&(balance.Year==year)&(balance.Country==country)&(balance.Item.str.contains(\"Aquatic\"))]"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "html": [
        "<div style=\"max-height:1000px;max-width:1500px;overflow:auto;\">\n",
        "<table border=\"1\" class=\"dataframe\">\n",
        "  <thead>\n",
        "    <tr style=\"text-align: right;\">\n",
        "      <th></th>\n",
        "      <th>CountryCode</th>\n",
        "      <th>Country</th>\n",
        "      <th>ItemCode</th>\n",
        "      <th>Item</th>\n",
        "      <th>ElementGroup</th>\n",
        "      <th>ElementCode</th>\n",
        "      <th>Element</th>\n",
        "      <th>Year</th>\n",
        "      <th>Unit</th>\n",
        "      <th>Value</th>\n",
        "      <th>Flag</th>\n",
        "    </tr>\n",
        "  </thead>\n",
        "  <tbody>\n",
        "    <tr>\n",
        "      <th>4823822</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2769</td>\n",
        "      <td>           Aquatic Animals, Others</td>\n",
        "      <td> 664</td>\n",
        "      <td> 664</td>\n",
        "      <td> Food supply</td>\n",
        "      <td> 1971</td>\n",
        "      <td> kcal/capita/day</td>\n",
        "      <td> 0</td>\n",
        "      <td> Fc</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4824587</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2775</td>\n",
        "      <td>                    Aquatic Plants</td>\n",
        "      <td> 664</td>\n",
        "      <td> 664</td>\n",
        "      <td> Food supply</td>\n",
        "      <td> 1971</td>\n",
        "      <td> kcal/capita/day</td>\n",
        "      <td> 0</td>\n",
        "      <td> Fc</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4825352</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2961</td>\n",
        "      <td> Aquatic Products, Other + (Total)</td>\n",
        "      <td> 664</td>\n",
        "      <td> 664</td>\n",
        "      <td> Food supply</td>\n",
        "      <td> 1971</td>\n",
        "      <td> kcal/capita/day</td>\n",
        "      <td> 0</td>\n",
        "      <td> Fc</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4859757</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2768</td>\n",
        "      <td>             Meat, Aquatic Mammals</td>\n",
        "      <td> 664</td>\n",
        "      <td> 664</td>\n",
        "      <td> Food supply</td>\n",
        "      <td> 1971</td>\n",
        "      <td> kcal/capita/day</td>\n",
        "      <td> 0</td>\n",
        "      <td> Fc</td>\n",
        "    </tr>\n",
        "  </tbody>\n",
        "</table>\n",
        "<p>4 rows \u00d7 11 columns</p>\n",
        "</div>"
       ],
       "metadata": {},
       "output_type": "pyout",
       "prompt_number": 432,
       "text": [
        "         CountryCode          Country  ItemCode  \\\n",
        "4823822         5000  World + (Total)      2769   \n",
        "4824587         5000  World + (Total)      2775   \n",
        "4825352         5000  World + (Total)      2961   \n",
        "4859757         5000  World + (Total)      2768   \n",
        "\n",
        "                                      Item  ElementGroup  ElementCode  \\\n",
        "4823822            Aquatic Animals, Others           664          664   \n",
        "4824587                     Aquatic Plants           664          664   \n",
        "4825352  Aquatic Products, Other + (Total)           664          664   \n",
        "4859757              Meat, Aquatic Mammals           664          664   \n",
        "\n",
        "             Element  Year             Unit  Value Flag  \n",
        "4823822  Food supply  1971  kcal/capita/day      0   Fc  \n",
        "4824587  Food supply  1971  kcal/capita/day      0   Fc  \n",
        "4825352  Food supply  1971  kcal/capita/day      0   Fc  \n",
        "4859757  Food supply  1971  kcal/capita/day      0   Fc  \n",
        "\n",
        "[4 rows x 11 columns]"
       ]
      }
     ],
     "prompt_number": 432
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "myprod={}\n",
      "mybal={}\n",
      "elements=['Production','Area','Yield','Seed']\n",
      "#for country in set(data.Country.values):\n",
      "country='World + (Total)'    \n",
      "if True:\n",
      "    #for year in set(data[data.Country==country].Year.values):\n",
      "    year = 1962\n",
      "    if True:    \n",
      "         for element in elements:\n",
      "            for i in prod[(prod.Element==element)&(prod.Year==year)&(prod.Country==country)].values:\n",
      "                foodvalue=i[9] #choose column in which food item values are stored, might need to change it\n",
      "                if (~np.isnan(foodvalue)&(foodvalue!=0)):\n",
      "                    fooditem=i[3]  #choose column in which food item names are stored, might need to change it\n",
      "                    mydict[fooditem]=foodvalue\n",
      "            for i in balance[(balance.Element==element)&(balance.Year==year)&(balance.Country==country)&~(data.Item.str.contains('Total'))].values:\n",
      "                foodvalue=i[9] #choose column in which food item values are stored, might need to change it\n",
      "                if (~np.isnan(foodvalue)&(foodvalue!=0)):\n",
      "                    fooditem=i[3]  #choose column in which food item names are stored, might need to change it\n",
      "                    mybal[fooditem]=foodvalue\n",
      "                    \n",
      "for i in mybal:\n",
      "    if (i in mydict):\n",
      "        print (i,mydict[i]/1000,mybal[i])"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "output_type": "stream",
       "stream": "stdout",
       "text": [
        "('Plantains', 53.73276, 13002.0)\n",
        "('Cloves', 2.59975, 19.0)\n",
        "('Sorghum', 973.22829, 964.0)\n",
        "('Wheat', 26366.96166, 25990.0)\n",
        "('Dates', 75.90092999999999, 1329.0)\n",
        "('Oats', 4440.853139999999, 4441.0)\n",
        "('Maize', 6595.107690000001, 6544.0)\n",
        "('Barley', 8912.04352, 8762.0)\n",
        "('Tomatoes', 169.75989, 28954.0)\n",
        "('Grapes', 56.958589999999994, 53173.0)\n",
        "('Cottonseed', 1310.77741, 1299.0)\n",
        "('Pineapples', 108.14235000000001, 3671.0)\n",
        "('Tea', 7.155399999999999, 1272.0)\n",
        "('Olives', 20.19679, 5402.0)\n",
        "('Rye', 4642.103389999999, 4642.0)\n",
        "('Yams', 573.1385, 517.0)\n",
        "('Potatoes', 45216.9196, 45194.0)\n",
        "('Apples', 118.73937, 21657.0)\n",
        "('Bananas', 106.63515, 20557.0)\n",
        "('Millet', 888.98725, 885.0)\n",
        "('Cassava', 0.067, 65563.0)\n"
       ]
      }
     ],
     "prompt_number": 71
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "balance[(balance.Element==element)&(balance.Year==year)&(balance.Country==country)\\\n",
      "                          &(((2511<=balance.ItemCode)&(balance.ItemCode<=2775))\\\n",
      "                          |(balance.ItemCode==2805)\\\n",
      "                          |(balance.ItemCode==2912)\\\n",
      "                          |(balance.ItemCode==2945)\\\n",
      "                          |(balance.ItemCode==2948)\\\n",
      "                          |(balance.ItemCode==2949))]"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "html": [
        "<div style=\"max-height:1000px;max-width:1500px;overflow:auto;\">\n",
        "<table border=\"1\" class=\"dataframe\">\n",
        "  <thead>\n",
        "    <tr style=\"text-align: right;\">\n",
        "      <th></th>\n",
        "      <th>CountryCode</th>\n",
        "      <th>Country</th>\n",
        "      <th>ItemCode</th>\n",
        "      <th>Item</th>\n",
        "      <th>ElementGroup</th>\n",
        "      <th>ElementCode</th>\n",
        "      <th>Element</th>\n",
        "      <th>Year</th>\n",
        "      <th>Unit</th>\n",
        "      <th>Value</th>\n",
        "      <th>Flag</th>\n",
        "    </tr>\n",
        "  </thead>\n",
        "  <tbody>\n",
        "    <tr>\n",
        "      <th>4820140</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2659</td>\n",
        "      <td>                 Alcohol, Non-Food</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4822588</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2617</td>\n",
        "      <td>               Apples and products</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    117</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4823353</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2769</td>\n",
        "      <td>           Aquatic Animals, Others</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4824118</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2775</td>\n",
        "      <td>                    Aquatic Plants</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    129</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4825648</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2615</td>\n",
        "      <td>                           Bananas</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    409</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4826413</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2513</td>\n",
        "      <td>               Barley and products</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>  43786</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4827178</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2546</td>\n",
        "      <td>                             Beans</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    133</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4827943</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2656</td>\n",
        "      <td>                              Beer</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4828708</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2658</td>\n",
        "      <td>              Beverages, Alcoholic</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4829473</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2657</td>\n",
        "      <td>              Beverages, Fermented</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4830238</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2731</td>\n",
        "      <td>                       Bovine Meat</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4831003</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2740</td>\n",
        "      <td>                      Butter, Ghee</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      1</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4831768</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2532</td>\n",
        "      <td>              Cassava and products</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>  16302</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4832533</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2766</td>\n",
        "      <td>                       Cephalopods</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      6</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4834063</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2520</td>\n",
        "      <td>                    Cereals, Other</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>   5457</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4834828</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2614</td>\n",
        "      <td>                     Citrus, Other</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4835593</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2642</td>\n",
        "      <td>                            Cloves</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4836358</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2633</td>\n",
        "      <td>          Cocoa Beans and products</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4837123</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2578</td>\n",
        "      <td>                       Coconut Oil</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4837888</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2560</td>\n",
        "      <td>             Coconuts - Incl Copra</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>     15</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4838653</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2630</td>\n",
        "      <td>               Coffee and products</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4839418</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2559</td>\n",
        "      <td>                        Cottonseed</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>   1609</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4840183</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2575</td>\n",
        "      <td>                    Cottonseed Oil</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4840948</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2743</td>\n",
        "      <td>                             Cream</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4841713</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2765</td>\n",
        "      <td>                       Crustaceans</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>     24</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4842478</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2619</td>\n",
        "      <td>                             Dates</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>     24</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4843243</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2762</td>\n",
        "      <td>                     Demersal Fish</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    788</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4844008</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2744</td>\n",
        "      <td>                              Eggs</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      4</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4844773</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2949</td>\n",
        "      <td>                    Eggs + (Total)</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      4</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4845538</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2737</td>\n",
        "      <td>                Fats, Animals, Raw</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    338</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4848598</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2761</td>\n",
        "      <td>                   Freshwater Fish</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>     10</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4850128</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2625</td>\n",
        "      <td>                     Fruits, Other</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>     66</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4851046</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2613</td>\n",
        "      <td>           Grapefruit and products</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4851811</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2620</td>\n",
        "      <td>   Grapes and products (excl wine)</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4852576</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2572</td>\n",
        "      <td>                     Groundnut Oil</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4853341</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2556</td>\n",
        "      <td>           Groundnuts (Shelled Eq)</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>     10</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4854106</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2745</td>\n",
        "      <td>                             Honey</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4855463</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2612</td>\n",
        "      <td>        Lemons, Limes and products</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4856228</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2514</td>\n",
        "      <td>                Maize and products</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td> 147255</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4856993</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2582</td>\n",
        "      <td>                    Maize Germ Oil</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4857758</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2764</td>\n",
        "      <td>                Marine Fish, Other</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    139</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4859288</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2768</td>\n",
        "      <td>             Meat, Aquatic Mammals</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4860053</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2735</td>\n",
        "      <td>                       Meat, Other</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>     36</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4861532</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2948</td>\n",
        "      <td> Milk - Excluding Butter + (Total)</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>  92128</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4862297</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2517</td>\n",
        "      <td>               Millet and products</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>   1678</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4863368</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2767</td>\n",
        "      <td>                   Molluscs, Other</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>     57</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4864133</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2732</td>\n",
        "      <td>                Mutton &amp; Goat Meat</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4865612</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2516</td>\n",
        "      <td>                              Oats</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>  38763</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4866377</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2945</td>\n",
        "      <td>                  Offals + (Total)</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    558</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4867142</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2736</td>\n",
        "      <td>                    Offals, Edible</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    558</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4868621</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2586</td>\n",
        "      <td>               Oilcrops Oil, Other</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4869386</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2570</td>\n",
        "      <td>                   Oilcrops, Other</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>     85</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4870151</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2580</td>\n",
        "      <td>                         Olive Oil</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4870916</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2563</td>\n",
        "      <td>      Olives (including preserved)</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4871681</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2602</td>\n",
        "      <td>                            Onions</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4872446</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2611</td>\n",
        "      <td>               Oranges, Mandarines</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4873211</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2562</td>\n",
        "      <td>                      Palm kernels</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4873976</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2577</td>\n",
        "      <td>                          Palm Oil</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4874741</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2576</td>\n",
        "      <td>                    Palmkernel Oil</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      3</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4875506</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2547</td>\n",
        "      <td>                              Peas</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>   1002</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th></th>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "    </tr>\n",
        "  </tbody>\n",
        "</table>\n",
        "<p>96 rows \u00d7 11 columns</p>\n",
        "</div>"
       ],
       "metadata": {},
       "output_type": "pyout",
       "prompt_number": 163,
       "text": [
        "         CountryCode          Country  ItemCode  \\\n",
        "4820140         5000  World + (Total)      2659   \n",
        "4822588         5000  World + (Total)      2617   \n",
        "4823353         5000  World + (Total)      2769   \n",
        "4824118         5000  World + (Total)      2775   \n",
        "4825648         5000  World + (Total)      2615   \n",
        "4826413         5000  World + (Total)      2513   \n",
        "4827178         5000  World + (Total)      2546   \n",
        "4827943         5000  World + (Total)      2656   \n",
        "4828708         5000  World + (Total)      2658   \n",
        "4829473         5000  World + (Total)      2657   \n",
        "4830238         5000  World + (Total)      2731   \n",
        "4831003         5000  World + (Total)      2740   \n",
        "4831768         5000  World + (Total)      2532   \n",
        "4832533         5000  World + (Total)      2766   \n",
        "4834063         5000  World + (Total)      2520   \n",
        "4834828         5000  World + (Total)      2614   \n",
        "4835593         5000  World + (Total)      2642   \n",
        "4836358         5000  World + (Total)      2633   \n",
        "4837123         5000  World + (Total)      2578   \n",
        "4837888         5000  World + (Total)      2560   \n",
        "4838653         5000  World + (Total)      2630   \n",
        "4839418         5000  World + (Total)      2559   \n",
        "4840183         5000  World + (Total)      2575   \n",
        "4840948         5000  World + (Total)      2743   \n",
        "4841713         5000  World + (Total)      2765   \n",
        "4842478         5000  World + (Total)      2619   \n",
        "4843243         5000  World + (Total)      2762   \n",
        "4844008         5000  World + (Total)      2744   \n",
        "4844773         5000  World + (Total)      2949   \n",
        "4845538         5000  World + (Total)      2737   \n",
        "4848598         5000  World + (Total)      2761   \n",
        "4850128         5000  World + (Total)      2625   \n",
        "4851046         5000  World + (Total)      2613   \n",
        "4851811         5000  World + (Total)      2620   \n",
        "4852576         5000  World + (Total)      2572   \n",
        "4853341         5000  World + (Total)      2556   \n",
        "4854106         5000  World + (Total)      2745   \n",
        "4855463         5000  World + (Total)      2612   \n",
        "4856228         5000  World + (Total)      2514   \n",
        "4856993         5000  World + (Total)      2582   \n",
        "4857758         5000  World + (Total)      2764   \n",
        "4859288         5000  World + (Total)      2768   \n",
        "4860053         5000  World + (Total)      2735   \n",
        "4861532         5000  World + (Total)      2948   \n",
        "4862297         5000  World + (Total)      2517   \n",
        "4863368         5000  World + (Total)      2767   \n",
        "4864133         5000  World + (Total)      2732   \n",
        "4865612         5000  World + (Total)      2516   \n",
        "4866377         5000  World + (Total)      2945   \n",
        "4867142         5000  World + (Total)      2736   \n",
        "4868621         5000  World + (Total)      2586   \n",
        "4869386         5000  World + (Total)      2570   \n",
        "4870151         5000  World + (Total)      2580   \n",
        "4870916         5000  World + (Total)      2563   \n",
        "4871681         5000  World + (Total)      2602   \n",
        "4872446         5000  World + (Total)      2611   \n",
        "4873211         5000  World + (Total)      2562   \n",
        "4873976         5000  World + (Total)      2577   \n",
        "4874741         5000  World + (Total)      2576   \n",
        "4875506         5000  World + (Total)      2547   \n",
        "                 ...              ...       ...   \n",
        "\n",
        "                                      Item  ElementGroup  ElementCode Element  \\\n",
        "4820140                  Alcohol, Non-Food           101         5521    Feed   \n",
        "4822588                Apples and products           101         5521    Feed   \n",
        "4823353            Aquatic Animals, Others           101         5521    Feed   \n",
        "4824118                     Aquatic Plants           101         5521    Feed   \n",
        "4825648                            Bananas           101         5521    Feed   \n",
        "4826413                Barley and products           101         5521    Feed   \n",
        "4827178                              Beans           101         5521    Feed   \n",
        "4827943                               Beer           101         5521    Feed   \n",
        "4828708               Beverages, Alcoholic           101         5521    Feed   \n",
        "4829473               Beverages, Fermented           101         5521    Feed   \n",
        "4830238                        Bovine Meat           101         5521    Feed   \n",
        "4831003                       Butter, Ghee           101         5521    Feed   \n",
        "4831768               Cassava and products           101         5521    Feed   \n",
        "4832533                        Cephalopods           101         5521    Feed   \n",
        "4834063                     Cereals, Other           101         5521    Feed   \n",
        "4834828                      Citrus, Other           101         5521    Feed   \n",
        "4835593                             Cloves           101         5521    Feed   \n",
        "4836358           Cocoa Beans and products           101         5521    Feed   \n",
        "4837123                        Coconut Oil           101         5521    Feed   \n",
        "4837888              Coconuts - Incl Copra           101         5521    Feed   \n",
        "4838653                Coffee and products           101         5521    Feed   \n",
        "4839418                         Cottonseed           101         5521    Feed   \n",
        "4840183                     Cottonseed Oil           101         5521    Feed   \n",
        "4840948                              Cream           101         5521    Feed   \n",
        "4841713                        Crustaceans           101         5521    Feed   \n",
        "4842478                              Dates           101         5521    Feed   \n",
        "4843243                      Demersal Fish           101         5521    Feed   \n",
        "4844008                               Eggs           101         5521    Feed   \n",
        "4844773                     Eggs + (Total)           101         5521    Feed   \n",
        "4845538                 Fats, Animals, Raw           101         5521    Feed   \n",
        "4848598                    Freshwater Fish           101         5521    Feed   \n",
        "4850128                      Fruits, Other           101         5521    Feed   \n",
        "4851046            Grapefruit and products           101         5521    Feed   \n",
        "4851811    Grapes and products (excl wine)           101         5521    Feed   \n",
        "4852576                      Groundnut Oil           101         5521    Feed   \n",
        "4853341            Groundnuts (Shelled Eq)           101         5521    Feed   \n",
        "4854106                              Honey           101         5521    Feed   \n",
        "4855463         Lemons, Limes and products           101         5521    Feed   \n",
        "4856228                 Maize and products           101         5521    Feed   \n",
        "4856993                     Maize Germ Oil           101         5521    Feed   \n",
        "4857758                 Marine Fish, Other           101         5521    Feed   \n",
        "4859288              Meat, Aquatic Mammals           101         5521    Feed   \n",
        "4860053                        Meat, Other           101         5521    Feed   \n",
        "4861532  Milk - Excluding Butter + (Total)           101         5521    Feed   \n",
        "4862297                Millet and products           101         5521    Feed   \n",
        "4863368                    Molluscs, Other           101         5521    Feed   \n",
        "4864133                 Mutton & Goat Meat           101         5521    Feed   \n",
        "4865612                               Oats           101         5521    Feed   \n",
        "4866377                   Offals + (Total)           101         5521    Feed   \n",
        "4867142                     Offals, Edible           101         5521    Feed   \n",
        "4868621                Oilcrops Oil, Other           101         5521    Feed   \n",
        "4869386                    Oilcrops, Other           101         5521    Feed   \n",
        "4870151                          Olive Oil           101         5521    Feed   \n",
        "4870916       Olives (including preserved)           101         5521    Feed   \n",
        "4871681                             Onions           101         5521    Feed   \n",
        "4872446                Oranges, Mandarines           101         5521    Feed   \n",
        "4873211                       Palm kernels           101         5521    Feed   \n",
        "4873976                           Palm Oil           101         5521    Feed   \n",
        "4874741                     Palmkernel Oil           101         5521    Feed   \n",
        "4875506                               Peas           101         5521    Feed   \n",
        "                                       ...           ...          ...     ...   \n",
        "\n",
        "         Year         Unit   Value Flag  \n",
        "4820140  1961  1000 tonnes     NaN  NaN  \n",
        "4822588  1961  1000 tonnes     117    A  \n",
        "4823353  1961  1000 tonnes     NaN  NaN  \n",
        "4824118  1961  1000 tonnes     129    A  \n",
        "4825648  1961  1000 tonnes     409    A  \n",
        "4826413  1961  1000 tonnes   43786    A  \n",
        "4827178  1961  1000 tonnes     133    A  \n",
        "4827943  1961  1000 tonnes     NaN  NaN  \n",
        "4828708  1961  1000 tonnes     NaN  NaN  \n",
        "4829473  1961  1000 tonnes     NaN  NaN  \n",
        "4830238  1961  1000 tonnes     NaN  NaN  \n",
        "4831003  1961  1000 tonnes       1    A  \n",
        "4831768  1961  1000 tonnes   16302    A  \n",
        "4832533  1961  1000 tonnes       6    A  \n",
        "4834063  1961  1000 tonnes    5457    A  \n",
        "4834828  1961  1000 tonnes     NaN  NaN  \n",
        "4835593  1961  1000 tonnes     NaN  NaN  \n",
        "4836358  1961  1000 tonnes     NaN  NaN  \n",
        "4837123  1961  1000 tonnes       0    A  \n",
        "4837888  1961  1000 tonnes      15    A  \n",
        "4838653  1961  1000 tonnes     NaN  NaN  \n",
        "4839418  1961  1000 tonnes    1609    A  \n",
        "4840183  1961  1000 tonnes       0    A  \n",
        "4840948  1961  1000 tonnes     NaN  NaN  \n",
        "4841713  1961  1000 tonnes      24    A  \n",
        "4842478  1961  1000 tonnes      24    A  \n",
        "4843243  1961  1000 tonnes     788    A  \n",
        "4844008  1961  1000 tonnes       4    A  \n",
        "4844773  1961  1000 tonnes       4    A  \n",
        "4845538  1961  1000 tonnes     338    A  \n",
        "4848598  1961  1000 tonnes      10    A  \n",
        "4850128  1961  1000 tonnes      66    A  \n",
        "4851046  1961  1000 tonnes       0    A  \n",
        "4851811  1961  1000 tonnes       0    A  \n",
        "4852576  1961  1000 tonnes       0    A  \n",
        "4853341  1961  1000 tonnes      10    A  \n",
        "4854106  1961  1000 tonnes       0    A  \n",
        "4855463  1961  1000 tonnes     NaN  NaN  \n",
        "4856228  1961  1000 tonnes  147255    A  \n",
        "4856993  1961  1000 tonnes     NaN  NaN  \n",
        "4857758  1961  1000 tonnes     139    A  \n",
        "4859288  1961  1000 tonnes     NaN  NaN  \n",
        "4860053  1961  1000 tonnes      36    A  \n",
        "4861532  1961  1000 tonnes   92128    A  \n",
        "4862297  1961  1000 tonnes    1678    A  \n",
        "4863368  1961  1000 tonnes      57    A  \n",
        "4864133  1961  1000 tonnes       0    A  \n",
        "4865612  1961  1000 tonnes   38763    A  \n",
        "4866377  1961  1000 tonnes     558    A  \n",
        "4867142  1961  1000 tonnes     558    A  \n",
        "4868621  1961  1000 tonnes       0    A  \n",
        "4869386  1961  1000 tonnes      85    A  \n",
        "4870151  1961  1000 tonnes       0    A  \n",
        "4870916  1961  1000 tonnes     NaN  NaN  \n",
        "4871681  1961  1000 tonnes       0    A  \n",
        "4872446  1961  1000 tonnes       0    A  \n",
        "4873211  1961  1000 tonnes       0    A  \n",
        "4873976  1961  1000 tonnes       0    A  \n",
        "4874741  1961  1000 tonnes       3    A  \n",
        "4875506  1961  1000 tonnes    1002    A  \n",
        "          ...          ...     ...  ...  \n",
        "\n",
        "[96 rows x 11 columns]"
       ]
      }
     ],
     "prompt_number": 163
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "a='Feed'\n",
      "b=0\n",
      "~np.isnan(a)"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "ename": "TypeError",
       "evalue": "Not implemented for this type",
       "output_type": "pyerr",
       "traceback": [
        "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m\n\u001b[1;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
        "\u001b[1;32m<ipython-input-29-11cf204d31e8>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m()\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[0ma\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m'Feed'\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[0mb\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 3\u001b[1;33m \u001b[1;33m~\u001b[0m\u001b[0mnp\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0misnan\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0ma\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
        "\u001b[1;31mTypeError\u001b[0m: Not implemented for this type"
       ]
      }
     ],
     "prompt_number": 29
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "data[(data.Element=='Food supply quantity')&(data.Year==1961)&(data.Country=='World + (Total)')&(data.Unit==\"g\"\"/capita\"\"/day\")&~(data.Item.str.contains('Total'))].head()"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "html": [
        "<div style=\"max-height:1000px;max-width:1500px;overflow:auto;\">\n",
        "<table border=\"1\" class=\"dataframe\">\n",
        "  <thead>\n",
        "    <tr style=\"text-align: right;\">\n",
        "      <th></th>\n",
        "      <th>CountryCode</th>\n",
        "      <th>Country</th>\n",
        "      <th>ItemCode</th>\n",
        "      <th>Item</th>\n",
        "      <th>ElementGroup</th>\n",
        "      <th>ElementCode</th>\n",
        "      <th>Element</th>\n",
        "      <th>Year</th>\n",
        "      <th>Unit</th>\n",
        "      <th>Value</th>\n",
        "      <th>Flag</th>\n",
        "    </tr>\n",
        "  </thead>\n",
        "  <tbody>\n",
        "    <tr>\n",
        "      <th>1077829</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2769</td>\n",
        "      <td> Aquatic Animals, Others</td>\n",
        "      <td> 646</td>\n",
        "      <td> 646</td>\n",
        "      <td> Food supply quantity</td>\n",
        "      <td> 1961</td>\n",
        "      <td> g/capita/day</td>\n",
        "      <td>  0</td>\n",
        "      <td> Fc</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>1078123</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2775</td>\n",
        "      <td>          Aquatic Plants</td>\n",
        "      <td> 646</td>\n",
        "      <td> 646</td>\n",
        "      <td> Food supply quantity</td>\n",
        "      <td> 1961</td>\n",
        "      <td> g/capita/day</td>\n",
        "      <td>  0</td>\n",
        "      <td> Fc</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>1078711</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2731</td>\n",
        "      <td>             Bovine Meat</td>\n",
        "      <td> 646</td>\n",
        "      <td> 646</td>\n",
        "      <td> Food supply quantity</td>\n",
        "      <td> 1961</td>\n",
        "      <td> g/capita/day</td>\n",
        "      <td> 26</td>\n",
        "      <td> Fc</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>1079005</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2740</td>\n",
        "      <td>            Butter, Ghee</td>\n",
        "      <td> 646</td>\n",
        "      <td> 646</td>\n",
        "      <td> Food supply quantity</td>\n",
        "      <td> 1961</td>\n",
        "      <td> g/capita/day</td>\n",
        "      <td>  5</td>\n",
        "      <td> Fc</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>1079299</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2766</td>\n",
        "      <td>             Cephalopods</td>\n",
        "      <td> 646</td>\n",
        "      <td> 646</td>\n",
        "      <td> Food supply quantity</td>\n",
        "      <td> 1961</td>\n",
        "      <td> g/capita/day</td>\n",
        "      <td>  1</td>\n",
        "      <td> Fc</td>\n",
        "    </tr>\n",
        "  </tbody>\n",
        "</table>\n",
        "<p>5 rows \u00d7 11 columns</p>\n",
        "</div>"
       ],
       "metadata": {},
       "output_type": "pyout",
       "prompt_number": 105,
       "text": [
        "         CountryCode          Country  ItemCode                     Item  \\\n",
        "1077829         5000  World + (Total)      2769  Aquatic Animals, Others   \n",
        "1078123         5000  World + (Total)      2775           Aquatic Plants   \n",
        "1078711         5000  World + (Total)      2731              Bovine Meat   \n",
        "1079005         5000  World + (Total)      2740             Butter, Ghee   \n",
        "1079299         5000  World + (Total)      2766              Cephalopods   \n",
        "\n",
        "         ElementGroup  ElementCode               Element  Year          Unit  \\\n",
        "1077829           646          646  Food supply quantity  1961  g/capita/day   \n",
        "1078123           646          646  Food supply quantity  1961  g/capita/day   \n",
        "1078711           646          646  Food supply quantity  1961  g/capita/day   \n",
        "1079005           646          646  Food supply quantity  1961  g/capita/day   \n",
        "1079299           646          646  Food supply quantity  1961  g/capita/day   \n",
        "\n",
        "         Value Flag  \n",
        "1077829      0   Fc  \n",
        "1078123      0   Fc  \n",
        "1078711     26   Fc  \n",
        "1079005      5   Fc  \n",
        "1079299      1   Fc  \n",
        "\n",
        "[5 rows x 11 columns]"
       ]
      }
     ],
     "prompt_number": 105
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "balance[(balance.Element==element)&(balance.Year==year)&(balance.Country==country)&(balance.Item.str.contains(\"Offals\"))]\n",
      "#energyvalue=foodvalue*cal*0.00116222222/100\n",
      "                        #TWh = 1000tons * kcal/100g # 10^9) /100g * 0.00116222222 kwh/kcal *10^-9 TWh/kWh\n",
      "                "
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "html": [
        "<div style=\"max-height:1000px;max-width:1500px;overflow:auto;\">\n",
        "<table border=\"1\" class=\"dataframe\">\n",
        "  <thead>\n",
        "    <tr style=\"text-align: right;\">\n",
        "      <th></th>\n",
        "      <th>CountryCode</th>\n",
        "      <th>Country</th>\n",
        "      <th>ItemCode</th>\n",
        "      <th>Item</th>\n",
        "      <th>ElementGroup</th>\n",
        "      <th>ElementCode</th>\n",
        "      <th>Element</th>\n",
        "      <th>Year</th>\n",
        "      <th>Unit</th>\n",
        "      <th>Value</th>\n",
        "      <th>Flag</th>\n",
        "    </tr>\n",
        "  </thead>\n",
        "  <tbody>\n",
        "    <tr>\n",
        "      <th>4866489</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2945</td>\n",
        "      <td> Offals + (Total)</td>\n",
        "      <td> 121</td>\n",
        "      <td> 5123</td>\n",
        "      <td> Waste</td>\n",
        "      <td> 1971</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td> 79</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4867203</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2736</td>\n",
        "      <td>   Offals, Edible</td>\n",
        "      <td> 121</td>\n",
        "      <td> 5123</td>\n",
        "      <td> Waste</td>\n",
        "      <td> 1971</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td> 79</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "  </tbody>\n",
        "</table>\n",
        "<p>2 rows \u00d7 11 columns</p>\n",
        "</div>"
       ],
       "metadata": {},
       "output_type": "pyout",
       "prompt_number": 425,
       "text": [
        "         CountryCode          Country  ItemCode              Item  \\\n",
        "4866489         5000  World + (Total)      2945  Offals + (Total)   \n",
        "4867203         5000  World + (Total)      2736    Offals, Edible   \n",
        "\n",
        "         ElementGroup  ElementCode Element  Year         Unit  Value Flag  \n",
        "4866489           121         5123   Waste  1971  1000 tonnes     79    A  \n",
        "4867203           121         5123   Waste  1971  1000 tonnes     79    A  \n",
        "\n",
        "[2 rows x 11 columns]"
       ]
      }
     ],
     "prompt_number": 425
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "supply1 = get_data(7)\n",
      "supply2 = get_data(8)"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [],
     "prompt_number": 87
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "from IPython.display import HTML\n",
      "HTML('<iframe src=http://127.0.0.1:8898/ width=1080 height=670></iframe>') \n",
      "#HTML('<iframe src=http://food.csaladen.es width=1080 height=600></iframe>') "
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "html": [
        "<iframe src=http://127.0.0.1:8898/ width=1080 height=670></iframe>"
       ],
       "metadata": {},
       "output_type": "pyout",
       "prompt_number": 45,
       "text": [
        "<IPython.core.display.HTML at 0x4f39c3c8>"
       ]
      }
     ],
     "prompt_number": 45
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "r = requests.get('http://www.fao.org/fileadmin/templates/ess/ess_test_folder/Food_security/Excel_sheets/Nutritive_Factors.xls')\n",
      "#xl = pd.ExcelFile(r.content)\n",
      "#xl\n",
      "#ind =10\n",
      "#if localpath:\n",
      "#    r = masterpath+indicators[ind]+'.zip'\n",
      "#    z = zipfile.ZipFile(r)\n",
      "#else:\n",
      "#    r = requests.get(masterpath+indicators[ind]+'.zip')\n",
      "#    z = zipfile.ZipFile(StringIO.StringIO(r.content))\n",
      "#data = pd.read_csv(z.open(indicators[ind]+'.csv'))\n",
      "#data.head()\n",
      "r.content\n",
      "nutri = pd.read_excel(masterpath+'Nutritive_Factors.xls','Sheet1')\n",
      "nutri"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "html": [
        "<div style=\"max-height:1000px;max-width:1500px;overflow:auto;\">\n",
        "<table border=\"1\" class=\"dataframe\">\n",
        "  <thead>\n",
        "    <tr style=\"text-align: right;\">\n",
        "      <th></th>\n",
        "      <th>Nutritive factors</th>\n",
        "      <th>Unnamed: 1</th>\n",
        "      <th>Unnamed: 2</th>\n",
        "      <th>Unnamed: 3</th>\n",
        "    </tr>\n",
        "  </thead>\n",
        "  <tbody>\n",
        "    <tr>\n",
        "      <th>0 </th>\n",
        "      <td> FOOD AND AGRICULTURE ORGANIZATION OF THE UNITE...</td>\n",
        "      <td>               NaN</td>\n",
        "      <td>             NaN</td>\n",
        "      <td>             NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>1 </th>\n",
        "      <td>                                         COMMODITY</td>\n",
        "      <td>          calories</td>\n",
        "      <td>         protein</td>\n",
        "      <td>             fat</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>2 </th>\n",
        "      <td>                                               NaN</td>\n",
        "      <td> (per 100 grammes)</td>\n",
        "      <td> (mg per gramme)</td>\n",
        "      <td> (mg per gramme)</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>3 </th>\n",
        "      <td>                                      ALFALFA MEAL</td>\n",
        "      <td>               265</td>\n",
        "      <td>             305</td>\n",
        "      <td>              20</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4 </th>\n",
        "      <td>                                          ALMONDS </td>\n",
        "      <td>               236</td>\n",
        "      <td>              80</td>\n",
        "      <td>             209</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>5 </th>\n",
        "      <td>                                  ALMONDS SHELLED </td>\n",
        "      <td>               589</td>\n",
        "      <td>             200</td>\n",
        "      <td>             522</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>6 </th>\n",
        "      <td>                                            ANISE </td>\n",
        "      <td>               345</td>\n",
        "      <td>             158</td>\n",
        "      <td>             149</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>7 </th>\n",
        "      <td>                         APPLE JUICE CONCENTRATED </td>\n",
        "      <td>               166</td>\n",
        "      <td>               5</td>\n",
        "      <td>               4</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>8 </th>\n",
        "      <td>                      APPLE JUICE SINGLE STRENGTH </td>\n",
        "      <td>                47</td>\n",
        "      <td>               1</td>\n",
        "      <td>               1</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>9 </th>\n",
        "      <td>                                           APPLES </td>\n",
        "      <td>                48</td>\n",
        "      <td>               1</td>\n",
        "      <td>               3</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>10</th>\n",
        "      <td>                                         APRICOTS </td>\n",
        "      <td>                45</td>\n",
        "      <td>              13</td>\n",
        "      <td>               4</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>11</th>\n",
        "      <td>                                       ARECA NUTS </td>\n",
        "      <td>               245</td>\n",
        "      <td>              49</td>\n",
        "      <td>              44</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>12</th>\n",
        "      <td>                                       ARTICHOKES </td>\n",
        "      <td>                20</td>\n",
        "      <td>              11</td>\n",
        "      <td>               1</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>13</th>\n",
        "      <td>                                        ASPARAGUS </td>\n",
        "      <td>                12</td>\n",
        "      <td>              16</td>\n",
        "      <td>               1</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>14</th>\n",
        "      <td>                                         AVOCADOS </td>\n",
        "      <td>               119</td>\n",
        "      <td>              15</td>\n",
        "      <td>             113</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>15</th>\n",
        "      <td>                                       BACON PIGS </td>\n",
        "      <td>               362</td>\n",
        "      <td>             131</td>\n",
        "      <td>             341</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>16</th>\n",
        "      <td>                                      BAMBARA BEAN</td>\n",
        "      <td>               365</td>\n",
        "      <td>             177</td>\n",
        "      <td>              63</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>17</th>\n",
        "      <td>                                          BANANAS </td>\n",
        "      <td>                60</td>\n",
        "      <td>               7</td>\n",
        "      <td>               3</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>18</th>\n",
        "      <td>                                           BARLEY </td>\n",
        "      <td>               332</td>\n",
        "      <td>             120</td>\n",
        "      <td>              18</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>19</th>\n",
        "      <td>                            BARLEY FLOUR AND GRITS</td>\n",
        "      <td>               343</td>\n",
        "      <td>              92</td>\n",
        "      <td>              17</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>20</th>\n",
        "      <td>                                      BARLEY PEARL</td>\n",
        "      <td>               346</td>\n",
        "      <td>              90</td>\n",
        "      <td>              14</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>21</th>\n",
        "      <td>                                         BEANS DRY</td>\n",
        "      <td>               341</td>\n",
        "      <td>             221</td>\n",
        "      <td>              17</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>22</th>\n",
        "      <td>                                       BEANS GREEN</td>\n",
        "      <td>                50</td>\n",
        "      <td>              30</td>\n",
        "      <td>               4</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>23</th>\n",
        "      <td>                                      BEEF BONLESS</td>\n",
        "      <td>               150</td>\n",
        "      <td>             185</td>\n",
        "      <td>              79</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>24</th>\n",
        "      <td>                                      BEEF CANNED </td>\n",
        "      <td>               233</td>\n",
        "      <td>             250</td>\n",
        "      <td>             140</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>25</th>\n",
        "      <td>                         BEEF DRIED, SALT, SMOKED </td>\n",
        "      <td>               203</td>\n",
        "      <td>             343</td>\n",
        "      <td>              63</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>26</th>\n",
        "      <td>                                BEEF PREPARATIONS </td>\n",
        "      <td>               233</td>\n",
        "      <td>             250</td>\n",
        "      <td>             140</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>27</th>\n",
        "      <td>                                        BEEF VEAL </td>\n",
        "      <td>               225</td>\n",
        "      <td>             147</td>\n",
        "      <td>             180</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>28</th>\n",
        "      <td>                                      BEER BARLEY </td>\n",
        "      <td>                49</td>\n",
        "      <td>               5</td>\n",
        "      <td>               0</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>29</th>\n",
        "      <td>                                       BEER MAIZE </td>\n",
        "      <td>                40</td>\n",
        "      <td>               4</td>\n",
        "      <td>               0</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>30</th>\n",
        "      <td>                                      BEER MILLET </td>\n",
        "      <td>                40</td>\n",
        "      <td>               4</td>\n",
        "      <td>               0</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>31</th>\n",
        "      <td>                                      BEER SORGHUM</td>\n",
        "      <td>                40</td>\n",
        "      <td>               4</td>\n",
        "      <td>               0</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>32</th>\n",
        "      <td>                                    BEET PULP DRY </td>\n",
        "      <td>               288</td>\n",
        "      <td>             111</td>\n",
        "      <td>               6</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>33</th>\n",
        "      <td>                                      BERRIES NES </td>\n",
        "      <td>                49</td>\n",
        "      <td>              10</td>\n",
        "      <td>               7</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>34</th>\n",
        "      <td>                   BEVERAGES DISTILLED. ALCOHOLIC </td>\n",
        "      <td>               295</td>\n",
        "      <td>               0</td>\n",
        "      <td>               0</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>35</th>\n",
        "      <td>                           BEVERAGES NON ALCOHOLIC</td>\n",
        "      <td>                39</td>\n",
        "      <td>               0</td>\n",
        "      <td>               0</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>36</th>\n",
        "      <td>                                      BLUEBERRIES </td>\n",
        "      <td>               120</td>\n",
        "      <td>               7</td>\n",
        "      <td>               4</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>37</th>\n",
        "      <td>                                        BRAN RICE </td>\n",
        "      <td>               276</td>\n",
        "      <td>             133</td>\n",
        "      <td>             158</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>38</th>\n",
        "      <td>                                       BRAN WHEAT </td>\n",
        "      <td>               213</td>\n",
        "      <td>             121</td>\n",
        "      <td>              31</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>39</th>\n",
        "      <td>                                      BRAZIL NUTS </td>\n",
        "      <td>               315</td>\n",
        "      <td>              69</td>\n",
        "      <td>             318</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>40</th>\n",
        "      <td>                                 BRAZILNUT SHELLED</td>\n",
        "      <td>               656</td>\n",
        "      <td>             143</td>\n",
        "      <td>             662</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>41</th>\n",
        "      <td>                               BROAD BEANS GROUND </td>\n",
        "      <td>                23</td>\n",
        "      <td>              23</td>\n",
        "      <td>               1</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>42</th>\n",
        "      <td>                                   BROAD BEANS DRY</td>\n",
        "      <td>               343</td>\n",
        "      <td>             234</td>\n",
        "      <td>              20</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>43</th>\n",
        "      <td>                                            BREAD </td>\n",
        "      <td>               249</td>\n",
        "      <td>              82</td>\n",
        "      <td>              12</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>44</th>\n",
        "      <td>                               BREAKFEAST CERLEALS</td>\n",
        "      <td>               389</td>\n",
        "      <td>              74</td>\n",
        "      <td>               7</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>45</th>\n",
        "      <td>                                        BUCKWHEAT </td>\n",
        "      <td>               330</td>\n",
        "      <td>             120</td>\n",
        "      <td>              20</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>46</th>\n",
        "      <td>                                      BUFFALO MEAT</td>\n",
        "      <td>                77</td>\n",
        "      <td>             113</td>\n",
        "      <td>              31</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>47</th>\n",
        "      <td>                                      BUFFALO MILK</td>\n",
        "      <td>                97</td>\n",
        "      <td>              38</td>\n",
        "      <td>              69</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>48</th>\n",
        "      <td>                                           BULGUR </td>\n",
        "      <td>               345</td>\n",
        "      <td>             123</td>\n",
        "      <td>              20</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>49</th>\n",
        "      <td>                               BUTTER BUFFALO/td&gt; </td>\n",
        "      <td>               717</td>\n",
        "      <td>               9</td>\n",
        "      <td>             811</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>50</th>\n",
        "      <td>                                      BUTTER SHEEP</td>\n",
        "      <td>               716</td>\n",
        "      <td>               6</td>\n",
        "      <td>             810</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>51</th>\n",
        "      <td>                                       BUTTER COWS</td>\n",
        "      <td>               717</td>\n",
        "      <td>               9</td>\n",
        "      <td>             811</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>52</th>\n",
        "      <td>                                       BUTTER GOAT</td>\n",
        "      <td>               717</td>\n",
        "      <td>               9</td>\n",
        "      <td>             811</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>53</th>\n",
        "      <td>                               BUTTER CURDLED MILK</td>\n",
        "      <td>                75</td>\n",
        "      <td>              30</td>\n",
        "      <td>              52</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>54</th>\n",
        "      <td>                                         CABBAGES </td>\n",
        "      <td>                19</td>\n",
        "      <td>              10</td>\n",
        "      <td>               1</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>55</th>\n",
        "      <td>                                CAKE OF GROUNDNUTS</td>\n",
        "      <td>               363</td>\n",
        "      <td>             417</td>\n",
        "      <td>              76</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>56</th>\n",
        "      <td>                              CAKE OF SESAME SEED </td>\n",
        "      <td>               376</td>\n",
        "      <td>             407</td>\n",
        "      <td>              34</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>57</th>\n",
        "      <td>                                      CAKE SOYBEAN</td>\n",
        "      <td>               261</td>\n",
        "      <td>             460</td>\n",
        "      <td>              50</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>58</th>\n",
        "      <td>                                       CAMEL MILK </td>\n",
        "      <td>                73</td>\n",
        "      <td>              38</td>\n",
        "      <td>              45</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>59</th>\n",
        "      <td>                                      CANARY SEED </td>\n",
        "      <td>               388</td>\n",
        "      <td>             160</td>\n",
        "      <td>              60</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th></th>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "    </tr>\n",
        "  </tbody>\n",
        "</table>\n",
        "<p>442 rows \u00d7 4 columns</p>\n",
        "</div>"
       ],
       "metadata": {},
       "output_type": "pyout",
       "prompt_number": 86,
       "text": [
        "                                    Nutritive factors         Unnamed: 1  \\\n",
        "0   FOOD AND AGRICULTURE ORGANIZATION OF THE UNITE...                NaN   \n",
        "1                                           COMMODITY           calories   \n",
        "2                                                 NaN  (per 100 grammes)   \n",
        "3                                        ALFALFA MEAL                265   \n",
        "4                                            ALMONDS                 236   \n",
        "5                                    ALMONDS SHELLED                 589   \n",
        "6                                              ANISE                 345   \n",
        "7                           APPLE JUICE CONCENTRATED                 166   \n",
        "8                        APPLE JUICE SINGLE STRENGTH                  47   \n",
        "9                                             APPLES                  48   \n",
        "10                                          APRICOTS                  45   \n",
        "11                                        ARECA NUTS                 245   \n",
        "12                                        ARTICHOKES                  20   \n",
        "13                                         ASPARAGUS                  12   \n",
        "14                                          AVOCADOS                 119   \n",
        "15                                        BACON PIGS                 362   \n",
        "16                                       BAMBARA BEAN                365   \n",
        "17                                           BANANAS                  60   \n",
        "18                                            BARLEY                 332   \n",
        "19                             BARLEY FLOUR AND GRITS                343   \n",
        "20                                       BARLEY PEARL                346   \n",
        "21                                          BEANS DRY                341   \n",
        "22                                        BEANS GREEN                 50   \n",
        "23                                       BEEF BONLESS                150   \n",
        "24                                       BEEF CANNED                 233   \n",
        "25                          BEEF DRIED, SALT, SMOKED                 203   \n",
        "26                                 BEEF PREPARATIONS                 233   \n",
        "27                                         BEEF VEAL                 225   \n",
        "28                                       BEER BARLEY                  49   \n",
        "29                                        BEER MAIZE                  40   \n",
        "30                                       BEER MILLET                  40   \n",
        "31                                       BEER SORGHUM                 40   \n",
        "32                                     BEET PULP DRY                 288   \n",
        "33                                       BERRIES NES                  49   \n",
        "34                    BEVERAGES DISTILLED. ALCOHOLIC                 295   \n",
        "35                            BEVERAGES NON ALCOHOLIC                 39   \n",
        "36                                       BLUEBERRIES                 120   \n",
        "37                                         BRAN RICE                 276   \n",
        "38                                        BRAN WHEAT                 213   \n",
        "39                                       BRAZIL NUTS                 315   \n",
        "40                                  BRAZILNUT SHELLED                656   \n",
        "41                                BROAD BEANS GROUND                  23   \n",
        "42                                    BROAD BEANS DRY                343   \n",
        "43                                             BREAD                 249   \n",
        "44                                BREAKFEAST CERLEALS                389   \n",
        "45                                         BUCKWHEAT                 330   \n",
        "46                                       BUFFALO MEAT                 77   \n",
        "47                                       BUFFALO MILK                 97   \n",
        "48                                            BULGUR                 345   \n",
        "49                                BUTTER BUFFALO/td>                 717   \n",
        "50                                       BUTTER SHEEP                716   \n",
        "51                                        BUTTER COWS                717   \n",
        "52                                        BUTTER GOAT                717   \n",
        "53                                BUTTER CURDLED MILK                 75   \n",
        "54                                          CABBAGES                  19   \n",
        "55                                 CAKE OF GROUNDNUTS                363   \n",
        "56                               CAKE OF SESAME SEED                 376   \n",
        "57                                       CAKE SOYBEAN                261   \n",
        "58                                        CAMEL MILK                  73   \n",
        "59                                       CANARY SEED                 388   \n",
        "                                                  ...                ...   \n",
        "\n",
        "         Unnamed: 2       Unnamed: 3  \n",
        "0               NaN              NaN  \n",
        "1           protein              fat  \n",
        "2   (mg per gramme)  (mg per gramme)  \n",
        "3               305               20  \n",
        "4                80              209  \n",
        "5               200              522  \n",
        "6               158              149  \n",
        "7                 5                4  \n",
        "8                 1                1  \n",
        "9                 1                3  \n",
        "10               13                4  \n",
        "11               49               44  \n",
        "12               11                1  \n",
        "13               16                1  \n",
        "14               15              113  \n",
        "15              131              341  \n",
        "16              177               63  \n",
        "17                7                3  \n",
        "18              120               18  \n",
        "19               92               17  \n",
        "20               90               14  \n",
        "21              221               17  \n",
        "22               30                4  \n",
        "23              185               79  \n",
        "24              250              140  \n",
        "25              343               63  \n",
        "26              250              140  \n",
        "27              147              180  \n",
        "28                5                0  \n",
        "29                4                0  \n",
        "30                4                0  \n",
        "31                4                0  \n",
        "32              111                6  \n",
        "33               10                7  \n",
        "34                0                0  \n",
        "35                0                0  \n",
        "36                7                4  \n",
        "37              133              158  \n",
        "38              121               31  \n",
        "39               69              318  \n",
        "40              143              662  \n",
        "41               23                1  \n",
        "42              234               20  \n",
        "43               82               12  \n",
        "44               74                7  \n",
        "45              120               20  \n",
        "46              113               31  \n",
        "47               38               69  \n",
        "48              123               20  \n",
        "49                9              811  \n",
        "50                6              810  \n",
        "51                9              811  \n",
        "52                9              811  \n",
        "53               30               52  \n",
        "54               10                1  \n",
        "55              417               76  \n",
        "56              407               34  \n",
        "57              460               50  \n",
        "58               38               45  \n",
        "59              160               60  \n",
        "                ...              ...  \n",
        "\n",
        "[442 rows x 4 columns]"
       ]
      }
     ],
     "prompt_number": 86
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "categories = pd.read_excel(masterpath+'Commodities_which_are_aggregated_or_standardized.xls','Sheet1')\n",
      "categories.head()\n",
      "categories[categories.WHEAT=='APPLES']"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "html": [
        "<div style=\"max-height:1000px;max-width:1500px;overflow:auto;\">\n",
        "<table border=\"1\" class=\"dataframe\">\n",
        "  <thead>\n",
        "    <tr style=\"text-align: right;\">\n",
        "      <th></th>\n",
        "      <th>WHEAT &amp; PRODUCTS </th>\n",
        "      <th>Unnamed: 1</th>\n",
        "      <th>Unnamed: 2</th>\n",
        "      <th>WHEAT</th>\n",
        "    </tr>\n",
        "  </thead>\n",
        "  <tbody>\n",
        "    <tr>\n",
        "      <th>628</th>\n",
        "      <td> APPLES &amp; PRODUCTS </td>\n",
        "      <td>NaN</td>\n",
        "      <td>NaN</td>\n",
        "      <td> APPLES</td>\n",
        "    </tr>\n",
        "  </tbody>\n",
        "</table>\n",
        "<p>1 rows \u00d7 4 columns</p>\n",
        "</div>"
       ],
       "metadata": {},
       "output_type": "pyout",
       "prompt_number": 46,
       "text": [
        "      WHEAT & PRODUCTS   Unnamed: 1  Unnamed: 2   WHEAT\n",
        "628  APPLES & PRODUCTS          NaN         NaN  APPLES\n",
        "\n",
        "[1 rows x 4 columns]"
       ]
      }
     ],
     "prompt_number": 46
    }
   ],
   "metadata": {}
  }
 ]
}{
 "metadata": {
  "name": "",
  "signature": "sha256:341bd633a049b52ca86829ec3fe495dd8d46f9c777d406dc983cba82af66ada6"
 },
 "nbformat": 3,
 "nbformat_minor": 0,
 "worksheets": [
  {
   "cells": [
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "import numpy as np, requests, zipfile, StringIO, pandas as pd, json, copy"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [],
     "prompt_number": 421
    },
    {
     "cell_type": "markdown",
     "metadata": {},
     "source": [
      "Connect to the FAO database and define indicator paths. Alternatively, the FAO databse is mirrored at the project website."
     ]
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "masterpath = 'http://faostat.fao.org/Portals/_Faostat/Downloads/zip_files/'\n",
      "#masterpath = 'http://food.csaladen.es/db/' #alternative mirror for entire FAO database\n",
      "localpath=True\n",
      "if localpath:\n",
      "    masterpath = 'E:/Skydrive/Documents/GitHub/Food-Energy/db/' #local path for downloaded FAO database, only for developer purposes\n",
      "indicators=[]\n",
      "indicators.append('CommodityBalances_Crops_E_All_Data') #0\n",
      "indicators.append('CommodityBalances_LivestockFish_E_All_Data') #1\n",
      "indicators.append('Emissions_Agriculture_Burning_crop_residues_E_All_Data') #2\n",
      "indicators.append('Emissions_Agriculture_Energy_E_All_Data') #3\n",
      "indicators.append('Emissions_Agriculture_Synthetic_Fertilizers_E_All_Data') #4\n",
      "indicators.append('Environment_Energy_E_All_Data') #5\n",
      "indicators.append('FoodBalanceSheets_E_All_Data') #6\n",
      "indicators.append('FoodSupply_Crops_E_All_Data') #7\n",
      "indicators.append('FoodSupply_LivestockFish_E_All_Data') #8\n",
      "indicators.append('Population_E_All_Data') #9\n",
      "indicators.append('Production_Crops_E_All_Data') #10\n",
      "indicators.append('Production_CropsProcessed_E_All_Data') #11\n",
      "indicators.append('Production_Livestock_E_All_Data') #12\n",
      "indicators.append('Production_LivestockPrimary_E_All_Data') #13\n",
      "indicators.append('Production_LivestockProcessed_E_All_Data') #14\n",
      "indicators.append('Resources_Fertilizers_E_All_Data') #15\n",
      "indicators.append('Resources_FertilizersArchive_E_All_Data') #16"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [],
     "prompt_number": 2
    },
    {
     "cell_type": "markdown",
     "metadata": {},
     "source": [
      "Select indicator and import data from the CSV from within the zip file. This can take anywhere from a few minutes to several hours, depending on your computer's performance. If you have access to paralell computing capabilites please turn them on at the *Clusters* tab of the main Ipython window. "
     ]
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "def get_data(ind):\n",
      "    if localpath:\n",
      "        r = masterpath+indicators[ind]+'.zip'\n",
      "        z = zipfile.ZipFile(r)\n",
      "    else:\n",
      "        r = requests.get(masterpath+indicators[ind]+'.zip')\n",
      "        z = zipfile.ZipFile(StringIO.StringIO(r.content))\n",
      "    return pd.read_csv(z.open(indicators[ind]+'.csv'))\n",
      "\n",
      "balance = get_data(6)\n",
      "energy = get_data(3)\n",
      "fertilizers1 = get_data(15)\n",
      "fertilizers2 = get_data(16)\n",
      "population = get_data(9)\n",
      "print set(balance.Element)\n",
      "print set(energy.Element)\n",
      "print set(fertilizers1.Element)\n",
      "print set(fertilizers2.Element)\n",
      "print set(population.Element)"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "output_type": "stream",
       "stream": "stdout",
       "text": [
        "set(['Feed', 'Stock Variation', 'Protein supply quantity', 'Food', 'Processing', 'Other Util', 'Food supply', 'Domestic supply quantity', 'Fat supply quantity', 'Seed', 'Food supply quantity (kg/capita', 'Total Population - Both sexes', 'Waste', 'Production', 'Import Quantity', 'Export Quantity'])\n",
        "set(['Emissions (CO2eq) (Energy)', 'Consumption in Agriculture', 'Emissions (N2O) (Energy)', 'Implied emission factor for CO2', 'Emissions (CH4) (Energy)', 'Implied emission factor for CH4', 'Emissions (CO2eq) from CH4 (Energy)', 'Emissions (CO2eq) from N2O (Energy)', 'Emissions (CO2) (Energy)', 'Implied emission factor for N2O'])\n",
        "set(['Export Quantity in nutrients', 'Consumption', 'Export Quantity', 'Consumption in nutrients', 'Non-fertilizer use', 'Production Quantity in nutrients', 'Non-fertilizer use in nutrients', 'Production', 'Import Quantity', 'Import Quantity in nutrients'])\n",
        "set(['Export Quantity', 'Prices Paid by Farmers', 'Production', 'Import Quantity', 'Consumption'])"
       ]
      },
      {
       "output_type": "stream",
       "stream": "stdout",
       "text": [
        "\n",
        "set(['Total economically active population in Agr', 'Total Population - Male', 'Total Population - Female', 'Total economically active population', 'Rural population', 'Female economically active population', 'Urban population', 'Male economically active population in Agr', 'Male economically active population', 'Female economically active population in Agr', 'Total Population - Both sexes'])\n"
       ]
      }
     ],
     "prompt_number": 489
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "data = population\n",
      "print set(data[((data.Element=='Total economically active population in Agr')&(data.Year==2003)&(data.Country=='Brazil'))].Item)\n",
      "data[((data.Element=='Total economically active population in Agr')&(data.Year==2003)&(data.Country=='Brazil'))]"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "output_type": "stream",
       "stream": "stdout",
       "text": [
        "set(['Population - Est. & Proj.'])\n"
       ]
      },
      {
       "html": [
        "<div style=\"max-height:1000px;max-width:1500px;overflow:auto;\">\n",
        "<table border=\"1\" class=\"dataframe\">\n",
        "  <thead>\n",
        "    <tr style=\"text-align: right;\">\n",
        "      <th></th>\n",
        "      <th>CountryCode</th>\n",
        "      <th>Country</th>\n",
        "      <th>ItemCode</th>\n",
        "      <th>Item</th>\n",
        "      <th>ElementGroup</th>\n",
        "      <th>ElementCode</th>\n",
        "      <th>Element</th>\n",
        "      <th>Year</th>\n",
        "      <th>Unit</th>\n",
        "      <th>Value</th>\n",
        "      <th>Flag</th>\n",
        "    </tr>\n",
        "  </thead>\n",
        "  <tbody>\n",
        "    <tr>\n",
        "      <th>42040</th>\n",
        "      <td> 21</td>\n",
        "      <td> Brazil</td>\n",
        "      <td> 3010</td>\n",
        "      <td> Population - Est. &amp; Proj.</td>\n",
        "      <td> 601</td>\n",
        "      <td> 601</td>\n",
        "      <td> Total economically active population in Agr</td>\n",
        "      <td> 2003</td>\n",
        "      <td> 1000</td>\n",
        "      <td> 12805</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "  </tbody>\n",
        "</table>\n",
        "<p>1 rows \u00d7 11 columns</p>\n",
        "</div>"
       ],
       "metadata": {},
       "output_type": "pyout",
       "prompt_number": 488,
       "text": [
        "       CountryCode Country  ItemCode                       Item  ElementGroup  \\\n",
        "42040           21  Brazil      3010  Population - Est. & Proj.           601   \n",
        "\n",
        "       ElementCode                                      Element  Year  Unit  \\\n",
        "42040          601  Total economically active population in Agr  2003  1000   \n",
        "\n",
        "       Value Flag  \n",
        "42040  12805  NaN  \n",
        "\n",
        "[1 rows x 11 columns]"
       ]
      }
     ],
     "prompt_number": 488
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "def add_to_json(data,i,source,target,value,prod,supply):\n",
      "    global groupdict\n",
      "    global count\n",
      "    if (~np.isnan(value)&(value!=0)):\n",
      "        if source not in groupdict[i]: \n",
      "            groupdict[i][source]=count[i]\n",
      "            data[i][\"nodes\"].append({\"name\":source})\n",
      "            count[i] += 1 \n",
      "        if target not in groupdict[i]: \n",
      "            groupdict[i][target]=count[i]\n",
      "            data[i][\"nodes\"].append({\"name\":target})\n",
      "            count[i] += 1 \n",
      "        links_innerdict={} \n",
      "        links_innerdict[\"source\"]=groupdict[i][source]\n",
      "        links_innerdict[\"target\"]=groupdict[i][target]\n",
      "        links_innerdict[\"value\"]=value\n",
      "        links_innerdict[\"prod\"]=prod\n",
      "        links_innerdict[\"supply\"]=supply\n",
      "        data[i][\"links\"].append(links_innerdict)\n",
      "\n",
      "#elements1=['Feed','Food','Processing','Other Util','Seed','Waste','Stock Variation','Import Quantity','Export Quantity']\n",
      "elements1=['Feed','Food','Processing','Other Util','Seed','Waste']\n",
      "elements2=['Food supply','Food supply quantity (kg/capita']\n",
      "fuels=['Gas-diesel oils', 'Natural gas (including LNG)', 'Residual fuel oil', 'Liquefied petroleum gas (LPG)']\n",
      "fert1=['Phosphate fertilizers', 'Potash fertilizers', 'Nitrogenous fertilizers']\n",
      "fert2=['Potash Fertilizers (K20 total nutrients)', 'Phosphate Fertilizers (P205 total nutrients)', 'Nitrogen Fertilizers (N total nutrients)']\n",
      "#for country in set(data.Country.values):\n",
      "for country in ['United States of America', 'Canada', 'China', 'India']:    #['World + (Total)']\n",
      "   #for year in set(balance[balance.Country==country].Year.values):\n",
      "   for year in range(1981,2009):\n",
      "     #try:\n",
      "            \n",
      "        ###############################################################################################\n",
      "        ######                                   FOOD PART                                       ######\n",
      "        ###############################################################################################\n",
      "        \n",
      "        #initialize food output variable for sum collection and processing for EROEI\n",
      "        foodoutput=0\n",
      "        \n",
      "        # associate food items to their respective groups\n",
      "        n = 4          #number of grouping variations\n",
      "        supergroup=[]  #group to which food item entry belongs to. defined below, custom groups possible, along the FAO official ones \n",
      "        parent={}      #food item parent(source) node, where applicable (secondary food items), i.e. Feed for Animal Products or Milk for Cheese\n",
      "        for i in range (n):\n",
      "            supergroup.append({})\n",
      "        \n",
      "        for i in balance[(balance.Element==\"Food\")&(balance.Year==year)&(balance.Country==country)\\\n",
      "                          &(((2511<=balance.ItemCode)&(balance.ItemCode<=2782))\\\n",
      "                          |(balance.ItemCode==2805)\\\n",
      "                          |(balance.ItemCode==2899)\\\n",
      "                          |(balance.ItemCode==2912)\\\n",
      "                          |(balance.ItemCode==2945)\\\n",
      "                          |(balance.ItemCode==2948)\\\n",
      "                          |(balance.ItemCode==2949)\\\n",
      "                          |(balance.ItemCode==2961))].values:\n",
      "            fooditem=i[3]         #choose column in which food item names are stored, might need to change it\n",
      "            if \"+\" in fooditem:   #simplify food names for the sake of visualization\n",
      "                fooditem=fooditem[0:fooditem.find(\"+\")-1]\n",
      "            if \"(\" in fooditem:\n",
      "                fooditem=fooditem[0:fooditem.find(\"(\")-1]\n",
      "            if \"and products\" in fooditem:\n",
      "                fooditem=fooditem[0:fooditem.find(\"and products\")-1]\n",
      "            index = i[2]         #choose column in which food group codes are stored, might need to change it\n",
      "            parent[fooditem]='None'\n",
      "            for i in range (n):  #assign default supergroup 'Others' and no parent to all food items\n",
      "                supergroup[i][fooditem]='Others'\n",
      "            if ((2511<=index<=2659) | (index==2745) | (index==2805) | (index==2899) | (index==2912)):\n",
      "                if ((2511<=index<=2520) | (index==2805)):\n",
      "                    supergroup[1][fooditem] = 'Cereals - Excluding Beer'\n",
      "                    supergroup[0][fooditem] = 'Cereals'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'None'\n",
      "                elif (2531<=index<=2535):\n",
      "                    supergroup[1][fooditem] = 'Starchy Roots'\n",
      "                    supergroup[0][fooditem] = 'Starchy Roots'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'None'\n",
      "                elif (2536<=index<=2537):\n",
      "                    supergroup[1][fooditem] = 'Sugar Crops'\n",
      "                    supergroup[0][fooditem] = 'Sugar Crops'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'None'\n",
      "                elif ((2541<=index<=2543)|(index==2745)):\n",
      "                    supergroup[1][fooditem] = 'Sugar & Sweeteners'\n",
      "                    supergroup[0][fooditem] = 'Sugar'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'Processing'\n",
      "                elif (2546<=index<=2549):\n",
      "                    supergroup[1][fooditem] = 'Pulses'\n",
      "                    supergroup[0][fooditem] = 'Fruits & Vegetables'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'None'\n",
      "                elif (2555<=index<=2570):\n",
      "                    supergroup[1][fooditem] = 'Oilcrops'\n",
      "                    supergroup[0][fooditem] = 'Oilcrops'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'None'\n",
      "                elif (2571<=index<=2586):\n",
      "                    supergroup[1][fooditem] = 'Vegetable Oils'\n",
      "                    supergroup[0][fooditem] = 'Vegetable Oils'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'Processing'\n",
      "                elif (2601<=index<=2605):\n",
      "                    supergroup[1][fooditem] = 'Vegetables'\n",
      "                    supergroup[0][fooditem] = 'Fruits & Vegetables'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'None'\n",
      "                elif (2611<=index<=2625):\n",
      "                    supergroup[1][fooditem] = 'Fruits - Excluding Wine'\n",
      "                    supergroup[0][fooditem] = 'Fruits & Vegetables'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'None'\n",
      "                elif (2630<=index<=2635):\n",
      "                    supergroup[1][fooditem] = 'Stimulants'\n",
      "                    supergroup[0][fooditem] = 'Others'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'None'\n",
      "                elif (2640<=index<=2645):\n",
      "                    supergroup[1][fooditem] = 'Spices'\n",
      "                    supergroup[0][fooditem] = 'Others'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'None'\n",
      "                elif (2655<=index<=2659):\n",
      "                    supergroup[1][fooditem] = 'Alcoholic Beverages'\n",
      "                    supergroup[0][fooditem] = 'Other Processed'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'Processing'\n",
      "                elif (index==2899):\n",
      "                    supergroup[1][fooditem] = 'Miscellaneous'\n",
      "                    supergroup[0][fooditem] = 'Others'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'None'\n",
      "                elif (index==2912):\n",
      "                    supergroup[1][fooditem] = 'Treenuts'\n",
      "                    supergroup[0][fooditem] = 'Fruits & Vegetables'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'None'\n",
      "                       \n",
      "            elif ((2731<=index<=2782) | (index==2945)| (index==2948) | (index==2949) | (index==2961)):\n",
      "                if (2731<=index<=2736):\n",
      "                    supergroup[1][fooditem] = 'Meat'\n",
      "                    supergroup[0][fooditem] = 'Animal Products'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'Feed'\n",
      "                elif (2737<=index<=2743):\n",
      "                    supergroup[1][fooditem] = 'Animal Fats'  \n",
      "                    supergroup[0][fooditem] = 'Other Processed' \n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'Processing'\n",
      "                elif (2761<=index<=2768):\n",
      "                    supergroup[1][fooditem] = 'Fish, Seafood'\n",
      "                    supergroup[0][fooditem] = 'Aquatic Products'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'Feed'\n",
      "                elif ((2769<=index<=2775)|(index==2961)):\n",
      "                    supergroup[1][fooditem] = 'Aquatic Products, Other'\n",
      "                    supergroup[0][fooditem] = 'Aquatic Products'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'Feed'\n",
      "                elif (2781<=index<=2782):\n",
      "                    supergroup[1][fooditem] = 'Animal Fats'\n",
      "                    supergroup[0][fooditem] = 'Other Processed'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'Processing'\n",
      "                elif (index==2945):\n",
      "                    supergroup[1][fooditem] = 'Offals'\n",
      "                    supergroup[0][fooditem] = 'Animal Products'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'Feed'\n",
      "                elif (index==2948):\n",
      "                    supergroup[1][fooditem] = 'Milk - Excluding Butter'\n",
      "                    supergroup[0][fooditem] = 'Animal Products'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'Feed'\n",
      "                elif (index==2949):\n",
      "                    supergroup[1][fooditem] = 'Eggs'    \n",
      "                    supergroup[0][fooditem] = 'Animal Products'\n",
      "                    parent[fooditem]=parent[supergroup[0][fooditem]]=parent[supergroup[1][fooditem]]= 'Feed'\n",
      "        \n",
      "        #extract food item caloric values\n",
      "        percapitasupply={}\n",
      "        percapitaenergy={}\n",
      "        for i in balance[(balance.Element=='Food supply')&(balance.Year==year)&(balance.Country==country)].values:\n",
      "            foodvalue=i[9]        #choose column in which food item values are stored, might need to change it\n",
      "            fooditem=i[3]         #choose column in which food item names are stored, might need to change it\n",
      "            if \"+\" in fooditem:   #simplify food names for the sake of visualization\n",
      "                fooditem=fooditem[0:fooditem.find(\"+\")-1]\n",
      "            if \"(\" in fooditem:\n",
      "                fooditem=fooditem[0:fooditem.find(\"(\")-1]\n",
      "            if \"and products\" in fooditem:\n",
      "                fooditem=fooditem[0:fooditem.find(\"and products\")-1]\n",
      "            percapitaenergy[fooditem]=foodvalue\n",
      "        \n",
      "        for i in balance[(balance.Element=='Food supply quantity (kg/capita')&(balance.Year==year)&(balance.Country==country)].values:\n",
      "            foodvalue=i[9]        #choose column in which food item values are stored, might need to change it\n",
      "            fooditem=i[3]         #choose column in which food item names are stored, might need to change it\n",
      "            if \"+\" in fooditem:   #simplify food names for the sake of visualization\n",
      "                fooditem=fooditem[0:fooditem.find(\"+\")-1]\n",
      "            if \"(\" in fooditem:\n",
      "                fooditem=fooditem[0:fooditem.find(\"(\")-1]\n",
      "            if \"and products\" in fooditem:\n",
      "                fooditem=fooditem[0:fooditem.find(\"and products\")-1]\n",
      "            percapitasupply[fooditem]=foodvalue*1000/365.25 #kg/year/capita->g/day/capita\n",
      "        \n",
      "        foodcalorie={}\n",
      "        for i in percapitasupply:\n",
      "            foodcalorie[i]=100  #set default caloric value for all food items, necessary to handle exceptions\n",
      "            if i in percapitaenergy:\n",
      "                if ((percapitasupply[i]==0)|(percapitaenergy[i]==0)): #if either term is null, try to assing the supergroup values, if they exist\n",
      "                    if ((i in supergroup[1])&(supergroup[1][i] in percapitasupply)&(supergroup[1][i] in percapitaenergy)):\n",
      "                        if ((percapitasupply[supergroup[1][i]]!=0)&(percapitaenergy[supergroup[1][i]]!=0)):\n",
      "                            foodcalorie[i]=100*percapitaenergy[supergroup[1][i]]/percapitasupply[supergroup[1][i]]\n",
      "                else:\n",
      "                    foodcalorie[i]=100*percapitaenergy[i]/percapitasupply[i]\n",
      "        \n",
      "        #extract supply data and calculate energy data\n",
      "        energydata=[]  #initialize dictionary array for later JSON export for D3 & sankey.js visualization\n",
      "        supplydata=[]  #initialize dictionary array for later JSON export for D3 & sankey.js visualization\n",
      "        count = []     #counter for the groupdict below\n",
      "        groupdict=[{}] #initialize dictionary for mapping food category names to JSON, in the order of addition - necessary format for sankey.js\n",
      "        parentsupplysum=[]   #dictionary to keep track of item sums in case of aggregations, based on the supergroup variable defined above\n",
      "        parentenergysum=[]   #dictionary to keep track of item sums in case of aggregations, based on the supergroup variable defined above    \n",
      "        for i in range (n):\n",
      "            energydata.append({\"nodes\":[],\"links\":[]})\n",
      "            supplydata.append({\"nodes\":[],\"links\":[]})\n",
      "            count.append(0)\n",
      "            groupdict.append({})\n",
      "            supergroup.append({})\n",
      "            parentsupplysum.append({})\n",
      "            parentenergysum.append({})\n",
      "        \n",
      "        for element in elements1:\n",
      "            supplysum=[]   #dictionary to keep track of item sums in case of aggregations, based on the supergroup variable defined above\n",
      "            energysum=[]   #dictionary to keep track of item sums in case of aggregations, based on the supergroup variable defined above\n",
      "            for i in range (n):\n",
      "                supplysum.append({})\n",
      "                energysum.append({})\n",
      "            \n",
      "            for i in balance[(balance.Element==element)&(balance.Year==year)&(balance.Country==country)\\\n",
      "                          &(((2511<=balance.ItemCode)&(balance.ItemCode<=2782))\\\n",
      "                          |(balance.ItemCode==2805)\\\n",
      "                          |(balance.ItemCode==2899)\\\n",
      "                          |(balance.ItemCode==2912)\\\n",
      "                          |(balance.ItemCode==2945)\\\n",
      "                          |(balance.ItemCode==2948)\\\n",
      "                          |(balance.ItemCode==2949)\\\n",
      "                          |(balance.ItemCode==2961))].values:\n",
      "                foodvalue=i[9]            #choose column in which food item values are stored, might need to change it\n",
      "                if (~np.isnan(foodvalue)&(foodvalue!=0)):\n",
      "                    fooditem=i[3]         #choose column in which food item names are stored, might need to change it\n",
      "                    if \"+\" in fooditem:   #simplify food names for the sake of visualization\n",
      "                        fooditem=fooditem[0:fooditem.find(\"+\")-1]\n",
      "                    if \"(\" in fooditem:\n",
      "                        fooditem=fooditem[0:fooditem.find(\"(\")-1]\n",
      "                    if \"and products\" in fooditem:\n",
      "                        fooditem=fooditem[0:fooditem.find(\"and products\")-1]\n",
      "                    \n",
      "                    energyvalue=foodvalue*foodcalorie[fooditem]*0.00116222222/100\n",
      "                          #TWh = 1000tons * kcal/100g # 10^9) /100g * 0.00116222222 kwh/kcal *10^-9 TWh/kWh\n",
      " \n",
      "                   #create links for detail level 3    \n",
      "                    if (element==\"Seed\"):  #replace seed group with self-loops \n",
      "                        add_to_json(supplydata,2,fooditem,fooditem,foodvalue,energyvalue,'[{\"l\":'+repr(fooditem)+',\"v\":'+repr(foodvalue)+'}]')   \n",
      "                        add_to_json(energydata,2,fooditem,fooditem,energyvalue,foodvalue,'[{\"l\":'+repr(fooditem)+',\"v\":'+repr(energyvalue)+'}]')   \n",
      "                    else:\n",
      "                        add_to_json(supplydata,2,fooditem,element,foodvalue,energyvalue,'[{\"l\":'+repr(fooditem)+',\"v\":'+repr(foodvalue)+'}]')\n",
      "                        add_to_json(energydata,2,fooditem,element,energyvalue,foodvalue,'[{\"l\":'+repr(fooditem)+',\"v\":'+repr(energyvalue)+'}]')\n",
      "                    \n",
      "                        #sum all links going into food for sepparate representation\n",
      "                        if (element==\"Food\"):\n",
      "                            foodoutput+=energyvalue\n",
      "                        \n",
      "                    #create aggregate values for parent links detail level 3\n",
      "                    if fooditem in parentsupplysum[2]:\n",
      "                        parentsupplysum[2][fooditem]+=foodvalue\n",
      "                        parentenergysum[2][fooditem]+=energyvalue\n",
      "                    else:\n",
      "                        parentsupplysum[2][fooditem]=foodvalue\n",
      "                        parentenergysum[2][fooditem]=energyvalue\n",
      "                    \n",
      "                    #create aggregate values for detail levels 1-2\n",
      "                    for i in range(2): #sum food item values over different groups, defined above, currently 1-2\n",
      "                        #save sum, but also components for the piechart breakdown\n",
      "                        if supergroup[i][fooditem] in supplysum[i]:\n",
      "                            supplysum[i][supergroup[i][fooditem]][\"data\"].append({\"l\":fooditem, \"v\":foodvalue})\n",
      "                            supplysum[i][supergroup[i][fooditem]][\"sum\"]+=foodvalue\n",
      "                            energysum[i][supergroup[i][fooditem]][\"data\"].append({\"l\":fooditem, \"v\":energyvalue})\n",
      "                            energysum[i][supergroup[i][fooditem]][\"sum\"]+=energyvalue\n",
      "                        else:\n",
      "                            supplysum[i][supergroup[i][fooditem]]={\"data\":[{\"l\":fooditem, \"v\":foodvalue}],\"sum\":foodvalue}\n",
      "                            energysum[i][supergroup[i][fooditem]]={\"data\":[{\"l\":fooditem, \"v\":energyvalue}],\"sum\":energyvalue}\n",
      "            \n",
      "            #create links for detail levels 1-2    \n",
      "            for i in range(2):\n",
      "                for j in supplysum[i]:\n",
      "                    if (element==\"Seed\"):\n",
      "                        add_to_json(supplydata,i,j,j,supplysum[i][j][\"sum\"],energysum[i][j][\"sum\"],supplysum[i][j][\"data\"])\n",
      "                        add_to_json(energydata,i,j,j,energysum[i][j][\"sum\"],supplysum[i][j][\"sum\"],energysum[i][j][\"data\"])\n",
      "                    else:\n",
      "                        add_to_json(supplydata,i,j,element,supplysum[i][j][\"sum\"],energysum[i][j][\"sum\"],supplysum[i][j][\"data\"])\n",
      "                        add_to_json(energydata,i,j,element,energysum[i][j][\"sum\"],supplysum[i][j][\"sum\"],energysum[i][j][\"data\"])\n",
      "            \n",
      "            #create aggregate values for parent links detail levels 1-2\n",
      "            for i in range(2):\n",
      "                for j in set(supplysum[i]):\n",
      "                    if j in parentsupplysum[i]:\n",
      "                        parentsupplysum[i][j]+=supplysum[i][j][\"sum\"]\n",
      "                        parentenergysum[i][j]+=energysum[i][j][\"sum\"]\n",
      "                    else:\n",
      "                        parentsupplysum[i][j]=supplysum[i][j][\"sum\"]\n",
      "                        parentenergysum[i][j]=energysum[i][j][\"sum\"]\n",
      "                   \n",
      "        #create parent links for detail levels 1-3\n",
      "        for i in range(3):    \n",
      "            for j in parentsupplysum[i]:\n",
      "                if (parent[j]!=\"None\"):\n",
      "                    add_to_json(supplydata,i, parent[j],j,parentsupplysum[i][j],parentenergysum[i][j],'[{\"l\":'+repr( parent[j])+',\"v\":'+repr(parentsupplysum[i][j])+'}]')\n",
      "                    add_to_json(energydata,i, parent[j],j,parentenergysum[i][j],parentsupplysum[i][j],'[{\"l\":'+repr( parent[j])+',\"v\":'+repr(parentenergysum[i][j])+'}]')\n",
      "        \n",
      "        #update nodes name map\n",
      "        for i in range(n):\n",
      "            energydata[i]['nodes']=supplydata[i]['nodes']\n",
      "            \n",
      "        ###############################################################################################\n",
      "        ######                                   FUEL PART                                       ######\n",
      "        ###############################################################################################\n",
      "        \n",
      "        #calculate crops share for energy input distribution\n",
      "        supplyshare=[]\n",
      "        energyshare=[]\n",
      "        fuelenergysum=[]\n",
      "        for i in range (n):\n",
      "            supplyshare.append({})\n",
      "            energyshare.append({})\n",
      "            fuelenergysum.append({})\n",
      "        \n",
      "        cropsum=[]\n",
      "        cropenergy=[]\n",
      "        for i in range(n):\n",
      "            cropsum.append(0)\n",
      "            cropenergy.append(0)\n",
      "            for j in parentsupplysum[i]:\n",
      "                if (parent[j]=='None'):\n",
      "                    cropsum[i] += parentsupplysum[i][j]\n",
      "                    cropenergy[i] += parentenergysum[i][j]\n",
      "        \n",
      "        for i in range(n):\n",
      "            for j in parentsupplysum[i]:\n",
      "                if (parent[j]=='None'):\n",
      "                    supplyshare[i][j] = parentsupplysum[i][j]/cropsum[i]\n",
      "                    energyshare[i][j] = parentenergysum[i][j]/cropenergy[i]\n",
      "        \n",
      "        #distribute electricity input\n",
      "        for fuel in ['Electricity']:\n",
      "            for i in energy[(energy.Element=='Consumption in Agriculture')&(energy.Year==year)&(energy.Country==country)\\\n",
      "                            &(energy.Unit=='Terajoule')&(energy.Item==fuel)].values:\n",
      "                fuelvalue=i[9]            #choose column in which fuel item values are stored, might need to change it\n",
      "                if (~np.isnan(fuelvalue)&(fuelvalue!=0)):\n",
      "                    fuelitem=i[3]         #choose column in which fuel item names are stored, might need to change it\n",
      "                    if \"+\" in fuelitem:   #simplify fuel names for the sake of visualization\n",
      "                        fuelitem=fuelitem[0:fuelitem.find(\"+\")-1]\n",
      "                    if \"(\" in fooditem:\n",
      "                        fuelitem=fuelitem[0:fuelitem.find(\"(\")-1]\n",
      "                    if \"and products\" in fuelitem:\n",
      "                        fuelitem=fuelitem[0:fuelitem.find(\"and products\")-1]\n",
      "                    electricityvalue=fuelvalue*0.000277777778 #1 joule = 0.000277777778 Wh\n",
      "                    for i in range(n):\n",
      "                        for j in parentsupplysum[i]:\n",
      "                            if (parent[j]=='None'):\n",
      "                                add_to_json(energydata,i, fuel,j,electricityvalue*energyshare[i][j],0,'[{\"l\":'+repr(fuel)+',\"v\":'+repr(electricityvalue*energyshare[i][j])+'}]')\n",
      "         \n",
      "        #distribute fossil fuel input\n",
      "        for fuel in fuels:\n",
      "            for i in energy[(energy.Element=='Consumption in Agriculture')&(energy.Year==year)&(energy.Country==country)\\\n",
      "                            &(energy.Unit=='Terajoule')&(energy.Item==fuel)].values:\n",
      "                fuelvalue=i[9]            #choose column in which fuel item values are stored, might need to change it\n",
      "                if (~np.isnan(fuelvalue)&(fuelvalue!=0)):\n",
      "                    fuelitem=i[3]         #choose column in which fuel item names are stored, might need to change it\n",
      "                    if \"+\" in fuelitem:   #simplify fuel names for the sake of visualization\n",
      "                        fuelitem=fuelitem[0:fuelitem.find(\"+\")-1]\n",
      "                    if \"(\" in fooditem:\n",
      "                        fuelitem=fuelitem[0:fuelitem.find(\"(\")-1]\n",
      "                    if \"and products\" in fuelitem:\n",
      "                        fuelitem=fuelitem[0:fuelitem.find(\"and products\")-1]\n",
      "                    fuelvalue*=0.000277777778 #1 joule = 0.000277777778 Wh\n",
      "                    for i in range(n): #sum fuel item values over all groups\n",
      "                        supergroup[i][fuelitem]=\"Fossil Fuels\"\n",
      "                        #save sum, but also components for the piechart breakdown\n",
      "                        if supergroup[i][fuelitem] in fuelenergysum[i]:\n",
      "                            fuelenergysum[i][supergroup[i][fuelitem]][\"data\"].append({\"l\":fuelitem, \"v\":fuelvalue})\n",
      "                            fuelenergysum[i][supergroup[i][fuelitem]][\"sum\"]+=fuelvalue\n",
      "                        else:\n",
      "                            fuelenergysum[i][supergroup[i][fuelitem]]={\"data\":[{\"l\":fuelitem, \"v\":fuelvalue}],\"sum\":fuelvalue}\n",
      "        f_save=copy.deepcopy(fuelenergysum)\n",
      "        for i in range(n):\n",
      "            for j in parentsupplysum[i]:\n",
      "                fuelenergysum=copy.deepcopy(f_save)\n",
      "                if (parent[j]=='None'):\n",
      "                    for k in fuelenergysum[i]:\n",
      "                        for f in fuelenergysum[i][k][\"data\"]:\n",
      "                            f[\"v\"]*=energyshare[i][j]\n",
      "                        add_to_json(energydata,i,k,j,fuelenergysum[i][k][\"sum\"]*energyshare[i][j],0,fuelenergysum[i][k][\"data\"])\n",
      "         \n",
      "        \n",
      "        ###############################################################################################\n",
      "        ######                                   FERTILIZERS PART                                ######\n",
      "        ###############################################################################################\n",
      "        \n",
      "        fertenergysum=[]\n",
      "        fertsupplysum=[]\n",
      "        for i in range (n):\n",
      "            fertenergysum.append({})\n",
      "            fertsupplysum.append({})\n",
      "        \n",
      "        if (year<2003):\n",
      "            fertilizers=fertilizers2 #inverted on purpose\n",
      "            fertnames=fert1\n",
      "            fertelement='Consumption'\n",
      "        else:\n",
      "            fertilizers=fertilizers1\n",
      "            fertnames=fert2\n",
      "            fertelement='Consumption in nutrients'\n",
      "        for fert in fertnames:\n",
      "            for i in fertilizers[(fertilizers.Element==fertelement)&(fertilizers.Year==year)&(fertilizers.Country==country)\\\n",
      "                            &(fertilizers.Item==fert)].values:\n",
      "                fertvalue=i[9]            #choose column in which fert item values are stored, might need to change it\n",
      "                if (~np.isnan(fertvalue)&(fertvalue!=0)):\n",
      "                    fertitem=i[3]         #choose column in which fert item names are stored, might need to change it\n",
      "                    #define energy content+packaging and transport (http://www.engr.usask.ca/societies/csae/c9915.pdf page10)\n",
      "                    if fertitem in ['Phosphate fertilizers', 'Phosphate Fertilizers (P205 total nutrients)']:\n",
      "                        fertenergycontent=6.82+8.33 #MJ/kg \n",
      "                        fertitem='Phosphate'\n",
      "                    if fertitem in ['Potash fertilizers', 'Potash Fertilizers (K20 total nutrients)']:\n",
      "                        fertenergycontent=2.88+6.35 #MJ/kg\n",
      "                        fertitem='Potash'\n",
      "                    if fertitem in ['Nitrogenous fertilizers', 'Nitrogen Fertilizers (N total nutrients)']:\n",
      "                        fertenergycontent=59+7.05 #MJ/kg\n",
      "                        fertitem='Nitrogen'\n",
      "                    \n",
      "                    fertvalue=fertvalue/1000 #model units are in 1000 tonnes\n",
      "                    fertenergy=fertvalue*fertenergycontent         *  0.000277777778   #TWh \n",
      "                                          #MJ/kg / TJ/1000tonnes   *  #1 joule = 0.000277777778 Wh\n",
      "                    for i in range(n): #sum fert item values over all groups\n",
      "                        supergroup[i][fertitem]=\"Fertilizers\"\n",
      "                        #save sum, but also components for the piechart breakdown\n",
      "                        if supergroup[i][fertitem] in fertenergysum[i]:\n",
      "                            fertenergysum[i][supergroup[i][fertitem]][\"data\"].append({\"l\":fertitem, \"v\":fertenergy})\n",
      "                            fertenergysum[i][supergroup[i][fertitem]][\"sum\"]+=fertenergy\n",
      "                            fertsupplysum[i][supergroup[i][fertitem]][\"data\"].append({\"l\":fertitem, \"v\":fertvalue})\n",
      "                            fertsupplysum[i][supergroup[i][fertitem]][\"sum\"]+=fertvalue\n",
      "                        else:\n",
      "                            fertenergysum[i][supergroup[i][fertitem]]={\"data\":[{\"l\":fertitem, \"v\":fertenergy}],\"sum\":fertenergy}\n",
      "                            fertsupplysum[i][supergroup[i][fertitem]]={\"data\":[{\"l\":fertitem, \"v\":fertvalue}],\"sum\":fertvalue}\n",
      "        f_save=copy.deepcopy(fertenergysum)\n",
      "        for i in range(n):\n",
      "            for j in parentsupplysum[i]:\n",
      "                fertenergysum=copy.deepcopy(f_save)\n",
      "                if (parent[j]=='None'):\n",
      "                    for k in fertenergysum[i]:\n",
      "                        for f in fertenergysum[i][k][\"data\"]:\n",
      "                            f[\"v\"]*=energyshare[i][j]\n",
      "                        add_to_json(energydata,i,k,j,fertenergysum[i][k][\"sum\"]*energyshare[i][j],fertsupplysum[i][k][\"sum\"]*energyshare[i][j],fertenergysum[i][k][\"data\"])\n",
      "           \n",
      "        ###############################################################################################\n",
      "        ######                                   LABOR PART                                      ######\n",
      "        ###############################################################################################\n",
      "        \n",
      "        calorietotal=balance[(balance.Element=='Food supply')&(balance.Year==year)&(balance.Country==country)\\\n",
      "                             &(balance.Item=='Grand Total + (Total)')].values[0][9] #second index: choose column in which pop item values are stored, might need to change it\n",
      "        popvalue=population[(population.Element=='Total economically active population in Agr')&(population.Year==year)\\\n",
      "                            &(population.Country==country)].values[0][9] #second index: choose column in which pop item values are stored, might need to change it\n",
      "        if (~np.isnan(popvalue)&(popvalue!=0)):\n",
      "            workyear=5.0/7.0*365.25   #working days spent with farming per year\n",
      "            \n",
      "            hourlycalorieburn=204        #calories needed per hour of farming\n",
      "            hoursperday=12               #hours per day spent farming\n",
      "            minimumcalorieburn=hourlycalorieburn*hoursperday\n",
      "            calorieburn=0.9              #percent of calorie intake burned for farming, if below minimum\n",
      "            \n",
      "            laborenergy=min(minimumcalorieburn,calorieburn*calorietotal)*workyear*popvalue*1000*0.00116222222/1000000000\n",
      "                                                                                              # 0.00116222222 kwh/kcal *10^-9 TWh/kWh\n",
      "            for i in range(n):\n",
      "                for j in parentsupplysum[i]:\n",
      "                    if (parent[j]=='None'):\n",
      "                        add_to_json(energydata,i,\"Labor\",j,laborenergy*energyshare[i][j],0,'[{\"l\":'+repr(\"Labor\")+',\"v\":'+repr(laborenergy*energyshare[i][j])+'}]')\n",
      "         \n",
      "        ###############################################################################################\n",
      "        ######                                   SAVE DATA                                       ######\n",
      "        ###############################################################################################\n",
      "        \n",
      "        for i in range(n):\n",
      "            file('../json/'+country+repr(year)+'d'+repr(i+1)+'.json','w').write(json.dumps(supplydata[i]))\n",
      "            file('../json/'+country+repr(year)+'e'+repr(i+1)+'.json','w').write(json.dumps(energydata[i]))\n",
      "        \n",
      "        #create global input-output graph    \n",
      "        fooddata={\"nodes\":[{\"name\": \"Input\"},{\"name\": \"Food\"},{\"name\": \"Output\"}],\"links\":[]}\n",
      "        foodinput=laborenergy+fertenergysum[0][\"Fertilizers\"][\"sum\"]+fuelenergysum[0][\"Fossil Fuels\"][\"sum\"]+electricityvalue\n",
      "        \n",
      "        links_innerdict={} \n",
      "        links_innerdict[\"source\"]=0\n",
      "        links_innerdict[\"target\"]=1\n",
      "        links_innerdict[\"value\"]=foodinput\n",
      "        fooddata[\"links\"].append(links_innerdict)\n",
      "        \n",
      "        links_innerdict={} \n",
      "        links_innerdict[\"source\"]=1\n",
      "        links_innerdict[\"target\"]=2\n",
      "        links_innerdict[\"value\"]=foodoutput\n",
      "        fooddata[\"links\"].append(links_innerdict)\n",
      "        \n",
      "        file('../json/'+country+repr(year)+'.json','w').write(json.dumps(fooddata)) \n",
      "     \n",
      "    #except:\n",
      "    #    KeyError        "
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "ename": "KeyError",
       "evalue": "'Fossil Fuels'",
       "output_type": "pyerr",
       "traceback": [
        "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m\n\u001b[1;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
        "\u001b[1;32m<ipython-input-571-5748d8e4a744>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m()\u001b[0m\n\u001b[0;32m    453\u001b[0m         \u001b[1;31m#create global input-output graph\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    454\u001b[0m         \u001b[0mfooddata\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;33m{\u001b[0m\u001b[1;34m\"nodes\"\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;33m{\u001b[0m\u001b[1;34m\"name\"\u001b[0m\u001b[1;33m:\u001b[0m \u001b[1;34m\"Input\"\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m{\u001b[0m\u001b[1;34m\"name\"\u001b[0m\u001b[1;33m:\u001b[0m \u001b[1;34m\"Food\"\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m{\u001b[0m\u001b[1;34m\"name\"\u001b[0m\u001b[1;33m:\u001b[0m \u001b[1;34m\"Output\"\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;34m\"links\"\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 455\u001b[1;33m         \u001b[0mfoodinput\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mlaborenergy\u001b[0m\u001b[1;33m+\u001b[0m\u001b[0mfertenergysum\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m\"Fertilizers\"\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m\"sum\"\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m+\u001b[0m\u001b[0mfuelenergysum\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m\"Fossil Fuels\"\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m\"sum\"\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m+\u001b[0m\u001b[0melectricityvalue\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    456\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    457\u001b[0m         \u001b[0mlinks_innerdict\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;33m{\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
        "\u001b[1;31mKeyError\u001b[0m: 'Fossil Fuels'"
       ]
      }
     ],
     "prompt_number": 571
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "try: \n",
      "    a=a[p]\n",
      "except:\n",
      "    KeyError"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [],
     "prompt_number": 569
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "popvalue=population[(population.Element=='Total economically active population in Agr')&(population.Year==1981)\\\n",
      "                            &(population.Country==country)].values[0][9]\n",
      "print popvalue"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "output_type": "stream",
       "stream": "stdout",
       "text": [
        "981259.0\n"
       ]
      }
     ],
     "prompt_number": 514
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "#energy[(energy.Element=='Consumption in Agriculture')&(balance.Year==2002)&(balance.Country==country)\\\n",
      "#                            &(energy.Unit=='Terajoule')&(energy.Item=='Electricty')]\n",
      "energy[(energy.Element=='Consumption in Agriculture')&(energy.Year==2002)&(energy.Country=='World + (Total)')]"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "html": [
        "<div style=\"max-height:1000px;max-width:1500px;overflow:auto;\">\n",
        "<table border=\"1\" class=\"dataframe\">\n",
        "  <thead>\n",
        "    <tr style=\"text-align: right;\">\n",
        "      <th></th>\n",
        "      <th>CountryCode</th>\n",
        "      <th>Country</th>\n",
        "      <th>ItemCode</th>\n",
        "      <th>Item</th>\n",
        "      <th>ElementGroup</th>\n",
        "      <th>ElementCode</th>\n",
        "      <th>Element</th>\n",
        "      <th>Year</th>\n",
        "      <th>Unit</th>\n",
        "      <th>Value</th>\n",
        "      <th>Flag</th>\n",
        "    </tr>\n",
        "  </thead>\n",
        "  <tbody>\n",
        "    <tr>\n",
        "      <th>346386</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6807</td>\n",
        "      <td>                                       Electricity</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td> 1312020.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>346387</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6807</td>\n",
        "      <td>                                       Electricity</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72182</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td> million kWh</td>\n",
        "      <td>  364449.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>346682</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6811</td>\n",
        "      <td>              Energy consumed in fishery + (Total)</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td>  383192.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>346986</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6808</td>\n",
        "      <td>                       Energy for power irrigation</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72182</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td> million kWh</td>\n",
        "      <td>  236328.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>346987</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6808</td>\n",
        "      <td>                       Energy for power irrigation</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td>  850780.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>347113</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6801</td>\n",
        "      <td>                                   Gas-diesel oils</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td> 3655110.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>347398</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6803</td>\n",
        "      <td>                      Gas-diesel oils in fisheries</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td>  213660.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>347680</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6800</td>\n",
        "      <td>                                          Gasoline</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td>  216053.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>347967</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6809</td>\n",
        "      <td>                                         Hard coal</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td>  561512.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>348254</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6805</td>\n",
        "      <td>                     Liquefied petroleum gas (LPG)</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td>  134066.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>348541</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6802</td>\n",
        "      <td>                       Natural gas (including LNG)</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td>  282638.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>348828</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6804</td>\n",
        "      <td>                                 Residual fuel oil</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td>  169532.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>349113</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6806</td>\n",
        "      <td>                    Residual fuel oil in fisheries</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td>   39336.7</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>349427</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6813</td>\n",
        "      <td>                            Total Energy + (Total)</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72182</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td> million kWh</td>\n",
        "      <td>  364449.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>349428</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6813</td>\n",
        "      <td>                            Total Energy + (Total)</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td> 6330930.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>349723</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 6810</td>\n",
        "      <td> Transport fuel consumed in agriculture (excl. ...</td>\n",
        "      <td> 7218</td>\n",
        "      <td> 72184</td>\n",
        "      <td> Consumption in Agriculture</td>\n",
        "      <td> 2002</td>\n",
        "      <td>   Terajoule</td>\n",
        "      <td> 3690460.0</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "  </tbody>\n",
        "</table>\n",
        "<p>16 rows \u00d7 11 columns</p>\n",
        "</div>"
       ],
       "metadata": {},
       "output_type": "pyout",
       "prompt_number": 314,
       "text": [
        "        CountryCode          Country  ItemCode  \\\n",
        "346386         5000  World + (Total)      6807   \n",
        "346387         5000  World + (Total)      6807   \n",
        "346682         5000  World + (Total)      6811   \n",
        "346986         5000  World + (Total)      6808   \n",
        "346987         5000  World + (Total)      6808   \n",
        "347113         5000  World + (Total)      6801   \n",
        "347398         5000  World + (Total)      6803   \n",
        "347680         5000  World + (Total)      6800   \n",
        "347967         5000  World + (Total)      6809   \n",
        "348254         5000  World + (Total)      6805   \n",
        "348541         5000  World + (Total)      6802   \n",
        "348828         5000  World + (Total)      6804   \n",
        "349113         5000  World + (Total)      6806   \n",
        "349427         5000  World + (Total)      6813   \n",
        "349428         5000  World + (Total)      6813   \n",
        "349723         5000  World + (Total)      6810   \n",
        "\n",
        "                                                     Item  ElementGroup  \\\n",
        "346386                                        Electricity          7218   \n",
        "346387                                        Electricity          7218   \n",
        "346682               Energy consumed in fishery + (Total)          7218   \n",
        "346986                        Energy for power irrigation          7218   \n",
        "346987                        Energy for power irrigation          7218   \n",
        "347113                                    Gas-diesel oils          7218   \n",
        "347398                       Gas-diesel oils in fisheries          7218   \n",
        "347680                                           Gasoline          7218   \n",
        "347967                                          Hard coal          7218   \n",
        "348254                      Liquefied petroleum gas (LPG)          7218   \n",
        "348541                        Natural gas (including LNG)          7218   \n",
        "348828                                  Residual fuel oil          7218   \n",
        "349113                     Residual fuel oil in fisheries          7218   \n",
        "349427                             Total Energy + (Total)          7218   \n",
        "349428                             Total Energy + (Total)          7218   \n",
        "349723  Transport fuel consumed in agriculture (excl. ...          7218   \n",
        "\n",
        "        ElementCode                     Element  Year         Unit      Value  \\\n",
        "346386        72184  Consumption in Agriculture  2002    Terajoule  1312020.0   \n",
        "346387        72182  Consumption in Agriculture  2002  million kWh   364449.0   \n",
        "346682        72184  Consumption in Agriculture  2002    Terajoule   383192.0   \n",
        "346986        72182  Consumption in Agriculture  2002  million kWh   236328.0   \n",
        "346987        72184  Consumption in Agriculture  2002    Terajoule   850780.0   \n",
        "347113        72184  Consumption in Agriculture  2002    Terajoule  3655110.0   \n",
        "347398        72184  Consumption in Agriculture  2002    Terajoule   213660.0   \n",
        "347680        72184  Consumption in Agriculture  2002    Terajoule   216053.0   \n",
        "347967        72184  Consumption in Agriculture  2002    Terajoule   561512.0   \n",
        "348254        72184  Consumption in Agriculture  2002    Terajoule   134066.0   \n",
        "348541        72184  Consumption in Agriculture  2002    Terajoule   282638.0   \n",
        "348828        72184  Consumption in Agriculture  2002    Terajoule   169532.0   \n",
        "349113        72184  Consumption in Agriculture  2002    Terajoule    39336.7   \n",
        "349427        72182  Consumption in Agriculture  2002  million kWh   364449.0   \n",
        "349428        72184  Consumption in Agriculture  2002    Terajoule  6330930.0   \n",
        "349723        72184  Consumption in Agriculture  2002    Terajoule  3690460.0   \n",
        "\n",
        "       Flag  \n",
        "346386    A  \n",
        "346387    A  \n",
        "346682    A  \n",
        "346986    A  \n",
        "346987    A  \n",
        "347113    A  \n",
        "347398    A  \n",
        "347680    A  \n",
        "347967    A  \n",
        "348254    A  \n",
        "348541    A  \n",
        "348828    A  \n",
        "349113    A  \n",
        "349427    A  \n",
        "349428    A  \n",
        "349723    A  \n",
        "\n",
        "[16 rows x 11 columns]"
       ]
      }
     ],
     "prompt_number": 314
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "'''                \n",
      "                            #add_to_json(energydata,2,fooditem,element,foodvalue,foodvalue,11,'[{\"l\":'+repr(fooditem)+',\"v\":'+repr(foodvalue)+'}]')\n",
      "                        if (element==\"Processing\"):\n",
      "                            processinggroup[2]+=energyvalue #save processing group\n",
      "                            processingprodgroup[2]+=foodvalue #save processing group\n",
      "                    \n",
      "                        for i in range(2): #sum fooitem values over different categories, defined above, currently 1-2\n",
      "                            if supergroup[i][fooditem] in energysum[i]:\n",
      "                                energysum[i][supergroup[i][fooditem]][\"data\"].append({\"l\":fooditem, \"v\":energyvalue})\n",
      "                                energysum[i][supergroup[i][fooditem]][\"sum\"]+=energyvalue\n",
      "                                prodsum[i][supergroup[i][fooditem]][\"data\"].append({\"l\":fooditem, \"v\":foodvalue})\n",
      "                                prodsum[i][supergroup[i][fooditem]][\"sum\"]+=foodvalue\n",
      "                            else:\n",
      "                                energysum[i][supergroup[i][fooditem]]={\"data\":[{\"l\":fooditem, \"v\":energyvalue}],\"sum\":energyvalue}\n",
      "                                prodsum[i][supergroup[i][fooditem]]={\"data\":[{\"l\":fooditem, \"v\":foodvalue}],\"sum\":foodvalue}\n",
      "                  \n",
      "            for i in range(2):\n",
      "                for j in energysum[i]:\n",
      "                    if (element==\"Seed\"):\n",
      "                        add_to_json(i,j,j,energysum[i][j][\"sum\"],prodsum[i][j][\"sum\"],energysum[i][j][\"sum\"]/(prodsum[i][j][\"sum\"]*(0.00116222222/100)),energysum[i][j][\"data\"]) #save categories, same manner for handling seed as above\n",
      "                    else:\n",
      "                        add_to_json(i,j,element,energysum[i][j][\"sum\"],prodsum[i][j][\"sum\"],energysum[i][j][\"sum\"]/(prodsum[i][j][\"sum\"]*(0.00116222222/100)),energysum[i][j][\"data\"])\n",
      "                    if (element==\"Processing\"):\n",
      "                        processinggroup[i]+=energysum[i][j][\"sum\"] #save processing group\n",
      "                        processingprodgroup[i]+=prodsum[i][j][\"sum\"] #save processing group\n",
      "                    if ((j=='Animal Products')\\\n",
      "                        |(j=='Aquatic Products')\\\n",
      "                        |(j=='Meat')\\\n",
      "                        |(j=='Animal Fats')\\\n",
      "                        |(j=='Fish, Seafood')\\\n",
      "                        |(j=='Aquatic Products, Other')\\\n",
      "                        |(j=='Offals')\\\n",
      "                        |(j=='Milk - Excluding Butter')\\\n",
      "                        |(j=='Eggs')):\n",
      "                            if j in feedgroup[i]:\n",
      "                                feedgroup[i][j]+=energysum[i][j][\"sum\"] #save feed group for the secondary food items\n",
      "                                feedprodgroup[i][j]+=prodsum[i][j][\"sum\"] #save feed group for the secondary food items\n",
      "                            else:\n",
      "                                feedgroup[i][j]=energysum[i][j][\"sum\"]\n",
      "                                feedprodgroup[i][j]=prodsum[i][j][\"sum\"]\n",
      "            \n",
      "        for i in range(3): #n\n",
      "            for j in feedgroup[i]:\n",
      "                add_to_json(i,\"Feed\",j,feedgroup[i][j],feedprodgroup[i][j],feedgroup[i][j]/(feedprodgroup[i][j]*(0.00116222222/100)),'[{\"l\":'+repr(\"Feed\")+',\"v\":'+repr(feedgroup[i][j])+'}]')\n",
      "        \n",
      "        for i in range(3): #n\n",
      "            add_to_json(i,\"Processing\",\"Food\",processinggroup[i],processingprodgroup[i],processinggroup[i]/(processingprodgroup[i]*(0.00116222222/100)),'[{\"l\":'+repr(\"Processing\")+',\"v\":'+repr(processinggroup[i])+'}]')\n",
      "'''"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "metadata": {},
       "output_type": "pyout",
       "prompt_number": 114,
       "text": [
        "'                \\n                            #add_to_json(energydata,2,fooditem,element,foodvalue,foodvalue,11,\\'[{\"l\":\\'+repr(fooditem)+\\',\"v\":\\'+repr(foodvalue)+\\'}]\\')\\n                        if (element==\"Processing\"):\\n                            processinggroup[2]+=energyvalue #save processing group\\n                            processingprodgroup[2]+=foodvalue #save processing group\\n                    \\n                        for i in range(2): #sum fooitem values over different categories, defined above, currently 1-2\\n                            if supergroup[i][fooditem] in energysum[i]:\\n                                energysum[i][supergroup[i][fooditem]][\"data\"].append({\"l\":fooditem, \"v\":energyvalue})\\n                                energysum[i][supergroup[i][fooditem]][\"sum\"]+=energyvalue\\n                                prodsum[i][supergroup[i][fooditem]][\"data\"].append({\"l\":fooditem, \"v\":foodvalue})\\n                                prodsum[i][supergroup[i][fooditem]][\"sum\"]+=foodvalue\\n                            else:\\n                                energysum[i][supergroup[i][fooditem]]={\"data\":[{\"l\":fooditem, \"v\":energyvalue}],\"sum\":energyvalue}\\n                                prodsum[i][supergroup[i][fooditem]]={\"data\":[{\"l\":fooditem, \"v\":foodvalue}],\"sum\":foodvalue}\\n                  \\n            for i in range(2):\\n                for j in energysum[i]:\\n                    if (element==\"Seed\"):\\n                        add_to_json(i,j,j,energysum[i][j][\"sum\"],prodsum[i][j][\"sum\"],energysum[i][j][\"sum\"]/(prodsum[i][j][\"sum\"]*(0.00116222222/100)),energysum[i][j][\"data\"]) #save categories, same manner for handling seed as above\\n                    else:\\n                        add_to_json(i,j,element,energysum[i][j][\"sum\"],prodsum[i][j][\"sum\"],energysum[i][j][\"sum\"]/(prodsum[i][j][\"sum\"]*(0.00116222222/100)),energysum[i][j][\"data\"])\\n                    if (element==\"Processing\"):\\n                        processinggroup[i]+=energysum[i][j][\"sum\"] #save processing group\\n                        processingprodgroup[i]+=prodsum[i][j][\"sum\"] #save processing group\\n                    if ((j==\\'Animal Products\\')                        |(j==\\'Aquatic Products\\')                        |(j==\\'Meat\\')                        |(j==\\'Animal Fats\\')                        |(j==\\'Fish, Seafood\\')                        |(j==\\'Aquatic Products, Other\\')                        |(j==\\'Offals\\')                        |(j==\\'Milk - Excluding Butter\\')                        |(j==\\'Eggs\\')):\\n                            if j in feedgroup[i]:\\n                                feedgroup[i][j]+=energysum[i][j][\"sum\"] #save feed group for the secondary food items\\n                                feedprodgroup[i][j]+=prodsum[i][j][\"sum\"] #save feed group for the secondary food items\\n                            else:\\n                                feedgroup[i][j]=energysum[i][j][\"sum\"]\\n                                feedprodgroup[i][j]=prodsum[i][j][\"sum\"]\\n            \\n        for i in range(3): #n\\n            for j in feedgroup[i]:\\n                add_to_json(i,\"Feed\",j,feedgroup[i][j],feedprodgroup[i][j],feedgroup[i][j]/(feedprodgroup[i][j]*(0.00116222222/100)),\\'[{\"l\":\\'+repr(\"Feed\")+\\',\"v\":\\'+repr(feedgroup[i][j])+\\'}]\\')\\n        \\n        for i in range(3): #n\\n            add_to_json(i,\"Processing\",\"Food\",processinggroup[i],processingprodgroup[i],processinggroup[i]/(processingprodgroup[i]*(0.00116222222/100)),\\'[{\"l\":\\'+repr(\"Processing\")+\\',\"v\":\\'+repr(processinggroup[i])+\\'}]\\')\\n'"
       ]
      }
     ],
     "prompt_number": 114
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "balance[(balance.Element==\"Food supply\")&(balance.Year==year)&(balance.Country==country)&(balance.Item.str.contains(\"Aquatic\"))]"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "html": [
        "<div style=\"max-height:1000px;max-width:1500px;overflow:auto;\">\n",
        "<table border=\"1\" class=\"dataframe\">\n",
        "  <thead>\n",
        "    <tr style=\"text-align: right;\">\n",
        "      <th></th>\n",
        "      <th>CountryCode</th>\n",
        "      <th>Country</th>\n",
        "      <th>ItemCode</th>\n",
        "      <th>Item</th>\n",
        "      <th>ElementGroup</th>\n",
        "      <th>ElementCode</th>\n",
        "      <th>Element</th>\n",
        "      <th>Year</th>\n",
        "      <th>Unit</th>\n",
        "      <th>Value</th>\n",
        "      <th>Flag</th>\n",
        "    </tr>\n",
        "  </thead>\n",
        "  <tbody>\n",
        "    <tr>\n",
        "      <th>4823822</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2769</td>\n",
        "      <td>           Aquatic Animals, Others</td>\n",
        "      <td> 664</td>\n",
        "      <td> 664</td>\n",
        "      <td> Food supply</td>\n",
        "      <td> 1971</td>\n",
        "      <td> kcal/capita/day</td>\n",
        "      <td> 0</td>\n",
        "      <td> Fc</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4824587</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2775</td>\n",
        "      <td>                    Aquatic Plants</td>\n",
        "      <td> 664</td>\n",
        "      <td> 664</td>\n",
        "      <td> Food supply</td>\n",
        "      <td> 1971</td>\n",
        "      <td> kcal/capita/day</td>\n",
        "      <td> 0</td>\n",
        "      <td> Fc</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4825352</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2961</td>\n",
        "      <td> Aquatic Products, Other + (Total)</td>\n",
        "      <td> 664</td>\n",
        "      <td> 664</td>\n",
        "      <td> Food supply</td>\n",
        "      <td> 1971</td>\n",
        "      <td> kcal/capita/day</td>\n",
        "      <td> 0</td>\n",
        "      <td> Fc</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4859757</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2768</td>\n",
        "      <td>             Meat, Aquatic Mammals</td>\n",
        "      <td> 664</td>\n",
        "      <td> 664</td>\n",
        "      <td> Food supply</td>\n",
        "      <td> 1971</td>\n",
        "      <td> kcal/capita/day</td>\n",
        "      <td> 0</td>\n",
        "      <td> Fc</td>\n",
        "    </tr>\n",
        "  </tbody>\n",
        "</table>\n",
        "<p>4 rows \u00d7 11 columns</p>\n",
        "</div>"
       ],
       "metadata": {},
       "output_type": "pyout",
       "prompt_number": 432,
       "text": [
        "         CountryCode          Country  ItemCode  \\\n",
        "4823822         5000  World + (Total)      2769   \n",
        "4824587         5000  World + (Total)      2775   \n",
        "4825352         5000  World + (Total)      2961   \n",
        "4859757         5000  World + (Total)      2768   \n",
        "\n",
        "                                      Item  ElementGroup  ElementCode  \\\n",
        "4823822            Aquatic Animals, Others           664          664   \n",
        "4824587                     Aquatic Plants           664          664   \n",
        "4825352  Aquatic Products, Other + (Total)           664          664   \n",
        "4859757              Meat, Aquatic Mammals           664          664   \n",
        "\n",
        "             Element  Year             Unit  Value Flag  \n",
        "4823822  Food supply  1971  kcal/capita/day      0   Fc  \n",
        "4824587  Food supply  1971  kcal/capita/day      0   Fc  \n",
        "4825352  Food supply  1971  kcal/capita/day      0   Fc  \n",
        "4859757  Food supply  1971  kcal/capita/day      0   Fc  \n",
        "\n",
        "[4 rows x 11 columns]"
       ]
      }
     ],
     "prompt_number": 432
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "myprod={}\n",
      "mybal={}\n",
      "elements=['Production','Area','Yield','Seed']\n",
      "#for country in set(data.Country.values):\n",
      "country='World + (Total)'    \n",
      "if True:\n",
      "    #for year in set(data[data.Country==country].Year.values):\n",
      "    year = 1962\n",
      "    if True:    \n",
      "         for element in elements:\n",
      "            for i in prod[(prod.Element==element)&(prod.Year==year)&(prod.Country==country)].values:\n",
      "                foodvalue=i[9] #choose column in which food item values are stored, might need to change it\n",
      "                if (~np.isnan(foodvalue)&(foodvalue!=0)):\n",
      "                    fooditem=i[3]  #choose column in which food item names are stored, might need to change it\n",
      "                    mydict[fooditem]=foodvalue\n",
      "            for i in balance[(balance.Element==element)&(balance.Year==year)&(balance.Country==country)&~(data.Item.str.contains('Total'))].values:\n",
      "                foodvalue=i[9] #choose column in which food item values are stored, might need to change it\n",
      "                if (~np.isnan(foodvalue)&(foodvalue!=0)):\n",
      "                    fooditem=i[3]  #choose column in which food item names are stored, might need to change it\n",
      "                    mybal[fooditem]=foodvalue\n",
      "                    \n",
      "for i in mybal:\n",
      "    if (i in mydict):\n",
      "        print (i,mydict[i]/1000,mybal[i])"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "output_type": "stream",
       "stream": "stdout",
       "text": [
        "('Plantains', 53.73276, 13002.0)\n",
        "('Cloves', 2.59975, 19.0)\n",
        "('Sorghum', 973.22829, 964.0)\n",
        "('Wheat', 26366.96166, 25990.0)\n",
        "('Dates', 75.90092999999999, 1329.0)\n",
        "('Oats', 4440.853139999999, 4441.0)\n",
        "('Maize', 6595.107690000001, 6544.0)\n",
        "('Barley', 8912.04352, 8762.0)\n",
        "('Tomatoes', 169.75989, 28954.0)\n",
        "('Grapes', 56.958589999999994, 53173.0)\n",
        "('Cottonseed', 1310.77741, 1299.0)\n",
        "('Pineapples', 108.14235000000001, 3671.0)\n",
        "('Tea', 7.155399999999999, 1272.0)\n",
        "('Olives', 20.19679, 5402.0)\n",
        "('Rye', 4642.103389999999, 4642.0)\n",
        "('Yams', 573.1385, 517.0)\n",
        "('Potatoes', 45216.9196, 45194.0)\n",
        "('Apples', 118.73937, 21657.0)\n",
        "('Bananas', 106.63515, 20557.0)\n",
        "('Millet', 888.98725, 885.0)\n",
        "('Cassava', 0.067, 65563.0)\n"
       ]
      }
     ],
     "prompt_number": 71
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "balance[(balance.Element==element)&(balance.Year==year)&(balance.Country==country)\\\n",
      "                          &(((2511<=balance.ItemCode)&(balance.ItemCode<=2775))\\\n",
      "                          |(balance.ItemCode==2805)\\\n",
      "                          |(balance.ItemCode==2912)\\\n",
      "                          |(balance.ItemCode==2945)\\\n",
      "                          |(balance.ItemCode==2948)\\\n",
      "                          |(balance.ItemCode==2949))]"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "html": [
        "<div style=\"max-height:1000px;max-width:1500px;overflow:auto;\">\n",
        "<table border=\"1\" class=\"dataframe\">\n",
        "  <thead>\n",
        "    <tr style=\"text-align: right;\">\n",
        "      <th></th>\n",
        "      <th>CountryCode</th>\n",
        "      <th>Country</th>\n",
        "      <th>ItemCode</th>\n",
        "      <th>Item</th>\n",
        "      <th>ElementGroup</th>\n",
        "      <th>ElementCode</th>\n",
        "      <th>Element</th>\n",
        "      <th>Year</th>\n",
        "      <th>Unit</th>\n",
        "      <th>Value</th>\n",
        "      <th>Flag</th>\n",
        "    </tr>\n",
        "  </thead>\n",
        "  <tbody>\n",
        "    <tr>\n",
        "      <th>4820140</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2659</td>\n",
        "      <td>                 Alcohol, Non-Food</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4822588</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2617</td>\n",
        "      <td>               Apples and products</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    117</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4823353</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2769</td>\n",
        "      <td>           Aquatic Animals, Others</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4824118</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2775</td>\n",
        "      <td>                    Aquatic Plants</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    129</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4825648</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2615</td>\n",
        "      <td>                           Bananas</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    409</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4826413</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2513</td>\n",
        "      <td>               Barley and products</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>  43786</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4827178</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2546</td>\n",
        "      <td>                             Beans</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    133</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4827943</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2656</td>\n",
        "      <td>                              Beer</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4828708</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2658</td>\n",
        "      <td>              Beverages, Alcoholic</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4829473</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2657</td>\n",
        "      <td>              Beverages, Fermented</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4830238</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2731</td>\n",
        "      <td>                       Bovine Meat</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4831003</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2740</td>\n",
        "      <td>                      Butter, Ghee</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      1</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4831768</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2532</td>\n",
        "      <td>              Cassava and products</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>  16302</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4832533</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2766</td>\n",
        "      <td>                       Cephalopods</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      6</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4834063</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2520</td>\n",
        "      <td>                    Cereals, Other</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>   5457</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4834828</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2614</td>\n",
        "      <td>                     Citrus, Other</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4835593</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2642</td>\n",
        "      <td>                            Cloves</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4836358</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2633</td>\n",
        "      <td>          Cocoa Beans and products</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4837123</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2578</td>\n",
        "      <td>                       Coconut Oil</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4837888</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2560</td>\n",
        "      <td>             Coconuts - Incl Copra</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>     15</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4838653</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2630</td>\n",
        "      <td>               Coffee and products</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4839418</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2559</td>\n",
        "      <td>                        Cottonseed</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>   1609</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4840183</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2575</td>\n",
        "      <td>                    Cottonseed Oil</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4840948</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2743</td>\n",
        "      <td>                             Cream</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4841713</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2765</td>\n",
        "      <td>                       Crustaceans</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>     24</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4842478</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2619</td>\n",
        "      <td>                             Dates</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>     24</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4843243</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2762</td>\n",
        "      <td>                     Demersal Fish</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    788</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4844008</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2744</td>\n",
        "      <td>                              Eggs</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      4</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4844773</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2949</td>\n",
        "      <td>                    Eggs + (Total)</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      4</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4845538</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2737</td>\n",
        "      <td>                Fats, Animals, Raw</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    338</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4848598</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2761</td>\n",
        "      <td>                   Freshwater Fish</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>     10</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4850128</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2625</td>\n",
        "      <td>                     Fruits, Other</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>     66</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4851046</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2613</td>\n",
        "      <td>           Grapefruit and products</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4851811</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2620</td>\n",
        "      <td>   Grapes and products (excl wine)</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4852576</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2572</td>\n",
        "      <td>                     Groundnut Oil</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4853341</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2556</td>\n",
        "      <td>           Groundnuts (Shelled Eq)</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>     10</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4854106</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2745</td>\n",
        "      <td>                             Honey</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4855463</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2612</td>\n",
        "      <td>        Lemons, Limes and products</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4856228</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2514</td>\n",
        "      <td>                Maize and products</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td> 147255</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4856993</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2582</td>\n",
        "      <td>                    Maize Germ Oil</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4857758</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2764</td>\n",
        "      <td>                Marine Fish, Other</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    139</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4859288</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2768</td>\n",
        "      <td>             Meat, Aquatic Mammals</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4860053</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2735</td>\n",
        "      <td>                       Meat, Other</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>     36</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4861532</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2948</td>\n",
        "      <td> Milk - Excluding Butter + (Total)</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>  92128</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4862297</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2517</td>\n",
        "      <td>               Millet and products</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>   1678</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4863368</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2767</td>\n",
        "      <td>                   Molluscs, Other</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>     57</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4864133</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2732</td>\n",
        "      <td>                Mutton &amp; Goat Meat</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4865612</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2516</td>\n",
        "      <td>                              Oats</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>  38763</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4866377</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2945</td>\n",
        "      <td>                  Offals + (Total)</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    558</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4867142</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2736</td>\n",
        "      <td>                    Offals, Edible</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    558</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4868621</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2586</td>\n",
        "      <td>               Oilcrops Oil, Other</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4869386</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2570</td>\n",
        "      <td>                   Oilcrops, Other</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>     85</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4870151</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2580</td>\n",
        "      <td>                         Olive Oil</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4870916</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2563</td>\n",
        "      <td>      Olives (including preserved)</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>    NaN</td>\n",
        "      <td> NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4871681</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2602</td>\n",
        "      <td>                            Onions</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4872446</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2611</td>\n",
        "      <td>               Oranges, Mandarines</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4873211</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2562</td>\n",
        "      <td>                      Palm kernels</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4873976</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2577</td>\n",
        "      <td>                          Palm Oil</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      0</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4874741</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2576</td>\n",
        "      <td>                    Palmkernel Oil</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>      3</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4875506</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2547</td>\n",
        "      <td>                              Peas</td>\n",
        "      <td> 101</td>\n",
        "      <td> 5521</td>\n",
        "      <td> Feed</td>\n",
        "      <td> 1961</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td>   1002</td>\n",
        "      <td>   A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th></th>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "    </tr>\n",
        "  </tbody>\n",
        "</table>\n",
        "<p>96 rows \u00d7 11 columns</p>\n",
        "</div>"
       ],
       "metadata": {},
       "output_type": "pyout",
       "prompt_number": 163,
       "text": [
        "         CountryCode          Country  ItemCode  \\\n",
        "4820140         5000  World + (Total)      2659   \n",
        "4822588         5000  World + (Total)      2617   \n",
        "4823353         5000  World + (Total)      2769   \n",
        "4824118         5000  World + (Total)      2775   \n",
        "4825648         5000  World + (Total)      2615   \n",
        "4826413         5000  World + (Total)      2513   \n",
        "4827178         5000  World + (Total)      2546   \n",
        "4827943         5000  World + (Total)      2656   \n",
        "4828708         5000  World + (Total)      2658   \n",
        "4829473         5000  World + (Total)      2657   \n",
        "4830238         5000  World + (Total)      2731   \n",
        "4831003         5000  World + (Total)      2740   \n",
        "4831768         5000  World + (Total)      2532   \n",
        "4832533         5000  World + (Total)      2766   \n",
        "4834063         5000  World + (Total)      2520   \n",
        "4834828         5000  World + (Total)      2614   \n",
        "4835593         5000  World + (Total)      2642   \n",
        "4836358         5000  World + (Total)      2633   \n",
        "4837123         5000  World + (Total)      2578   \n",
        "4837888         5000  World + (Total)      2560   \n",
        "4838653         5000  World + (Total)      2630   \n",
        "4839418         5000  World + (Total)      2559   \n",
        "4840183         5000  World + (Total)      2575   \n",
        "4840948         5000  World + (Total)      2743   \n",
        "4841713         5000  World + (Total)      2765   \n",
        "4842478         5000  World + (Total)      2619   \n",
        "4843243         5000  World + (Total)      2762   \n",
        "4844008         5000  World + (Total)      2744   \n",
        "4844773         5000  World + (Total)      2949   \n",
        "4845538         5000  World + (Total)      2737   \n",
        "4848598         5000  World + (Total)      2761   \n",
        "4850128         5000  World + (Total)      2625   \n",
        "4851046         5000  World + (Total)      2613   \n",
        "4851811         5000  World + (Total)      2620   \n",
        "4852576         5000  World + (Total)      2572   \n",
        "4853341         5000  World + (Total)      2556   \n",
        "4854106         5000  World + (Total)      2745   \n",
        "4855463         5000  World + (Total)      2612   \n",
        "4856228         5000  World + (Total)      2514   \n",
        "4856993         5000  World + (Total)      2582   \n",
        "4857758         5000  World + (Total)      2764   \n",
        "4859288         5000  World + (Total)      2768   \n",
        "4860053         5000  World + (Total)      2735   \n",
        "4861532         5000  World + (Total)      2948   \n",
        "4862297         5000  World + (Total)      2517   \n",
        "4863368         5000  World + (Total)      2767   \n",
        "4864133         5000  World + (Total)      2732   \n",
        "4865612         5000  World + (Total)      2516   \n",
        "4866377         5000  World + (Total)      2945   \n",
        "4867142         5000  World + (Total)      2736   \n",
        "4868621         5000  World + (Total)      2586   \n",
        "4869386         5000  World + (Total)      2570   \n",
        "4870151         5000  World + (Total)      2580   \n",
        "4870916         5000  World + (Total)      2563   \n",
        "4871681         5000  World + (Total)      2602   \n",
        "4872446         5000  World + (Total)      2611   \n",
        "4873211         5000  World + (Total)      2562   \n",
        "4873976         5000  World + (Total)      2577   \n",
        "4874741         5000  World + (Total)      2576   \n",
        "4875506         5000  World + (Total)      2547   \n",
        "                 ...              ...       ...   \n",
        "\n",
        "                                      Item  ElementGroup  ElementCode Element  \\\n",
        "4820140                  Alcohol, Non-Food           101         5521    Feed   \n",
        "4822588                Apples and products           101         5521    Feed   \n",
        "4823353            Aquatic Animals, Others           101         5521    Feed   \n",
        "4824118                     Aquatic Plants           101         5521    Feed   \n",
        "4825648                            Bananas           101         5521    Feed   \n",
        "4826413                Barley and products           101         5521    Feed   \n",
        "4827178                              Beans           101         5521    Feed   \n",
        "4827943                               Beer           101         5521    Feed   \n",
        "4828708               Beverages, Alcoholic           101         5521    Feed   \n",
        "4829473               Beverages, Fermented           101         5521    Feed   \n",
        "4830238                        Bovine Meat           101         5521    Feed   \n",
        "4831003                       Butter, Ghee           101         5521    Feed   \n",
        "4831768               Cassava and products           101         5521    Feed   \n",
        "4832533                        Cephalopods           101         5521    Feed   \n",
        "4834063                     Cereals, Other           101         5521    Feed   \n",
        "4834828                      Citrus, Other           101         5521    Feed   \n",
        "4835593                             Cloves           101         5521    Feed   \n",
        "4836358           Cocoa Beans and products           101         5521    Feed   \n",
        "4837123                        Coconut Oil           101         5521    Feed   \n",
        "4837888              Coconuts - Incl Copra           101         5521    Feed   \n",
        "4838653                Coffee and products           101         5521    Feed   \n",
        "4839418                         Cottonseed           101         5521    Feed   \n",
        "4840183                     Cottonseed Oil           101         5521    Feed   \n",
        "4840948                              Cream           101         5521    Feed   \n",
        "4841713                        Crustaceans           101         5521    Feed   \n",
        "4842478                              Dates           101         5521    Feed   \n",
        "4843243                      Demersal Fish           101         5521    Feed   \n",
        "4844008                               Eggs           101         5521    Feed   \n",
        "4844773                     Eggs + (Total)           101         5521    Feed   \n",
        "4845538                 Fats, Animals, Raw           101         5521    Feed   \n",
        "4848598                    Freshwater Fish           101         5521    Feed   \n",
        "4850128                      Fruits, Other           101         5521    Feed   \n",
        "4851046            Grapefruit and products           101         5521    Feed   \n",
        "4851811    Grapes and products (excl wine)           101         5521    Feed   \n",
        "4852576                      Groundnut Oil           101         5521    Feed   \n",
        "4853341            Groundnuts (Shelled Eq)           101         5521    Feed   \n",
        "4854106                              Honey           101         5521    Feed   \n",
        "4855463         Lemons, Limes and products           101         5521    Feed   \n",
        "4856228                 Maize and products           101         5521    Feed   \n",
        "4856993                     Maize Germ Oil           101         5521    Feed   \n",
        "4857758                 Marine Fish, Other           101         5521    Feed   \n",
        "4859288              Meat, Aquatic Mammals           101         5521    Feed   \n",
        "4860053                        Meat, Other           101         5521    Feed   \n",
        "4861532  Milk - Excluding Butter + (Total)           101         5521    Feed   \n",
        "4862297                Millet and products           101         5521    Feed   \n",
        "4863368                    Molluscs, Other           101         5521    Feed   \n",
        "4864133                 Mutton & Goat Meat           101         5521    Feed   \n",
        "4865612                               Oats           101         5521    Feed   \n",
        "4866377                   Offals + (Total)           101         5521    Feed   \n",
        "4867142                     Offals, Edible           101         5521    Feed   \n",
        "4868621                Oilcrops Oil, Other           101         5521    Feed   \n",
        "4869386                    Oilcrops, Other           101         5521    Feed   \n",
        "4870151                          Olive Oil           101         5521    Feed   \n",
        "4870916       Olives (including preserved)           101         5521    Feed   \n",
        "4871681                             Onions           101         5521    Feed   \n",
        "4872446                Oranges, Mandarines           101         5521    Feed   \n",
        "4873211                       Palm kernels           101         5521    Feed   \n",
        "4873976                           Palm Oil           101         5521    Feed   \n",
        "4874741                     Palmkernel Oil           101         5521    Feed   \n",
        "4875506                               Peas           101         5521    Feed   \n",
        "                                       ...           ...          ...     ...   \n",
        "\n",
        "         Year         Unit   Value Flag  \n",
        "4820140  1961  1000 tonnes     NaN  NaN  \n",
        "4822588  1961  1000 tonnes     117    A  \n",
        "4823353  1961  1000 tonnes     NaN  NaN  \n",
        "4824118  1961  1000 tonnes     129    A  \n",
        "4825648  1961  1000 tonnes     409    A  \n",
        "4826413  1961  1000 tonnes   43786    A  \n",
        "4827178  1961  1000 tonnes     133    A  \n",
        "4827943  1961  1000 tonnes     NaN  NaN  \n",
        "4828708  1961  1000 tonnes     NaN  NaN  \n",
        "4829473  1961  1000 tonnes     NaN  NaN  \n",
        "4830238  1961  1000 tonnes     NaN  NaN  \n",
        "4831003  1961  1000 tonnes       1    A  \n",
        "4831768  1961  1000 tonnes   16302    A  \n",
        "4832533  1961  1000 tonnes       6    A  \n",
        "4834063  1961  1000 tonnes    5457    A  \n",
        "4834828  1961  1000 tonnes     NaN  NaN  \n",
        "4835593  1961  1000 tonnes     NaN  NaN  \n",
        "4836358  1961  1000 tonnes     NaN  NaN  \n",
        "4837123  1961  1000 tonnes       0    A  \n",
        "4837888  1961  1000 tonnes      15    A  \n",
        "4838653  1961  1000 tonnes     NaN  NaN  \n",
        "4839418  1961  1000 tonnes    1609    A  \n",
        "4840183  1961  1000 tonnes       0    A  \n",
        "4840948  1961  1000 tonnes     NaN  NaN  \n",
        "4841713  1961  1000 tonnes      24    A  \n",
        "4842478  1961  1000 tonnes      24    A  \n",
        "4843243  1961  1000 tonnes     788    A  \n",
        "4844008  1961  1000 tonnes       4    A  \n",
        "4844773  1961  1000 tonnes       4    A  \n",
        "4845538  1961  1000 tonnes     338    A  \n",
        "4848598  1961  1000 tonnes      10    A  \n",
        "4850128  1961  1000 tonnes      66    A  \n",
        "4851046  1961  1000 tonnes       0    A  \n",
        "4851811  1961  1000 tonnes       0    A  \n",
        "4852576  1961  1000 tonnes       0    A  \n",
        "4853341  1961  1000 tonnes      10    A  \n",
        "4854106  1961  1000 tonnes       0    A  \n",
        "4855463  1961  1000 tonnes     NaN  NaN  \n",
        "4856228  1961  1000 tonnes  147255    A  \n",
        "4856993  1961  1000 tonnes     NaN  NaN  \n",
        "4857758  1961  1000 tonnes     139    A  \n",
        "4859288  1961  1000 tonnes     NaN  NaN  \n",
        "4860053  1961  1000 tonnes      36    A  \n",
        "4861532  1961  1000 tonnes   92128    A  \n",
        "4862297  1961  1000 tonnes    1678    A  \n",
        "4863368  1961  1000 tonnes      57    A  \n",
        "4864133  1961  1000 tonnes       0    A  \n",
        "4865612  1961  1000 tonnes   38763    A  \n",
        "4866377  1961  1000 tonnes     558    A  \n",
        "4867142  1961  1000 tonnes     558    A  \n",
        "4868621  1961  1000 tonnes       0    A  \n",
        "4869386  1961  1000 tonnes      85    A  \n",
        "4870151  1961  1000 tonnes       0    A  \n",
        "4870916  1961  1000 tonnes     NaN  NaN  \n",
        "4871681  1961  1000 tonnes       0    A  \n",
        "4872446  1961  1000 tonnes       0    A  \n",
        "4873211  1961  1000 tonnes       0    A  \n",
        "4873976  1961  1000 tonnes       0    A  \n",
        "4874741  1961  1000 tonnes       3    A  \n",
        "4875506  1961  1000 tonnes    1002    A  \n",
        "          ...          ...     ...  ...  \n",
        "\n",
        "[96 rows x 11 columns]"
       ]
      }
     ],
     "prompt_number": 163
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "a='Feed'\n",
      "b=0\n",
      "~np.isnan(a)"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "ename": "TypeError",
       "evalue": "Not implemented for this type",
       "output_type": "pyerr",
       "traceback": [
        "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m\n\u001b[1;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
        "\u001b[1;32m<ipython-input-29-11cf204d31e8>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m()\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[0ma\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m'Feed'\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[0mb\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 3\u001b[1;33m \u001b[1;33m~\u001b[0m\u001b[0mnp\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0misnan\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0ma\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
        "\u001b[1;31mTypeError\u001b[0m: Not implemented for this type"
       ]
      }
     ],
     "prompt_number": 29
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "data[(data.Element=='Food supply quantity')&(data.Year==1961)&(data.Country=='World + (Total)')&(data.Unit==\"g\"\"/capita\"\"/day\")&~(data.Item.str.contains('Total'))].head()"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "html": [
        "<div style=\"max-height:1000px;max-width:1500px;overflow:auto;\">\n",
        "<table border=\"1\" class=\"dataframe\">\n",
        "  <thead>\n",
        "    <tr style=\"text-align: right;\">\n",
        "      <th></th>\n",
        "      <th>CountryCode</th>\n",
        "      <th>Country</th>\n",
        "      <th>ItemCode</th>\n",
        "      <th>Item</th>\n",
        "      <th>ElementGroup</th>\n",
        "      <th>ElementCode</th>\n",
        "      <th>Element</th>\n",
        "      <th>Year</th>\n",
        "      <th>Unit</th>\n",
        "      <th>Value</th>\n",
        "      <th>Flag</th>\n",
        "    </tr>\n",
        "  </thead>\n",
        "  <tbody>\n",
        "    <tr>\n",
        "      <th>1077829</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2769</td>\n",
        "      <td> Aquatic Animals, Others</td>\n",
        "      <td> 646</td>\n",
        "      <td> 646</td>\n",
        "      <td> Food supply quantity</td>\n",
        "      <td> 1961</td>\n",
        "      <td> g/capita/day</td>\n",
        "      <td>  0</td>\n",
        "      <td> Fc</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>1078123</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2775</td>\n",
        "      <td>          Aquatic Plants</td>\n",
        "      <td> 646</td>\n",
        "      <td> 646</td>\n",
        "      <td> Food supply quantity</td>\n",
        "      <td> 1961</td>\n",
        "      <td> g/capita/day</td>\n",
        "      <td>  0</td>\n",
        "      <td> Fc</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>1078711</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2731</td>\n",
        "      <td>             Bovine Meat</td>\n",
        "      <td> 646</td>\n",
        "      <td> 646</td>\n",
        "      <td> Food supply quantity</td>\n",
        "      <td> 1961</td>\n",
        "      <td> g/capita/day</td>\n",
        "      <td> 26</td>\n",
        "      <td> Fc</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>1079005</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2740</td>\n",
        "      <td>            Butter, Ghee</td>\n",
        "      <td> 646</td>\n",
        "      <td> 646</td>\n",
        "      <td> Food supply quantity</td>\n",
        "      <td> 1961</td>\n",
        "      <td> g/capita/day</td>\n",
        "      <td>  5</td>\n",
        "      <td> Fc</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>1079299</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2766</td>\n",
        "      <td>             Cephalopods</td>\n",
        "      <td> 646</td>\n",
        "      <td> 646</td>\n",
        "      <td> Food supply quantity</td>\n",
        "      <td> 1961</td>\n",
        "      <td> g/capita/day</td>\n",
        "      <td>  1</td>\n",
        "      <td> Fc</td>\n",
        "    </tr>\n",
        "  </tbody>\n",
        "</table>\n",
        "<p>5 rows \u00d7 11 columns</p>\n",
        "</div>"
       ],
       "metadata": {},
       "output_type": "pyout",
       "prompt_number": 105,
       "text": [
        "         CountryCode          Country  ItemCode                     Item  \\\n",
        "1077829         5000  World + (Total)      2769  Aquatic Animals, Others   \n",
        "1078123         5000  World + (Total)      2775           Aquatic Plants   \n",
        "1078711         5000  World + (Total)      2731              Bovine Meat   \n",
        "1079005         5000  World + (Total)      2740             Butter, Ghee   \n",
        "1079299         5000  World + (Total)      2766              Cephalopods   \n",
        "\n",
        "         ElementGroup  ElementCode               Element  Year          Unit  \\\n",
        "1077829           646          646  Food supply quantity  1961  g/capita/day   \n",
        "1078123           646          646  Food supply quantity  1961  g/capita/day   \n",
        "1078711           646          646  Food supply quantity  1961  g/capita/day   \n",
        "1079005           646          646  Food supply quantity  1961  g/capita/day   \n",
        "1079299           646          646  Food supply quantity  1961  g/capita/day   \n",
        "\n",
        "         Value Flag  \n",
        "1077829      0   Fc  \n",
        "1078123      0   Fc  \n",
        "1078711     26   Fc  \n",
        "1079005      5   Fc  \n",
        "1079299      1   Fc  \n",
        "\n",
        "[5 rows x 11 columns]"
       ]
      }
     ],
     "prompt_number": 105
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "balance[(balance.Element==element)&(balance.Year==year)&(balance.Country==country)&(balance.Item.str.contains(\"Offals\"))]\n",
      "#energyvalue=foodvalue*cal*0.00116222222/100\n",
      "                        #TWh = 1000tons * kcal/100g # 10^9) /100g * 0.00116222222 kwh/kcal *10^-9 TWh/kWh\n",
      "                "
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "html": [
        "<div style=\"max-height:1000px;max-width:1500px;overflow:auto;\">\n",
        "<table border=\"1\" class=\"dataframe\">\n",
        "  <thead>\n",
        "    <tr style=\"text-align: right;\">\n",
        "      <th></th>\n",
        "      <th>CountryCode</th>\n",
        "      <th>Country</th>\n",
        "      <th>ItemCode</th>\n",
        "      <th>Item</th>\n",
        "      <th>ElementGroup</th>\n",
        "      <th>ElementCode</th>\n",
        "      <th>Element</th>\n",
        "      <th>Year</th>\n",
        "      <th>Unit</th>\n",
        "      <th>Value</th>\n",
        "      <th>Flag</th>\n",
        "    </tr>\n",
        "  </thead>\n",
        "  <tbody>\n",
        "    <tr>\n",
        "      <th>4866489</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2945</td>\n",
        "      <td> Offals + (Total)</td>\n",
        "      <td> 121</td>\n",
        "      <td> 5123</td>\n",
        "      <td> Waste</td>\n",
        "      <td> 1971</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td> 79</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4867203</th>\n",
        "      <td> 5000</td>\n",
        "      <td> World + (Total)</td>\n",
        "      <td> 2736</td>\n",
        "      <td>   Offals, Edible</td>\n",
        "      <td> 121</td>\n",
        "      <td> 5123</td>\n",
        "      <td> Waste</td>\n",
        "      <td> 1971</td>\n",
        "      <td> 1000 tonnes</td>\n",
        "      <td> 79</td>\n",
        "      <td> A</td>\n",
        "    </tr>\n",
        "  </tbody>\n",
        "</table>\n",
        "<p>2 rows \u00d7 11 columns</p>\n",
        "</div>"
       ],
       "metadata": {},
       "output_type": "pyout",
       "prompt_number": 425,
       "text": [
        "         CountryCode          Country  ItemCode              Item  \\\n",
        "4866489         5000  World + (Total)      2945  Offals + (Total)   \n",
        "4867203         5000  World + (Total)      2736    Offals, Edible   \n",
        "\n",
        "         ElementGroup  ElementCode Element  Year         Unit  Value Flag  \n",
        "4866489           121         5123   Waste  1971  1000 tonnes     79    A  \n",
        "4867203           121         5123   Waste  1971  1000 tonnes     79    A  \n",
        "\n",
        "[2 rows x 11 columns]"
       ]
      }
     ],
     "prompt_number": 425
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "supply1 = get_data(7)\n",
      "supply2 = get_data(8)"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [],
     "prompt_number": 87
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "from IPython.display import HTML\n",
      "HTML('<iframe src=http://127.0.0.1:8898/ width=1080 height=670></iframe>') \n",
      "#HTML('<iframe src=http://food.csaladen.es width=1080 height=600></iframe>') "
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "html": [
        "<iframe src=http://127.0.0.1:8898/ width=1080 height=670></iframe>"
       ],
       "metadata": {},
       "output_type": "pyout",
       "prompt_number": 45,
       "text": [
        "<IPython.core.display.HTML at 0x4f39c3c8>"
       ]
      }
     ],
     "prompt_number": 45
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "r = requests.get('http://www.fao.org/fileadmin/templates/ess/ess_test_folder/Food_security/Excel_sheets/Nutritive_Factors.xls')\n",
      "#xl = pd.ExcelFile(r.content)\n",
      "#xl\n",
      "#ind =10\n",
      "#if localpath:\n",
      "#    r = masterpath+indicators[ind]+'.zip'\n",
      "#    z = zipfile.ZipFile(r)\n",
      "#else:\n",
      "#    r = requests.get(masterpath+indicators[ind]+'.zip')\n",
      "#    z = zipfile.ZipFile(StringIO.StringIO(r.content))\n",
      "#data = pd.read_csv(z.open(indicators[ind]+'.csv'))\n",
      "#data.head()\n",
      "r.content\n",
      "nutri = pd.read_excel(masterpath+'Nutritive_Factors.xls','Sheet1')\n",
      "nutri"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "html": [
        "<div style=\"max-height:1000px;max-width:1500px;overflow:auto;\">\n",
        "<table border=\"1\" class=\"dataframe\">\n",
        "  <thead>\n",
        "    <tr style=\"text-align: right;\">\n",
        "      <th></th>\n",
        "      <th>Nutritive factors</th>\n",
        "      <th>Unnamed: 1</th>\n",
        "      <th>Unnamed: 2</th>\n",
        "      <th>Unnamed: 3</th>\n",
        "    </tr>\n",
        "  </thead>\n",
        "  <tbody>\n",
        "    <tr>\n",
        "      <th>0 </th>\n",
        "      <td> FOOD AND AGRICULTURE ORGANIZATION OF THE UNITE...</td>\n",
        "      <td>               NaN</td>\n",
        "      <td>             NaN</td>\n",
        "      <td>             NaN</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>1 </th>\n",
        "      <td>                                         COMMODITY</td>\n",
        "      <td>          calories</td>\n",
        "      <td>         protein</td>\n",
        "      <td>             fat</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>2 </th>\n",
        "      <td>                                               NaN</td>\n",
        "      <td> (per 100 grammes)</td>\n",
        "      <td> (mg per gramme)</td>\n",
        "      <td> (mg per gramme)</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>3 </th>\n",
        "      <td>                                      ALFALFA MEAL</td>\n",
        "      <td>               265</td>\n",
        "      <td>             305</td>\n",
        "      <td>              20</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>4 </th>\n",
        "      <td>                                          ALMONDS </td>\n",
        "      <td>               236</td>\n",
        "      <td>              80</td>\n",
        "      <td>             209</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>5 </th>\n",
        "      <td>                                  ALMONDS SHELLED </td>\n",
        "      <td>               589</td>\n",
        "      <td>             200</td>\n",
        "      <td>             522</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>6 </th>\n",
        "      <td>                                            ANISE </td>\n",
        "      <td>               345</td>\n",
        "      <td>             158</td>\n",
        "      <td>             149</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>7 </th>\n",
        "      <td>                         APPLE JUICE CONCENTRATED </td>\n",
        "      <td>               166</td>\n",
        "      <td>               5</td>\n",
        "      <td>               4</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>8 </th>\n",
        "      <td>                      APPLE JUICE SINGLE STRENGTH </td>\n",
        "      <td>                47</td>\n",
        "      <td>               1</td>\n",
        "      <td>               1</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>9 </th>\n",
        "      <td>                                           APPLES </td>\n",
        "      <td>                48</td>\n",
        "      <td>               1</td>\n",
        "      <td>               3</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>10</th>\n",
        "      <td>                                         APRICOTS </td>\n",
        "      <td>                45</td>\n",
        "      <td>              13</td>\n",
        "      <td>               4</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>11</th>\n",
        "      <td>                                       ARECA NUTS </td>\n",
        "      <td>               245</td>\n",
        "      <td>              49</td>\n",
        "      <td>              44</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>12</th>\n",
        "      <td>                                       ARTICHOKES </td>\n",
        "      <td>                20</td>\n",
        "      <td>              11</td>\n",
        "      <td>               1</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>13</th>\n",
        "      <td>                                        ASPARAGUS </td>\n",
        "      <td>                12</td>\n",
        "      <td>              16</td>\n",
        "      <td>               1</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>14</th>\n",
        "      <td>                                         AVOCADOS </td>\n",
        "      <td>               119</td>\n",
        "      <td>              15</td>\n",
        "      <td>             113</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>15</th>\n",
        "      <td>                                       BACON PIGS </td>\n",
        "      <td>               362</td>\n",
        "      <td>             131</td>\n",
        "      <td>             341</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>16</th>\n",
        "      <td>                                      BAMBARA BEAN</td>\n",
        "      <td>               365</td>\n",
        "      <td>             177</td>\n",
        "      <td>              63</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>17</th>\n",
        "      <td>                                          BANANAS </td>\n",
        "      <td>                60</td>\n",
        "      <td>               7</td>\n",
        "      <td>               3</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>18</th>\n",
        "      <td>                                           BARLEY </td>\n",
        "      <td>               332</td>\n",
        "      <td>             120</td>\n",
        "      <td>              18</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>19</th>\n",
        "      <td>                            BARLEY FLOUR AND GRITS</td>\n",
        "      <td>               343</td>\n",
        "      <td>              92</td>\n",
        "      <td>              17</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>20</th>\n",
        "      <td>                                      BARLEY PEARL</td>\n",
        "      <td>               346</td>\n",
        "      <td>              90</td>\n",
        "      <td>              14</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>21</th>\n",
        "      <td>                                         BEANS DRY</td>\n",
        "      <td>               341</td>\n",
        "      <td>             221</td>\n",
        "      <td>              17</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>22</th>\n",
        "      <td>                                       BEANS GREEN</td>\n",
        "      <td>                50</td>\n",
        "      <td>              30</td>\n",
        "      <td>               4</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>23</th>\n",
        "      <td>                                      BEEF BONLESS</td>\n",
        "      <td>               150</td>\n",
        "      <td>             185</td>\n",
        "      <td>              79</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>24</th>\n",
        "      <td>                                      BEEF CANNED </td>\n",
        "      <td>               233</td>\n",
        "      <td>             250</td>\n",
        "      <td>             140</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>25</th>\n",
        "      <td>                         BEEF DRIED, SALT, SMOKED </td>\n",
        "      <td>               203</td>\n",
        "      <td>             343</td>\n",
        "      <td>              63</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>26</th>\n",
        "      <td>                                BEEF PREPARATIONS </td>\n",
        "      <td>               233</td>\n",
        "      <td>             250</td>\n",
        "      <td>             140</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>27</th>\n",
        "      <td>                                        BEEF VEAL </td>\n",
        "      <td>               225</td>\n",
        "      <td>             147</td>\n",
        "      <td>             180</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>28</th>\n",
        "      <td>                                      BEER BARLEY </td>\n",
        "      <td>                49</td>\n",
        "      <td>               5</td>\n",
        "      <td>               0</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>29</th>\n",
        "      <td>                                       BEER MAIZE </td>\n",
        "      <td>                40</td>\n",
        "      <td>               4</td>\n",
        "      <td>               0</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>30</th>\n",
        "      <td>                                      BEER MILLET </td>\n",
        "      <td>                40</td>\n",
        "      <td>               4</td>\n",
        "      <td>               0</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>31</th>\n",
        "      <td>                                      BEER SORGHUM</td>\n",
        "      <td>                40</td>\n",
        "      <td>               4</td>\n",
        "      <td>               0</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>32</th>\n",
        "      <td>                                    BEET PULP DRY </td>\n",
        "      <td>               288</td>\n",
        "      <td>             111</td>\n",
        "      <td>               6</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>33</th>\n",
        "      <td>                                      BERRIES NES </td>\n",
        "      <td>                49</td>\n",
        "      <td>              10</td>\n",
        "      <td>               7</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>34</th>\n",
        "      <td>                   BEVERAGES DISTILLED. ALCOHOLIC </td>\n",
        "      <td>               295</td>\n",
        "      <td>               0</td>\n",
        "      <td>               0</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>35</th>\n",
        "      <td>                           BEVERAGES NON ALCOHOLIC</td>\n",
        "      <td>                39</td>\n",
        "      <td>               0</td>\n",
        "      <td>               0</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>36</th>\n",
        "      <td>                                      BLUEBERRIES </td>\n",
        "      <td>               120</td>\n",
        "      <td>               7</td>\n",
        "      <td>               4</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>37</th>\n",
        "      <td>                                        BRAN RICE </td>\n",
        "      <td>               276</td>\n",
        "      <td>             133</td>\n",
        "      <td>             158</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>38</th>\n",
        "      <td>                                       BRAN WHEAT </td>\n",
        "      <td>               213</td>\n",
        "      <td>             121</td>\n",
        "      <td>              31</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>39</th>\n",
        "      <td>                                      BRAZIL NUTS </td>\n",
        "      <td>               315</td>\n",
        "      <td>              69</td>\n",
        "      <td>             318</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>40</th>\n",
        "      <td>                                 BRAZILNUT SHELLED</td>\n",
        "      <td>               656</td>\n",
        "      <td>             143</td>\n",
        "      <td>             662</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>41</th>\n",
        "      <td>                               BROAD BEANS GROUND </td>\n",
        "      <td>                23</td>\n",
        "      <td>              23</td>\n",
        "      <td>               1</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>42</th>\n",
        "      <td>                                   BROAD BEANS DRY</td>\n",
        "      <td>               343</td>\n",
        "      <td>             234</td>\n",
        "      <td>              20</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>43</th>\n",
        "      <td>                                            BREAD </td>\n",
        "      <td>               249</td>\n",
        "      <td>              82</td>\n",
        "      <td>              12</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>44</th>\n",
        "      <td>                               BREAKFEAST CERLEALS</td>\n",
        "      <td>               389</td>\n",
        "      <td>              74</td>\n",
        "      <td>               7</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>45</th>\n",
        "      <td>                                        BUCKWHEAT </td>\n",
        "      <td>               330</td>\n",
        "      <td>             120</td>\n",
        "      <td>              20</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>46</th>\n",
        "      <td>                                      BUFFALO MEAT</td>\n",
        "      <td>                77</td>\n",
        "      <td>             113</td>\n",
        "      <td>              31</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>47</th>\n",
        "      <td>                                      BUFFALO MILK</td>\n",
        "      <td>                97</td>\n",
        "      <td>              38</td>\n",
        "      <td>              69</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>48</th>\n",
        "      <td>                                           BULGUR </td>\n",
        "      <td>               345</td>\n",
        "      <td>             123</td>\n",
        "      <td>              20</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>49</th>\n",
        "      <td>                               BUTTER BUFFALO/td&gt; </td>\n",
        "      <td>               717</td>\n",
        "      <td>               9</td>\n",
        "      <td>             811</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>50</th>\n",
        "      <td>                                      BUTTER SHEEP</td>\n",
        "      <td>               716</td>\n",
        "      <td>               6</td>\n",
        "      <td>             810</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>51</th>\n",
        "      <td>                                       BUTTER COWS</td>\n",
        "      <td>               717</td>\n",
        "      <td>               9</td>\n",
        "      <td>             811</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>52</th>\n",
        "      <td>                                       BUTTER GOAT</td>\n",
        "      <td>               717</td>\n",
        "      <td>               9</td>\n",
        "      <td>             811</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>53</th>\n",
        "      <td>                               BUTTER CURDLED MILK</td>\n",
        "      <td>                75</td>\n",
        "      <td>              30</td>\n",
        "      <td>              52</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>54</th>\n",
        "      <td>                                         CABBAGES </td>\n",
        "      <td>                19</td>\n",
        "      <td>              10</td>\n",
        "      <td>               1</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>55</th>\n",
        "      <td>                                CAKE OF GROUNDNUTS</td>\n",
        "      <td>               363</td>\n",
        "      <td>             417</td>\n",
        "      <td>              76</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>56</th>\n",
        "      <td>                              CAKE OF SESAME SEED </td>\n",
        "      <td>               376</td>\n",
        "      <td>             407</td>\n",
        "      <td>              34</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>57</th>\n",
        "      <td>                                      CAKE SOYBEAN</td>\n",
        "      <td>               261</td>\n",
        "      <td>             460</td>\n",
        "      <td>              50</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>58</th>\n",
        "      <td>                                       CAMEL MILK </td>\n",
        "      <td>                73</td>\n",
        "      <td>              38</td>\n",
        "      <td>              45</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th>59</th>\n",
        "      <td>                                      CANARY SEED </td>\n",
        "      <td>               388</td>\n",
        "      <td>             160</td>\n",
        "      <td>              60</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <th></th>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "    </tr>\n",
        "  </tbody>\n",
        "</table>\n",
        "<p>442 rows \u00d7 4 columns</p>\n",
        "</div>"
       ],
       "metadata": {},
       "output_type": "pyout",
       "prompt_number": 86,
       "text": [
        "                                    Nutritive factors         Unnamed: 1  \\\n",
        "0   FOOD AND AGRICULTURE ORGANIZATION OF THE UNITE...                NaN   \n",
        "1                                           COMMODITY           calories   \n",
        "2                                                 NaN  (per 100 grammes)   \n",
        "3                                        ALFALFA MEAL                265   \n",
        "4                                            ALMONDS                 236   \n",
        "5                                    ALMONDS SHELLED                 589   \n",
        "6                                              ANISE                 345   \n",
        "7                           APPLE JUICE CONCENTRATED                 166   \n",
        "8                        APPLE JUICE SINGLE STRENGTH                  47   \n",
        "9                                             APPLES                  48   \n",
        "10                                          APRICOTS                  45   \n",
        "11                                        ARECA NUTS                 245   \n",
        "12                                        ARTICHOKES                  20   \n",
        "13                                         ASPARAGUS                  12   \n",
        "14                                          AVOCADOS                 119   \n",
        "15                                        BACON PIGS                 362   \n",
        "16                                       BAMBARA BEAN                365   \n",
        "17                                           BANANAS                  60   \n",
        "18                                            BARLEY                 332   \n",
        "19                             BARLEY FLOUR AND GRITS                343   \n",
        "20                                       BARLEY PEARL                346   \n",
        "21                                          BEANS DRY                341   \n",
        "22                                        BEANS GREEN                 50   \n",
        "23                                       BEEF BONLESS                150   \n",
        "24                                       BEEF CANNED                 233   \n",
        "25                          BEEF DRIED, SALT, SMOKED                 203   \n",
        "26                                 BEEF PREPARATIONS                 233   \n",
        "27                                         BEEF VEAL                 225   \n",
        "28                                       BEER BARLEY                  49   \n",
        "29                                        BEER MAIZE                  40   \n",
        "30                                       BEER MILLET                  40   \n",
        "31                                       BEER SORGHUM                 40   \n",
        "32                                     BEET PULP DRY                 288   \n",
        "33                                       BERRIES NES                  49   \n",
        "34                    BEVERAGES DISTILLED. ALCOHOLIC                 295   \n",
        "35                            BEVERAGES NON ALCOHOLIC                 39   \n",
        "36                                       BLUEBERRIES                 120   \n",
        "37                                         BRAN RICE                 276   \n",
        "38                                        BRAN WHEAT                 213   \n",
        "39                                       BRAZIL NUTS                 315   \n",
        "40                                  BRAZILNUT SHELLED                656   \n",
        "41                                BROAD BEANS GROUND                  23   \n",
        "42                                    BROAD BEANS DRY                343   \n",
        "43                                             BREAD                 249   \n",
        "44                                BREAKFEAST CERLEALS                389   \n",
        "45                                         BUCKWHEAT                 330   \n",
        "46                                       BUFFALO MEAT                 77   \n",
        "47                                       BUFFALO MILK                 97   \n",
        "48                                            BULGUR                 345   \n",
        "49                                BUTTER BUFFALO/td>                 717   \n",
        "50                                       BUTTER SHEEP                716   \n",
        "51                                        BUTTER COWS                717   \n",
        "52                                        BUTTER GOAT                717   \n",
        "53                                BUTTER CURDLED MILK                 75   \n",
        "54                                          CABBAGES                  19   \n",
        "55                                 CAKE OF GROUNDNUTS                363   \n",
        "56                               CAKE OF SESAME SEED                 376   \n",
        "57                                       CAKE SOYBEAN                261   \n",
        "58                                        CAMEL MILK                  73   \n",
        "59                                       CANARY SEED                 388   \n",
        "                                                  ...                ...   \n",
        "\n",
        "         Unnamed: 2       Unnamed: 3  \n",
        "0               NaN              NaN  \n",
        "1           protein              fat  \n",
        "2   (mg per gramme)  (mg per gramme)  \n",
        "3               305               20  \n",
        "4                80              209  \n",
        "5               200              522  \n",
        "6               158              149  \n",
        "7                 5                4  \n",
        "8                 1                1  \n",
        "9                 1                3  \n",
        "10               13                4  \n",
        "11               49               44  \n",
        "12               11                1  \n",
        "13               16                1  \n",
        "14               15              113  \n",
        "15              131              341  \n",
        "16              177               63  \n",
        "17                7                3  \n",
        "18              120               18  \n",
        "19               92               17  \n",
        "20               90               14  \n",
        "21              221               17  \n",
        "22               30                4  \n",
        "23              185               79  \n",
        "24              250              140  \n",
        "25              343               63  \n",
        "26              250              140  \n",
        "27              147              180  \n",
        "28                5                0  \n",
        "29                4                0  \n",
        "30                4                0  \n",
        "31                4                0  \n",
        "32              111                6  \n",
        "33               10                7  \n",
        "34                0                0  \n",
        "35                0                0  \n",
        "36                7                4  \n",
        "37              133              158  \n",
        "38              121               31  \n",
        "39               69              318  \n",
        "40              143              662  \n",
        "41               23                1  \n",
        "42              234               20  \n",
        "43               82               12  \n",
        "44               74                7  \n",
        "45              120               20  \n",
        "46              113               31  \n",
        "47               38               69  \n",
        "48              123               20  \n",
        "49                9              811  \n",
        "50                6              810  \n",
        "51                9              811  \n",
        "52                9              811  \n",
        "53               30               52  \n",
        "54               10                1  \n",
        "55              417               76  \n",
        "56              407               34  \n",
        "57              460               50  \n",
        "58               38               45  \n",
        "59              160               60  \n",
        "                ...              ...  \n",
        "\n",
        "[442 rows x 4 columns]"
       ]
      }
     ],
     "prompt_number": 86
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "categories = pd.read_excel(masterpath+'Commodities_which_are_aggregated_or_standardized.xls','Sheet1')\n",
      "categories.head()\n",
      "categories[categories.WHEAT=='APPLES']"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "html": [
        "<div style=\"max-height:1000px;max-width:1500px;overflow:auto;\">\n",
        "<table border=\"1\" class=\"dataframe\">\n",
        "  <thead>\n",
        "    <tr style=\"text-align: right;\">\n",
        "      <th></th>\n",
        "      <th>WHEAT &amp; PRODUCTS </th>\n",
        "      <th>Unnamed: 1</th>\n",
        "      <th>Unnamed: 2</th>\n",
        "      <th>WHEAT</th>\n",
        "    </tr>\n",
        "  </thead>\n",
        "  <tbody>\n",
        "    <tr>\n",
        "      <th>628</th>\n",
        "      <td> APPLES &amp; PRODUCTS </td>\n",
        "      <td>NaN</td>\n",
        "      <td>NaN</td>\n",
        "      <td> APPLES</td>\n",
        "    </tr>\n",
        "  </tbody>\n",
        "</table>\n",
        "<p>1 rows \u00d7 4 columns</p>\n",
        "</div>"
       ],
       "metadata": {},
       "output_type": "pyout",
       "prompt_number": 46,
       "text": [
        "      WHEAT & PRODUCTS   Unnamed: 1  Unnamed: 2   WHEAT\n",
        "628  APPLES & PRODUCTS          NaN         NaN  APPLES\n",
        "\n",
        "[1 rows x 4 columns]"
       ]
      }
     ],
     "prompt_number": 46
    }
   ],
   "metadata": {}
  }
 ]
}